### ISSUE TITLE
[BUG]Rename-PnPTenantSite are not working as expected in Tenants with vanity url.

### ISSUE THREAD

**Issue by SouptakRoy** [pnp/powershell#3520] opened 2023-10-19 03:17 UTC
Reporting an Issue or Missing Feature
**Issue:**
Rename-PnPTenantSite are not working as expected in Tenants with vanity url.
Site URL – https://contoso-xyz.sharepoint.com/
Admin URL - https://contosoadmin-xyz.sharepoint.com/
The error message shows wrong tenant url if we connect to Site URL only. If we connect using Tenant Admin URL it shows below error –
Rename-PnPTenantSite : An error occurred while sending the request.
**Expected behavior**
Expected behavior is to Rename SPO Site URL without any error.
**Actual behavior**
If we connect using SPO Site URL only, we get wrong tenant error as it tries to form Tenant Admin url dynamically and goes to wrong url. Same like https://github.com/pnp/powershell/issues/137 and https://github.com/pnp/powershell/issues/2567

Connect-PnPOnline -Url "https://contoso-xyz.sharepoint.com/sites/Test" -Interactive

Rename-PnPTenantSite : Unable to connect to the SharePoint Online Admin Center at ‘https://contoso-xyz-admin.sharepoint.com/' to run this cmdlet. Please ensure you pass in the
correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl and you have access to it. Error message: AADSTS500011: The resource principal named
‘https://contoso-xyz-admin.sharepoint.com/' was not found in the tenant named XYZ. This can happen if the application has not been installed by the administrator of the tenant or
consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.

Timestamp: 2023-10-18 21:37:26Z.
At line:1 char:1

Rename-PnPTenantSite -Identity $currentSiteUrl -NewSiteUrl $updatedSi ...
  + CategoryInfo          : InvalidOperation: (:) [Rename-PnPTenantSite], PSInvalidOperationException
  + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Admin.RenameTenantSite

If we try to connect with Tenant Admin url, it shows “An error occurred while sending the request.”

Connect-PnPOnline -TenantAdminUrl "[https://contosoadmin-xyz.sharepoint.com”](https://contosoadmin-xyz.sharepoint.xn--com-9o0a/) -Url "https://contoso-xyz.sharepoint.com/sites/Test" -Interactive
Rename-PnPTenantSite -Identity $currentSiteUrl -NewSiteUrl $updatedSiteUrl

Rename-PnPTenantSite : An error occurred while sending the request.
At line:1 char:1

Rename-PnPTenantSite -Identity $currentSiteUrl -NewSiteUrl $updatedSi ...
  + CategoryInfo          : WriteError: (:) [Rename-PnPTenantSite], HttpRequestException
  + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.RenameTenantSite
**Steps to reproduce behavior**
Connect-PnPOnline -TenantAdminUrl "[https://contosoadmin-xyz.sharepoint.com”](https://contosoadmin-xyz.sharepoint.xn--com-9o0a/) -Url "https://contoso-xyz.sharepoint.com/sites/Test" -Interactive
Rename-PnPTenantSite -Identity $currentSiteUrl -NewSiteUrl $updatedSiteUrl
What is the version of the Cmdlet module you are running?
ModuleType Version Name ExportedCommands

Manifest 1.12.0 PnP.PowerShell {Add-PnPAdaptiveScopeProperty, Add-PnPPropertyBagValue, Add-PnPSiteClassification, Copy-PnPFolder...}
**Which operating system/environment are you running PnP PowerShell on?**
• [ x] Windows
• Linux
• MacOS
• Azure Cloud Shell
• Azure Functions
• Other : please specify

**Comment by gautamdsheth** [comment] 2023-10-22 18:32
hi @SouptakRoy , did you specify the `TenantAdminUrl` parameter when connecting using `Connect-PnPOnline` and try ? 

https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#-tenantadminurl

You will need it since vanity URLs are kinda special tenants

**Comment by SouptakRoy** [comment] 2023-10-23 12:45
@gautamdsheth - Thanks for your response. I did, as you can see here -
Connect-PnPOnline -TenantAdminUrl "https://contosoadmin-xyz.sharepoint.com” -Url "https://contoso-xyz.sharepoint.com/sites/Test" -Interactive
Rename-PnPTenantSite -Identity $currentSiteUrl -NewSiteUrl $updatedSiteUrl

Rename operation still fails, however Get-PNPTenantSite works with Tenantadminurl. If some code changes which were done in Get-PNPTenantSite to get it working for Vanity url tenants work, can be synced with Rename-PNPTenantSite too - that might fix the issue.

**Comment by koskila** [comment] 2023-10-24 17:51
Took a look into the code for this one - this might be caused by the commandlet using this method in UrlUtilities class for ensuring the URL, that blatantly ignores the possibility of a vanity URL existing:
![image](https://github.com/pnp/powershell/assets/4086860/5a1c0e15-4cdb-453b-8cb2-e0664a310f1b)

This is done despite the AdminContext already having, well, tenant admin url (it supports vanity domains).

![image](https://github.com/pnp/powershell/assets/4086860/9d93d264-96f0-4fc7-aa6f-40ee88cee2cf)

There's probably a reason this is done this way, but I wonder if we can just remove the extra validation in this case? Or alternatively, somehow verify if the passed url is in fact a "vanity admin url"...

**Comment by koskila** [comment] 2023-10-24 19:25
I guess a fix could be as simple as this:
https://github.com/pnp/powershell/compare/dev...koskila:pnppowershell:bugfix/3520

**Comment by SouptakRoy** [comment] 2023-10-26 04:11
Thanks a lot @koskila , will wait and test it once available for our vanity tenant. Is this included in today's 2.2.110-nightly release?

**Comment by koskila** [comment] 2023-10-26 11:05
Appreciate it @SouptakRoy, I don't have a tenant like that myself so my testing has been very theoretical... :D

The change is not merged yet, I believe after merging (if accepted) it'll be available in the next nightly... Right, @gautamdsheth?

**Comment by veronicageek** [comment] 2023-10-26 20:22
Yes, once merged, it will be available in the nightly the day after indeed 🙂

**Comment by gautamdsheth** [comment] 2023-10-30 08:14
@SouptakRoy - has been fixed in the latest nightly builds by @koskila .

Closing this now.

**Closed by gautamdsheth** 2023-10-30 08:14 UTC
Labels: bug, more info needed
