### ISSUE TITLE
Duplicate Field Name "Service_x0020_Group" was found

### ISSUE THREAD

**Issue by PraveenS091213** [pnp/powershell#1350] opened 2021-11-16 01:45 UTC
### Discussed in https://github.com/pnp/powershell/discussions/1345

<div type='discussions-op-text'>

<sup>Originally posted by **PraveenS091213** November 13, 2021</sup>
Hello Team,

Good day!

My name is Praveen and i am working on a scenario. 

We have a SharePoint Online Team site created. This team site has site columns with "Single Line of Text", "Choice", & "MMS" column types. These site columns are used on a document library.

This site is used by the clients and there was a request to add couple of new columns to the list (of type Single line of text) and re-order the columns.

We have about 150 client sites and it had to be done on all the sites. To make the job simpler, we created a teamsite and incorporated all the changes requested by the client and used the following command to create a site template

Get-PnPProvisioningTemplate -Out "clientsitetemplate.pnp" -ExcludeHandlers ApplicationLifecycleManagement, SiteSecurity -ExcludeContentTypesFromSyndication 

This template was then uploaded to the "Site Assets" library.

Post this, we used the following command to apply the template to one of the client sites and got the error

Invoke-PnPSiteTemplate -Path https://wipflillp.sharepoint.com/SiteAssets/clientsitetemplate.pnp -ClearNavigation -WarningAction ignore

Error Message:
Invoke-PnPSiteTemplate : A duplicate field name "Service_x0020_Group" was found.
At line:1 char:1
+ Invoke-PnPSiteTemplate -Path https://wipflillp.sharepoint.com/SiteAss ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Invoke-PnPSiteTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.InvokeSiteTemplate

The existing client sites have the field called "Service Group" (internal name Service_x0029_Group). This field is coming from the site columns.

I am trying for options to successfully apply the template to the existing client sites but not able to get past this error. Could you please let me know if there is an option to force apply / ignore duplicate field names / any other action plan to get around this issue?

Thank you,

Regards,

Praveen</div>

**Comment by gautamdsheth** [comment] 2021-12-18 18:46
@PraveenS091213 - the issue is not clear at all. 

Please create the issue with the specified issue template with clear steps to reproduce it , we can't help if there is no way to repro it.  Sorry will have to close it. 

Please create a new issue with the specified template with clear steps to reproduce the error,  which is available here - 

https://github.com/pnp/powershell/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D

**Closed by gautamdsheth** 2021-12-18 18:46 UTC
