### ISSUE TITLE
[BUG] using -ReturnConnection when connecting to SPO and not using it when calling cmdlets will throw exception

### ISSUE THREAD

**Issue by AndersRask** [pnp/powershell#2958] opened 2023-03-31 10:59 UTC
### Reporting an Issue or Missing Feature
ISSUE 
Breaking change from 1.10.0 to 1.12.0 that including `-ReturnConnection` on `Connect-PnPOnline` and not using `-Connection` parameter on cmdlets will result in `InvalidOperationException`

### Expected behavior 
In earlier versions you could specify -ReturnConnection when connecting to SharePoint Online, and not use it, as the connection was "given" implicitly as latest connection. 

```
# example 1: with -ReturnConnection and not using -Connection 
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive -ReturnConnection
Get-PnPList
Disconnect-PnPOnline
# Would list all lists on site collection

# example 2: omitting -ReturnConnection would also work
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive 
Get-PnPList
Disconnect-PnPOnline
# Would list all lists on site collection

# example 3: with -ReturnConnection using -Connection
$connection = Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive -ReturnConnection
Get-PnPList -Connection $connection
Disconnect-PnPOnline
# Would list all lists on site collection
```

### Actual behavior 
Example 1 will no longer work in 1.12.0 introducing a breaking change in a minor version change.
**This may very well be pr design as of the connection rework also of disconnecting connections, but since it is a breaking change, this breaks code that would work in earlier versions it would be nice with backward compatibility handling, like a warning or error if you use -ReturnConnection** 

```
# including -ReturnConnection and not using it will throw error
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive -ValidateConnection -ReturnConnection
Get-PnPList
# In 1.12.0 this will now return an InvalidOperationException:
Get-PnPList: The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect.
```

### Steps to reproduce behavior
run the code below in 1.10.0 and 1.12.0 and notice that ex 1 will throw error
```
# example 1: with -ReturnConnection and not using -Connection 
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive -ReturnConnection
Get-PnPList
Disconnect-PnPOnline
# Would list all lists on site collection but only in v1.10.0

# example 2: omitting -ReturnConnection would also work
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive 
Get-PnPList
Disconnect-PnPOnline
# Would list all lists on site collection

# example 3: with -ReturnConnection using -Connection
$connection = Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com/" -Interactive -ReturnConnection
Get-PnPList -Connection $connection
Disconnect-PnPOnline
# Would list all lists on site collection
```

### What is the version of the Cmdlet module you are running?
1.10.0 and 1.120.

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment] 2023-04-01 09:09
This is by design as it doesn't make sense to return a connection while not doing anything with the returned connection. It could lead to scenarios where you wouldn't know anymore what context you were operating on. This has been explained before when 1.12 came out. I'll try to find the discussion thread so you can read up on it.

**Comment by KoenZomers** [comment] 2023-04-01 09:18
Can't quickly find the threads back in which it has been discussed. I see it was changed in 1.11 already by the way, so nearly a year ago. Going forward from 1.11 the use of `-ReturnConnection` will not set the default context. If you wan to set up multiple connections to different sites, just connect on the default context first (so without -ReturnConnection) and then build up your connections using -ReturnConnection to as many sites as you want and they will reuse the authentication from the default context.

**Comment by AndersRask** [comment] 2023-04-01 09:22
I suspected as much, but it's still a breaking change, so a warning like
when usi g disconnect would be a good thing to do 😉
It can be hard to remember connection parameter on each and every cmdlet
and what worked before will now break if you upgrade

lør. 1. apr. 2023 11.09 skrev Koen Zomers ***@***.***>:

**Comment by veronicageek** [comment] 2023-04-11 13:31
> Can't quickly find the threads back in which it has been discussed

Here it is: Issue #2071 

Closing now.

**Closed by veronicageek** 2023-04-11 13:31 UTC
Labels: not a bug
