### ISSUE TITLE
Add-PnPContentTypesFromContentTypeHub , wrong sync for Content Type where the parent is missing

### ISSUE THREAD

**Issue by kasperbolarsen** [pnp/powershell#940] opened 2021-07-26 08:38 UTC
### Reporting an Issue or Missing Feature
I am not sure if this is a bug or just a weird "works as designed" ?

### Expected behavior 
I would expect that Add-PnPContentTypesFromContentTypeHub would fail if the parent of the current Content Type is not available at the target site collection.

### Actual behavior 

![image](https://user-images.githubusercontent.com/20593570/126958988-a1c919c2-0792-4b4d-a902-9cf33dd9995b.png)

### Steps to reproduce behavior
Add a Content Type "HubContenttypeA" to the hub and publish it, parent = Item
Add a Content Type "HubContenttypeAB" to the hub and publish it, parent = "A", note the content type ID

$list = New-Object Collections.Generic.List[string]
 $list.Add('the content type id of "HubContenttypeAB"')
run Add-PnPContentTypesFromContentTypeHub -Contenttypes $list

Note that "HubContenttypeAB" is sync'ed however the parent is now "item", not "A"

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2021-07-27 14:29
Closing as this is by design.

**Closed by veronicageek** 2021-07-27 14:29 UTC
Labels: azure-automation, bug
