### ISSUE TITLE
[BUG] Set-PnPSite -Owners Get Stuck

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#770] opened 2021-06-08 12:32 UTC
### Reporting an Issue or Missing Feature
When you connect to an admin site and run `Set-PnPSite` to change site owner of some other site, command would just stuck - no error, no command prompt, no nothing.

### Expected behavior 
If you run `Set-PnPSite` instead of `Set-PnPTenantSite` while connected to Admin portal https://contoso-admin.sharepoint.com it should throw some error

### Actual behavior 
Command stuck running
![image](https://user-images.githubusercontent.com/5260172/121185425-bbf0a480-c86e-11eb-9dcf-8029455461dc.png)

### Steps to reproduce behavior
```
Connect-PnPOnline https://contoso-admin.sharepoint.com 
Set-PnPSite https://contoso.sharepoint.com/sites/test-site
```
### What is the version of the Cmdlet module you are running?
`PnP,PowerShell 1.6.0`

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2021-06-08 13:24
@YuriySamorodov - No issue here on `1.6.0`, and it took 2s to run. Also FYI, the `Set-PnPSite` will not change the admins, it will add whoever is in the `-Owners`
However, I can see on your screenshot that your URL is a ODFB site?

![image](https://user-images.githubusercontent.com/25181757/121192765-2ac90000-c865-11eb-84e0-54630404c313.png)

**Comment by YuriySamorodov** [comment] 2021-06-08 15:11
@veronicageek 
> However, I can see on your screenshot that your URL is a ODFB site?
This is correct.

**Comment by veronicageek** [comment] 2021-06-08 17:47
Thanks. I've re-read your issue and can reproduce it.

**Comment by YuriySamorodov** [comment] 2021-06-23 07:36
Hi @veronicageek , is there any progress on this?

**Comment by KoenZomers** [comment] 2021-09-23 21:26
Looking into this one.

**Comment by KoenZomers** [comment] 2021-09-23 21:29
Found the issue. It's really specific when using it with a OneDrive URL only. Looking into how to fix this.

**Comment by KoenZomers** [comment] 2021-09-23 21:36
Fixed it. Releasing PR.

**Comment by KoenZomers** [comment] 2021-09-23 21:41
Once the PR has been merged, during the next day you can use the latest prerelease to try this out. Assuming the issue is fixed with this PR, I'm closing this issue. If it turns out still not to work well for you with this fix, feel free to reopen this issue.

**Closed by KoenZomers** 2021-09-23 21:41 UTC
Labels: bug, reproduced
