### ISSUE TITLE
New-PnPSite can't create new team site

### ISSUE THREAD

**Issue by tina-palomino** [pnp/powershell#405] opened 2021-03-10 15:23 UTC
### Reporting an Issue or Missing Feature
Reporting and issue with New-PnPSite, the condole hangs after I run the script. They O365 group is created but the site isn't.

### Expected behavior 
Team site and O365 group assigned get created.

### Actual behavior 
O365 group is created but team site isn't.

### Steps to reproduce behavior
Running PowerShell 7.1 and version 1.3.0 or pnp.powershell. 

#1
#.csv with general access sites details

$sites = Import-Csv C:\Code\SPFileSystem\OpsGeneralAccess\OpsGeneralSite.csv

$Creds = Get-Credential 

#2
#SharePointPnP Create sites
#Connect SharePointPnP
Register-PnPManagementShellAccess
Connect-PnPOnline -url "https://xxxxx.sharepoint.com" -Credentials $Creds

foreach ($site in $sites){

New-PnPSite -Type $site.type -Title $site.title -Alias $site.alias

}

### What is the version of the Cmdlet module you are running?

Running PowerShell 7.1 and version 1.3.0 or pnp.powershell. 

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2021-03-10 19:18
Hi @tina-palomino - I can't seem to be able to reproduce your issue, working fine on 1.3.0 and PS7.
Could you try to create only 1 site and not use your .csv file?

**Comment by radityoardi** [comment] 2021-03-15 04:36
@veronicageek me too, encountered the same issue where the site can't be created. The error message also didn't provide a clue of what's going on.
In my case, it was due to the dash or special characters in the URL. Once removed, the site can be created. Can please at least give a clearer error message?
The same issue exists in both v1.3.0 and v1.4.0. I'm using PS 5.1 by the way.

![image](https://user-images.githubusercontent.com/12979499/111103994-9e22e480-858a-11eb-9ec8-6ee8fb29374d.png)

**Comment by veronicageek** [comment] 2021-03-15 14:54
Thank you for your comment @radityoardi
@tina-palomino - I'll close this for now, but do re-open it if you're still facing the issue.

**Closed by veronicageek** 2021-03-15 14:54 UTC
Labels: bug
