### ISSUE TITLE
[BUG] Remove-PnpFile failing in v1.11.0 with parameter issue

### ISSUE THREAD

**Issue by softwareliberationarmy** [pnp/powershell#2099] opened 2022-07-06 16:20 UTC
### Reporting an Issue or Missing Feature
We have a PS script that runs as part of our CI/CD process that installs Pnp.Powershell (no required version) and calls Connect-PnPOnline, Resolve-PnPFolder, Get-PnPFolderItem, and then Remove-PnPFile in a loop (to clean up old files). Starting on July 5th, when v1.11.0 was released, we've noticed that the Remove-PnPFile calls are all failing with what looks like a parameter issue. 

### Expected behavior 
Expecting the Remove-PnPFile command to delete the SP file (actual command syntax being used: `Remove-PnPFile -ServerRelativeUrl $file.ServerRelativeUrl -Force`)

### Actual behavior 
Error output: 
```
Remove-PnPFile : Parameter set cannot be resolved using the specified named parameters.
At D:\a\_temp\680a8da3-2a92-4b2f-bd49-4107237ca3ab.ps1:51 char:5
+     Remove-PnPFile -ServerRelativeUrl $file.ServerRelativeUrl -Force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-PnPFile], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmbiguousParameterSet,PnP.PowerShell.Commands.Files.RemoveFile
PowerShell exited with code '1'.
```
Looking at the [code file](https://github.com/pnp/powershell/blame/dev/src/Commands/Files/RemoveFile.cs), I suspect this might be caused by there being two ParameterSetNames for ServerRelativeUrl (these appear to have been added in 1.11.0), and the Force parameter isn't able to break the tie and decide which ParameterSetName to use, hence the "AmbiguousParameterSet" error. But that's just a guess. 

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)
```
# SharePoint variables
$SharePointUrl = '$(SP.Url)'
$ClientId = '$(SP.ClientId)'
$ClientSecret = '$(SP.ClientSecret)'
$Directory = '$(SP.TargetFolder)\$(Release.Artifacts.SourceBranchName)'

# Archiving variables
$FilesToKeep = 3

If (!(Get-Module -Name Pnp.Powershell)) {
    Install-Module -Name Pnp.Powershell -Scope 'CurrentUser' -Force
    Import-Module -Name Pnp.Powershell
}

Get-Module -Name Pnp.Powershell 

Connect-PnPOnline -Url $SharePointUrl -ClientId $ClientId -ClientSecret $ClientSecret -WarningAction Ignore
$files = Get-PnPFolderItem -FolderSiteRelativeUrl $Directory -ItemType File

$files | Out-Host

#add additional properties
$groupedFiles = $null
$matchedFiles = @()

$pattern = '(?<major>\d+)_(?<minor>\d+)_(?<patch>\d+)_(?<rev>\d+).zip'

foreach ($file in $files) {
    $fileName = $file.Name
    if ($fileName -match $pattern) {
        $file | Add-Member -MemberType NoteProperty -Name 'Major' -Value ([int]$Matches['major'])
        $file | Add-Member -MemberType NoteProperty -Name 'Minor' -Value ([int]$Matches['minor'])
        $file | Add-Member -MemberType NoteProperty -Name 'Patch' -Value ([int]$Matches['patch'])
        $file | Add-Member -MemberType NoteProperty -Name 'Rev' -Value ([int]$Matches['rev'])
        $matchedFiles += $file
    }
    else {
        Write-Host "##vso[task.LogIssue type=warning;] the file '$fileName' did not match the regular expression '$pattern'. The file will be ignored."
    }    
}

$oldFiles = $matchedFiles | Sort-Object 'Major', 'Minor', 'Patch', 'Rev' -Descending | Select-Object -Skip $FilesToKeep

foreach ($file in $oldFiles) {
    Write-Host "Deleting $($File.Name)..."
    Remove-PnPFile -ServerRelativeUrl $file.ServerRelativeUrl -Force  # <<<< THIS LINE FAILS
    Write-Host "$($File.Name) Deleted"
    Start-Sleep -Milliseconds 200 #Sharepoint has thrown errors if Remove-PnPFile or Move-PnpFile are called too quickly
}
```

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x ] Other : please specify - Azure Remote Build Agent running windows-latest

**Comment by marc-pinyol** [comment] 2022-07-08 10:29
Same issue here, downgrade to 1.10.0 allowed to bypass temporarily the problem

**Comment by JazBInKC** [comment] 2022-07-12 13:25
Had a similar issue with Remove-PnPListItem.  That was resolved in 1.10.50

**Comment by Cadder** [comment] 2022-07-23 06:24
**WORKAROUND:**
I gave up trying to get **Remove-PNPFile** to work intuitively, but did find an old article here: [Why Use Remove-PnPListItem vs Remove-PnPFile?](https://threewill.com/why-use-remove-pnplistitem-vs-remove-pnpfile/) which suggested there is a better way anyway.
(In my case, the Remove-PnPFile command is within a separate function _and_ I'm using more than one site, so I _need_ to specify the **-Connection** parameter. You may not find it necessary)

Given: **$pnpFileObj** returns
```
Name         Type Items/Size Last Modified         
----         ---- ---------- -------------         
IMG_1363.jpg File          0 21/03/2018 12:30:36 AM
```
and **$pnpFileObj.ServerRelativeUrl** returns
`/PROJECTS/14/14452/03_Images/Construction/Windows/IMG_1363.jpg`

**$deletedObj = Remove-PnPFile -Connection $Script:Conn -ServerRelativeURL $pnpFileObj.ServerRelativeURL -Recycle -Force**
Fails with:
```
Remove-PnPFile : Value does not fall within the expected range.
At line:1 char:8
+ $del = Remove-PnPFile -Connection $Script:Conn -Se ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPFile], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.RemoveFile
```
    
 INSTEAD: use _**Remove-PNPListitem**_. Thus:
**$deletedObj = Remove-PnPListitem -connection $Script:Conn -identity ($pnpFileObj.Listitemallfields) -Recycle -Force**
works and **$deletedObj** returns 
```
RecycleBinItemId                    
----------------                    
f6c08141-e41b-4a29-af2b-e7d43d38671a
```

**Comment by vreezy** [comment] 2022-07-26 15:02
Workaround
$web = Get-PnPWeb -Connection $site_connection -ErrorVariable error_web -ErrorAction SilentlyContinue;
$path = $web.ServerRelativeUrl + "/SitePages/Home.aspx";
$file = $web.GetFileByServerRelativeUrl($path)  
$file.DeleteObject()
Invoke-PnPQuery -RetryCount 5 -Connection $site_connection;

BTW Pls enable Unit-Test again. thx.

**Comment by milanholemans** [comment] 2022-07-27 23:34
If I'm not mistaken, we can remove all parameter sets. I don't think they are very useful here.
What do you think @KoenZomers @gautamdsheth?

**Comment by damienvanrobaeys** [comment] 2022-07-28 08:42
Same issue here with the 1.11.0, Remove-PnPFile does not work

**Comment by rbishop-etq** [comment] 2022-08-03 17:12
Same problem here. wont let me delete when using -serverrelativeurl OR -siterelativeurl
Remove-PnPFile : Parameter set cannot be resolved using the specified named parameters.

Any news for a fix??

**Comment by milanholemans** [comment] 2022-08-04 15:58
I made a fix for this issue. Locally it works for me now. Just have to wait for a maintainer to review the changes.

**Closed** 2022-08-17 11:26 UTC
Labels: bug

**Comment by gautamdsheth** [comment] 2022-08-17 11:29
Hello all, the issue has been fixed by @milanholemans !
It will be available from tomorrow's nightly and the next major version.

Thank you for raising the issue and thanks Milan for providing the fix.

**Comment by damienvanrobaeys** [comment] 2022-08-27 12:09
Hello, 
Nice new
Any date for the new release including the fix ?

**Comment by milanholemans** [comment] 2022-08-27 13:48
> Hello, 
> Nice new
> Any date for the new release including the fix ?

Hi @damienvanrobaeys 

Hard to say when the next major release will be. If I check the release history, there are 3 months on average between every release. Last release was ublished on July 1st.

This fix is already live in the beta version of PnP.PowerShell.
To install this, run the following command:
```powershell
Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber
```

**Comment by JeffreyvanEijk** [comment] 2022-08-30 12:35
> ```powershell
> Install-Module -Name PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -AllowClobber
> ```

I have installed the beta. Unfortunately is received below error when using Remove-PnPFile

Remove-PnPFile : Parameter set cannot be resolved using the specified named parameters.

**Comment by milanholemans** [comment] 2022-08-30 12:38
Hi @JeffreyvanEijk 

Could you verify that you are indeed using the latest beta release? This can be done by running following command:
```powershell
Get-InstalledModule -Name PnP.PowerShell
```

**Comment by JeffreyvanEijk** [comment] 2022-08-30 12:51
![image](https://user-images.githubusercontent.com/38246077/187441234-5f56a16b-4992-4241-af72-db1557275dfc.png)

**Comment by milanholemans** [comment] 2022-08-30 14:47
Hi @JeffreyvanEijk 

Strangely enough your version does not end on `-nightly`. When I install the nightly release, it looks like this:

![image](https://user-images.githubusercontent.com/11723921/187467099-f9405d83-4fe5-40ea-9a37-28d9fe42e6b8.png)

What I usually do is completely uninstall the alpha release to prevent unexpected behavior and install the nightly release as follows:
```powershell
Uninstall-Module -Name PnP.PowerShell
Install-Module -Name PnP.PowerShell -AllowClobber -AllowPrerelease -SkipPublisherCheck
```

After doing this, it works fine for me.

![image](https://user-images.githubusercontent.com/11723921/187466914-c0e02778-7ae1-4bde-b08d-896a887bbb70.png)

**Comment by joshtransient** [comment] 2022-10-05 12:49
Another workaround option, since @Cadder's workaround did not capture .ListItemAllFields for me:
````
$deleteMe = Get-PnPFile -Url 'Shared Documents/path/to/delete-me.docx' -AsListItem
Remove-PnPListItem -List Documents -Identity $deleteMe.Id   # Add -Force or -Recycle at your discretion
````

**Comment by Thomas-Drechsler** [comment] 2023-02-07 12:42
I am also got an error while using Remove-PnPFile. I had to use SiteRelative Url and made a connection to the site before. Script:
 
Remove-PnPFile -Connection $Connection -SiteRelativeUrl $SourcePath -Recycle

i get the following error: 

Remove-PnPFile : serverRelativePath
Parameter name: Der angegebene Wert wird für den serverRelativePath-Parameter nicht unterstützt.
At C:\Users\sharegate04\Documents\Archiving\PnPOnlyScript.ps1:14 char:3
+   Remove-PnPFile -Connection $Connection -SiteRelativeUrl $SourcePath ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPFile], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.RemoveFile

i am using PnP.PowerShell 1.12.0

**Comment by milanholemans** [comment] 2023-02-07 13:31
I don't think this error is related to this issue, but quick check, are you specifying a decoded URL?

**Comment by Thomas-Drechsler** [comment] 2023-02-07 13:47
no is not encoded. But the problem i would address is that i use a **Site**RelativeUrl and the Error states that the value cannot be used for the **server**RelativePath parameter. this makes no sense in my opinion. Do i miss something?

**Comment by milanholemans** [comment] 2023-02-07 13:58
> no is not encoded. But the problem i would address is that i use a **Site**RelativeUrl and the Error states that the value cannot be used for the **server**RelativePath parameter. this makes no sense in my opinion. Do i miss something?

This is because in the code, `SiteRelativeUrl` is being translated to `ServerRelativeUrl`. I just tested it and it seems to be working for me:

```powershell
Remove-PnPFile -SiteRelativeUrl "/TestLib/Sample-copy.pdf" -Recycle -Force
```

**Comment by Thomas-Drechsler** [comment] 2023-02-07 14:30
which version of pnp powershell you have used?
i tested some different things but i got this error The url is correct encoded, an the statement is the same as yours...
The error states that the Path is wrong and not the url. is this only a typo?

**Comment by milanholemans** [comment] 2023-02-09 14:18
> Freigegebene%20Dokumente%2fFolderA%2fFolderB%2fFilename.pptx

Hi @Thomas-Drechsler, I think this is indeed the issue. The path you are providing is an URL encoded string which is not supported (anymore).
If you provide `-SiteRelativeUrl "Freigegebene Dokumente/FolderA/FolderB/Filename.pptx"`, this should work.

**Comment by Thomas-Drechsler** [comment] 2023-02-09 15:21
i tested various combinations but it does not work.
i have check the following:
- connection
- permissions
- decoded input string (site relative url)
- Remove-PnPFile -SiteRelativeUrl $SourcePath -> Error " Parameter set cannot be resolved using the specified named parameters."
-  Remove-PnPFile -SiteRelativeUrl $SourcePath -Recycle -> Error "Remove-PnPFile : serverRelativePath
Parameter name: Der angegebene Wert wird für den serverRelativePath-Parameter nicht unterstützt."
- Remove-PnPFile -ServerRelativeUrl $SourcePath -> Error "Remove-PnPFile : Parameter set cannot be resolved using the specified named parameters."

**Comment by Thomas-Drechsler** [comment] 2023-02-09 15:48
i reduced my script to the essential part:
$Connection = Connect-PnPOnline -Url "https://tenantname.sharepoint.com" -Tenant tenantname.onmicrosoft.com -Interactive
$SourcePath = "Freigegebene Dokumente/test.docx"
Remove-PnPFile -SiteRelativeUrl $SourcePath -Recycle -Force

Error-> Remove-PnPFile : serverRelativePath
Parameter name: Der angegebene Wert wird für den serverRelativePath-Parameter nicht unterstützt.
At line:1 char:1
+ Remove-PnPFile -SiteRelativeUrl $SourcePath -Recycle -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Remove-PnPFile], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.RemoveFile

**Comment by JazBInKC** [comment] 2023-02-09 16:56
Thomas –

I’ve a script (moves data from ODB to a SharePoint Archive) where I delete the files after copy.  I’m using

PS C:\scripts> get-command Remove-pnpfile

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Remove-PnPFile                                     1.12.32    PnP.PowerShell

And I’m not having the issue that you’re experiencing – I too had problems with earlier interim version.

Regards,

jbw

***@***.***<https://ihs911.com/>
***@***.***<https://twitter.com/IHS911marketing>
***@***.***<https://www.facebook.com/IHS911/>
***@***.***<https://www.linkedin.com/company/ihs911>
James Wood​​​​
Support Services ‑ Solution Specialist
t: (913) 945-4711<tel:(913)%20945-4711>
f: (913) 945-4711<fax:(913)%20945-4711>
e: ***@***.******@***.***>
 |
w: www.ihs911.com<https://ihs911.com/>
a:
7520 W. 160th St. Suite 101
,
Overland Park
,
KS
66085

**Comment by Thomas-Drechsler** [comment] 2023-02-09 17:06
I will check this. Thanks for the hint

**Comment by milanholemans** [comment] 2023-02-09 17:20
It's probably not recommended to do, but sometimes if things are screwed, I just remove the folder from `C:\Users\<username>\Documents\PowerShell\Modules\PnP.PowerShell`

**Comment by Thomas-Drechsler** [comment] 2023-02-09 17:36
it works now!
i had remove the folder and reinstall the pnp.powershell module with scope to current user and now i have the right version of the command and it works well. Thanks to @milanholemans  and @JazBInKC !
