### ISSUE TITLE
[BUG] New-PnPSite: Object reference not set to an instance of an object when using Application ID

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#3278] opened 2023-07-18 02:26 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
New site created.

### Actual behavior 
New-PnPSite: Object reference not set to an instance of an object.
![image](https://github.com/pnp/powershell/assets/12259728/f4e9f1df-c516-4e27-a619-e230b43eb8db)

### Steps to reproduce behavior
New-PnPSite -Type TeamSite -Title "TITLE" -Alias "ALIAS" -Owners @("USER@TENANT.onmicrosoft.com") -Wait -Verbose -debug -ErrorAction Stop -Connection $connection # Where connection is a connection using an application ID

**PLEASE NOTE: That I can create sites successfully with v1.12 hence the Graph API permission is correct.**

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2023-07-18 08:33
Closing it as duplicate of https://github.com/pnp/powershell/issues/3273 , will track it there

**Closed by gautamdsheth** 2023-07-18 08:33 UTC
Labels: bug
