### ISSUE TITLE
[BUG] Context after Get-PNPList is not the same

### ISSUE THREAD

**Issue by SPDEVGUY** [pnp/powershell#3702] opened 2024-01-22 19:04 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
context remains the same.

### Actual behavior 
Context is changed to last used connect-pnponline

### Steps to reproduce behavior
```


function test-failure {
$adminAccountLabel = "AdminAccount"

$siteA = "https://tenant.sharepoint.com/sites/sitecollection/subsite"
$siteB = "https://tenant.sharepoint.com/sites/sitecollection"

connect-pnponline -url $siteA -Credentials $adminAccountLabel
$siteAContext = get-pnpcontext
"Site A Context: $($siteAContext.Url)"

connect-pnponline -url $siteB -Credentials $adminAccountLabel
$siteBContext = get-pnpcontext
"Site B Context: $($siteBContext.Url)"

Set-PNPContext -Context $siteAContext #revert to siteAContext

#context should be SITE A
"Pre-Call Ctx: $((get-pnpcontext).url)"

$lib = get-pnplist "Documents"

#context should be SITE A, but it is now SITE B
"Post-Call Ctx: $((get-pnpcontext).url)"
}

test-failure

```

output:
PS D:\> test-failure
Site A Context: https://tenant.sharepoint.com/sites/sitecollection/subsite
Site B Context: https://tenant.sharepoint.com/sites/sitecollection
Pre-Call Ctx: https://tenant.sharepoint.com/sites/sitecollection/subsite
Post-Call Ctx: https://tenant.sharepoint.com/sites/sitecollection

### What is the version of the Cmdlet module you are running?

2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by SPDEVGUY** [comment] 2024-01-23 18:36
https://github.com/pnp/powershell/blob/dev/src/Commands/Base/PnPWebRetrievalsCmdlet.cs

EndProcessing method returns context back to the last connection.

Would it not make sense to leave returning to context in the user's hand?  Do I have to call set context by design every time I want to use any command on a sub-site or use the much longer process intensive connect pnp for each subsite?

**Comment by gautamdsheth** [comment] 2024-01-28 16:16
Closing as duplicate of https://github.com/pnp/powershell/issues/2150 .

The recommended way is to reuse connection as mentioned below:

$siteConn1 = Connect-PnPOnline -Url "https://mytenant.sharepoint.com/sites/someSite1" -ReturnConnection
$web1 = Get-PnPWeb -Connection $siteConn1

$siteConn2 = Connect-PnPOnline -Url "https://mytenant.sharepoint.com/sites/someSite2" -ReturnConnection
$web2 = Get-PnPWeb -Connection $siteConn2

**Closed by gautamdsheth** 2024-01-28 16:16 UTC
Labels: bug
