### ISSUE TITLE
[BUG] PnP and Azure functions assembly conflict. Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope' from assembly 'Microsoft.Extensions.Logging.Abstractions'

### ISSUE THREAD

**Issue by jmartncp** [pnp/powershell#2136] opened 2022-07-13 01:56 UTC
### Reporting an Issue or Missing Feature
This is an issue related to PnP using a conflicting assembly dependency than what
the Azure functions service loads by default. To be more specific, the issue occurs for us
with the module ```Microsoft.Extensions.Logging.Abstractions``` on each call of
```Connect-PnPOnline```. PowerShell 7.2 on Azure functions automatically loads
version ```3.0.3.0``` while the one included with PnP is ```2.2.0.0```. I have tried many
potential resolutions but have been unable to fix (Wrapping in ThreadJob does not work).
The one solution about downgrading from 7.2 to 7.0 is not an option for us, as we require
7.2 for its functionalities. Due to this issue, we are unable to rely on PnP for our needs at
the moment. If a fix for PnP in this scenario is possible, please do. If not, then notify of any
possible workarounds. This problem had me stumped for a while, so anything that can be
done about it is appreciated.

### Expected behavior 
Successful connection via ```Connect-PnPOnline``` cmdlet.

### Actual behavior 
An error related to a module in Azure functions:
![Screenshot 2022-07-05 094943](https://user-images.githubusercontent.com/102254299/178629618-10a78b28-8a93-45a5-b563-c38b189d7e87.png)

### Steps to reproduce behavior
* Create an Azure functions app version 4.0 and set it to use PowerShell 7.2
* Add PnP.PowerShell 1.10.0 to the requirements.psd1 file.
* Create a basic function that just tries to execute ```Connect-PnPOnline```. Ensure it logs error info.
* Deploy the function to the cloud and execute via your API. (<app_url>/api/<func_name>)
* Wait a bit for logs to save, then go to monitor log menu for that function.
* View its logs and observe error.

NOTE: To reproduce, ensure code is run in the cloud within an Azure function. Running ```Connect-PnPOnline```
           locally will likely NOT cause an error. (The Azure assemblies won't be loaded)

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.10.0, PowerShell Core 7.2

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Linux
- [ ] MacOS
- [ ] Windows
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment] 2022-08-08 14:41
@jmartncp bit of a shot in the dark but have you tried upgrading to PnP.PowerShell v1.11?

**Comment by jmartncp** [comment] 2022-08-09 01:25
> @jmartncp bit of a shot in the dark but have you tried upgrading to PnP.PowerShell v1.11?

Yes I have. I actually tried both upgrading and downgrading. Neither made much of a difference though.

**Comment by CallumCrowley** [comment] 2022-08-09 07:14
I'm pretty sure I encountered the exact same issue after I erroneously created a new function app on PS Core 7.2, I downgraded it to 7.0 and everything was fine then (though I know this information isn't helpful).

@veronicageek are there any plans for PnP PS where it will support this scenario?

**Comment by Rutger-Knijnenburg** [comment] 2022-08-09 12:13
I had the exact same issue. Downgrading the Function App to use PowerShell 7.0 instead of latest (7.2) fixed this for me!

**Comment by jmartncp** [comment] 2022-08-15 13:34
> I had the exact same issue. Downgrading the Function App to use PowerShell 7.0 instead of latest (7.2) fixed this for me!

As I mentioned, this wasn't an option due to security facilities only present in 7.2. I suppose if you had the option you could do that, though I am not sure if I would consider that a 'fix'. Thanks for your thoughts though.

**Comment by gautamdsheth** [comment] 2022-08-23 19:28
@jmartncp - can you try commenting out the Az modules from `requirements.psd1` files and then load PnP PowerShell ? I think there might be some conflict between these modules.

**Comment by jmartncp** [comment] 2022-08-24 13:04
> @jmartncp - can you try commenting out the Az modules from `requirements.psd1` files and then load PnP PowerShell ? I think there might be some conflict between these modules.

They were already commented out. I wasn't using them to begin with, I only had PnP as my single dependency. Azure functions still attempts to load particular modules, like the `Microsoft.Extensions.Logging` one you see in the screenshot.

**Comment by BaronSparky** [comment] 2022-09-09 13:23
I am seeing exactly the same behaviour and error with 7.2 and Azure functions. Downgrading to 7.0 fixes it for me also but would prefer not to have to.

**Comment by Micael-stack** [comment] 2022-09-15 23:59
omg!! They are deprecating P.S 7.0 in december and still we have this crap! All our azure functions will fail that is it?

**Comment by BaronSparky** [comment] 2022-09-16 07:29
They won't fail as such, but the platform will be unsupported going forward.

**Comment by CallumCrowley** [comment] 2022-09-16 14:13
This is certainly turning in to a bit of an issue. While you could continue running 7.0, some organisations will have policies regarding out of support software and may not allow you to continue using a solution which isn't fully supported. Does anyone know of a way to stipulate which version `Microsoft.Extensions.Logging.Abstractions` Azure Functions loads? (as a workaround)

**Comment by Micael-stack** [comment] 2022-09-16 16:52
So I fixed it... by rebuilding Pnp.Powershell and Pnp.Framework. Updated refs to all Microsoft.Extensions.* from 2.2.0 to 3.0.3.0 

PnP.Framework.csproj: 
![image](https://user-images.githubusercontent.com/52808567/190689237-b5e350c8-6010-4278-ab97-4478d46944ce.png)

PnP.PowerShell.csproj:
![image](https://user-images.githubusercontent.com/52808567/190689367-0f185731-37e8-4e21-abb2-0f445303b851.png)


I rebuilded a local module and uploaded it to my Azure function, so no more managed dependencies... referencing directly the module in scripts.

**Comment by Micael-stack** [comment] 2022-09-16 16:54
So it is concluding that Pnp.Powershell should upgrade microsoft.Extensions.* dependencies in project. There is no impacts moving from 2.2.0 to 3.0.3.0...

**Comment by CallumCrowley** [comment] 2022-09-16 17:01
@Micael-stack what testing have you done to conclude that there is no breaking changes in upgrading the extensions?

Of course, upgrading the extensions would solve this issue but doing this could inadvertently introduce other bugs relating to wherever these dependencies are used in the PnP solution.

**Comment by Micael-stack** [comment] 2022-09-16 17:09
Our module is used in multiple client services for site provisioning creation from teams to communication sites with full assets. I would not say that I am covering 100% cases but from my point with my dev Team it does the trick.

**Comment by BarasG** [comment] 2022-09-26 10:06
I am experiencing the same issue. Downgrading to PowerShell version 7.0 fixes the issue, but this can only be a temporary solution since we have to upgrade to 7.2 by December 3th 2022. Our customer won't allow out of support software running on their tenant.

**Comment by CallumCrowley** [comment] 2022-09-26 10:22
@BarasG yes, I raised this as a concern above. PnP.PowerShell is probably used in countless Azure Functions, surely this means every single one of them would be in an unsupportable state from Microsoft's viewpoint on December 3rd 2022.

**Comment by jebalert** [comment] 2022-09-26 18:38
Confirmed this was the fix for me as well.. downgrading to runtime 7.0.

**Comment by frompedro** [comment] 2022-09-29 07:28
Downgrading to PS 7.0 did it

**Comment by astenman** [comment] 2022-10-12 08:56
+1, Me too

**Comment by arjenbloemsma** [comment] 2022-10-12 20:09
I'm facing the same issue. Downgrading solves it for now, but please implement the real fix soon PnP team, so we all can benefit from PowerShell 7.2.

**Comment by StevenDerveaux-DnDCore** [comment] 2022-10-17 09:50
I'm also facing this issue but cannot downgrade to PowerShell 7.0 because I use the Powershell module 'AzureAD'. That module requires the use of TLS 1.2 or higher. So, upgrading from 7.0 to 7.2 solves the new TLS requirements for AzureAD but breaks the Connect-PnPOnline cmdlet... Really, really annoying since the fact that some production Azure Functions are just not working anymore...

**Comment by oufly** [comment] 2022-10-20 11:56
+1, the same for us

**Comment by StevenDerveaux-DnDCore** [comment] 2022-10-25 15:01
@gautamdsheth , do you have any idea if the pnp.powershell is adapted on this issue or when it will happen?
Thanks for your feedback!

**Comment by ekdegerman** [comment] 2022-10-25 16:06
We just ran into this same issue when trying to get our functions upgraded before the December 3rd deprecation of 7.0. It would really help to understand if/when we can expect a fix to be released.

**Comment by brandilton** [comment] 2022-10-26 19:12
> So I fixed it... by rebuilding Pnp.Powershell and Pnp.Framework. Updated refs to all Microsoft.Extensions.* from 2.2.0 to 3.0.3.0
> 
> PnP.Framework.csproj: ![image](https://user-images.githubusercontent.com/52808567/190689237-b5e350c8-6010-4278-ab97-4478d46944ce.png)
> 
> PnP.PowerShell.csproj: ![image](https://user-images.githubusercontent.com/52808567/190689367-0f185731-37e8-4e21-abb2-0f445303b851.png)
> 
> I rebuilded a local module and uploaded it to my Azure function, so no more managed dependencies... referencing directly the module in scripts.

@Micael-stack - can you give a bit more detail on where I could find these files to modify and where they would need to be uploaded?  I'm somewhat familar with Kudu for doing this type of thing, but am not seeing PnP.PowerShell.csproj or PnP.Framework.csproj anywhere.

**Comment by wrongecho** [comment] 2022-10-27 16:03
Running into this error as well. Downgrading to 7.0 is a workaround but definitely not a resolution as support is being depreciated.

**Comment by gautamdsheth** [comment] 2022-10-27 20:02
Hello all on this thread, we are looking into fixing this for Azure functions.
Is more complex than we initially thought.
It is surely at the top of our minds and a priority issue for us. Will try to fix it asap but can't provide an ETA at this point.

**Comment by svermaak** [comment] 2022-11-09 01:46
> > So I fixed it... by rebuilding Pnp.Powershell and Pnp.Framework. Updated refs to all Microsoft.Extensions.* from 2.2.0 to 3.0.3.0
> > PnP.Framework.csproj: ![image](https://user-images.githubusercontent.com/52808567/190689237-b5e350c8-6010-4278-ab97-4478d46944ce.png)
> > PnP.PowerShell.csproj: ![image](https://user-images.githubusercontent.com/52808567/190689367-0f185731-37e8-4e21-abb2-0f445303b851.png)
> > I rebuilded a local module and uploaded it to my Azure function, so no more managed dependencies... referencing directly the module in scripts.
> 
> @Micael-stack - can you give a bit more detail on where I could find these files to modify and where they would need to be uploaded? I'm somewhat familar with Kudu for doing this type of thing, but am not seeing PnP.PowerShell.csproj or PnP.Framework.csproj anywhere.

@Micael-stack Do you mind sharing project and binaries?

**Comment by thunderstorm654** [comment] 2022-11-10 22:58
+1 to needing a solution for this. Our clients will not allow use of unsupported versions in prod so we're under pressure to resolve this ASAP before December and can't stay on 7.0. Heavy usage of PnP PowerShell so rebuilding not an ideal scenario. Any more details on whether @Micael-stack's approach is at all plausible?

**Comment by Micael-stack** [comment] 2022-11-11 00:31
Hi, I have created a pull request. I did a fork too, if it isnt approved so here it is : 

https://github.com/Micael-stack/powershell/tree/fix/support-powershell7.2-azure-function

Instructions to get your own files : 

1. Clone the git branch mentionned here
2. Run the powershell script in ".\Build\Build-Debug.ps1"
   `. .\Build\Build-Debug.ps1`
3. At the end of the script, there should be a module folder in your Documents/Powershell/Modules/Pnp.Powershell
4. Zip it, and upload it to your azure function, if not in git push setup ( I use the powershell tool in azure portal and upload the zip here :
![image](https://user-images.githubusercontent.com/52808567/201234193-78db8d58-8b9f-4afb-b149-972aa13ff201.png)

5. Reference the powershell module in your code like this : `Import-Module .\Pnp.PowerShell\PnP.PowerShell.psd1`

That's it, you should be running with no problems!
- You cannot use anymore PNP.Powershell managed dependencies like this. Remove it if you do from requirements.psd1

Thanks!

**Comment by KoenZomers** [comment] 2022-11-11 13:55
Thanks @Micael-stack for your efforts. We're currently working with the Product Group to see how this can be addressed on the Azure Function side. Lowering our version references is not sustainable in the long run as the .NET versions should be aligned for optimal performance and stability. The PG is currently looking at how they can change Azure Functions to fix this on their side.

**Comment by Micael-stack** [comment] 2022-11-11 14:54
@KoenZomers That is why my pull request, to raise Pnp.PowerShell to use newer package versions to be compatible with Azure function, that is at a later version with packages.

**Comment by KoenZomers** [comment] 2022-11-11 15:02
I see. Thanks for elaborating. For the current version that might work, but we're aiming to go for .NET 6 support in the next version and there this would not be an option. I'll discuss it in our team if we could apply your suggestion in the meantime.

**Comment by Micael-stack** [comment] 2022-11-11 15:15
I did myself a version with PnP.Core and PnP.Framework locally built with .NET 6 and i did upgrade the packages (Microsoft.Extensions.Logging.Abstractions and others) to the 3.0.3.0, and did test PnP.PowerShell with a build .Net6 profil too and everything seemed working (building the projects, not going farther though...)!

**Comment by thunderstorm654** [comment] 2022-11-11 16:05
@KoenZomers if the solution proposed by @Micael-stack is suitable while you work with the PG and towards .NET 6 that would make a lot of us very happy!

**Comment by BeekvanV** [comment] 2022-11-21 15:09
We're experiencing this issue as well. seeing as PS7.2 will be deprecated in a week or so I hope this issue gets appropriate attention.

**Comment by KoenZomers** [comment] 2022-11-21 16:21
No worries @BeekvanV, we're working closely with the Product Group for a solution on this. We're currently testing a resolution for this internally. Thus far things are looking well. It will not be that your current Azure Functions will stop working on December 3rd. The permanent resolution for this will follow in January or February as things look like now.

**Comment by jukka76** [comment] 2022-11-30 08:10
Hi @KoenZomers! 

> It will not be that your current Azure Functions will stop working on December 3rd. 

Could you clarify? Does this mean that we can safely ignore the error message and continue using PS7.0 until resolution is available and we can safely switch to 7.2? In that case please update the date in deprecation message in Azure. Just making sure our prod environment does not stop working suddenly

**Comment by Henry-Sir** [comment] 2022-11-30 16:44
> Hi, I have created a pull request. I did a fork too, if it isnt approved so here it is :
> 
> https://github.com/Micael-stack/powershell/tree/fix/support-powershell7.2-azure-function
> 
> Instructions to get your own files :
> 
> 1. Clone the git branch mentionned here
> 2. Run the powershell script in ".\Build\Build-Debug.ps1"
>    `. .\Build\Build-Debug.ps1`
> 3. At the end of the script, there should be a module folder in your Documents/Powershell/Modules/Pnp.Powershell
> 4. Zip it, and upload it to your azure function, if not in git push setup ( I use the powershell tool in azure portal and upload the zip here :
>    ![image](https://user-images.githubusercontent.com/52808567/201234193-78db8d58-8b9f-4afb-b149-972aa13ff201.png)
> 5. Reference the powershell module in your code like this : `Import-Module .\Pnp.PowerShell\PnP.PowerShell.psd1`
> 
> That's it, you should be running with no problems!
> 
> * You cannot use anymore PNP.Powershell managed dependencies like this. Remove it if you do from requirements.psd1
> 
> Thanks!

@Micael-stack 
Is it possible to upload your build?
I have created a build according to your instructions, unfortunately it does not work (same error again).

@KoenZomers 
> It will not be that your current Azure Functions will stop working on December 3rd.

See jukka76 post. What does this mean for us?

**Comment by srnlekkala** [comment] 2022-12-01 08:22
pnp.powershell 1.7.0 is supporting with powershell 7.2 and higher versions giving the reported error.  until the fix comes to continue to support after 3rd Dec, we can use this solution. If the requirement is to use higher version of pnp.powershell then downgrading powershell version to 7.0 is the workaround.

**Comment by Henry-Sir** [comment] 2022-12-01 11:48
> pnp.powershell 1.7.0 is supporting with powershell 7.2 and higher versions giving the reported error. until the fix comes to continue to support after 3rd Dec, we can use this solution. If the requirement is to use higher version of pnp.powershell then downgrading powershell version to 7.0 is the workaround.

No, version 1.7.0 does not work either, see screnshot below.

I tested some more and the fix from @Micael-stack works. Only the login (Connection-PNPOnline) via **certficate** does not work. Via user/password, app ID / secret and acsses token works.


![2022-12-01 11_53_55-Logic Apps Designer - Microsoft Azure - Greenshot Editor](https://user-images.githubusercontent.com/75314095/205042598-30389191-595a-4181-92f5-331f496aa28d.png)

**Comment by KoenZomers** [comment] 2022-12-07 11:25
@Francisco-Gamino can you comment on the rollout of the updated Azure Functions in January and the situation between now and then with PowerShell 7.0 Azure Functions being deprecated?

**Comment by Micael-stack** [comment] 2022-12-07 14:30
@Henry-Sir Hi, sorry for the delay. Yep ok just testes with the fork I did, since Pnp.Powershell 1.12 my fix stopped working. Sorry for that. I will have to try another way but running out of time!

I will try to save up some time this week or the next to bend my head over it.

**Comment by Ofer-Gal** [comment] 2022-12-07 15:22
I have the same issue in Azure using 1.12.0 on a function that I could only use PowerShell 7.0 (no other option)
The error is on a statement:
`
$appConn = Connect-PnPOnline  -Url $appUrl  -Tenant $env:TenantId -ClientId $env:ClientId  -CertificateBase64Encoded $env:CertificatePFX -CertificatePassword $CertificatePassWord -ReturnConnection`
Should I downgrade to 1.10.0 or maybe less? 
Is there another fix?

**Comment by Francisco-Gamino** [comment] 2022-12-08 18:09
> @Francisco-Gamino can you comment on the rollout of the updated Azure Functions in January and the situation between now and then with PowerShell 7.0 Azure Functions being deprecated?

The `PowerShell 7.2` language worker with the fix will start rolling out January 3rd, and it is expected to complete in one or two weeks. In the meantime, we are committing to provide support for the apps that are on `PowerShell 7.0` until this deployment completes.

/cc @anirudhgarg @anatolib @MadhuraBharadwaj-MSFT @michaelpeng36 @VpOfEngineering

**Comment by Ofer-Gal** [comment] 2022-12-09 06:48
I set the PowerShell to 7.0 and it works now.
But I have a timeout issue. the plan is premium but I get a "Timeout value of 00:30:00 exceeded by function 'Functions.DailyMaintenance' " so paying more does not help?
I have SCM_LOGSTREAM_TIMEOUT set to 43200 seconds
Any ideas

**Comment by wrongecho** [comment] 2022-12-09 07:54
> I set the PowerShell to 7.0 and it works now.
> But I have a timeout issue. the plan is premium but I get a "Timeout value of 00:30:00 exceeded by function 'Functions.DailyMaintenance' " so paying more does not help?
> I have SCM_LOGSTREAM_TIMEOUT set to 43200 seconds
> Any ideas?

30 mins is default for premium. 

You need to adjust the functionTimeout parameter in host.json.

For premium functions the upper limit is technically unbounded, but Microsoft only guarantee 60 mins of continuous running (i.e it might be restarted after that time, so needs to handle that gracefully).

**Comment by Ofer-Gal** [comment] 2022-12-09 12:58
"functionTimeout": "10:00:00", is 10 hours?

**Comment by Micael-stack** [comment] 2022-12-09 14:15
@Ofer-Gal yes, so when you're in basic plan, the maximum is : 
`functionTimeout": "00:10:00"`
And for premium : 
`functionTimeout": "00:30:00"`

**Comment by SaadKnowIT** [comment] 2022-12-09 14:22
How do i force PowerShell version to 7.0 in an Azure function?

**Comment by Micael-stack** [comment] 2022-12-09 15:43
@SaadKnowIT You can't anymore from the interface, this is exacly what MS removed!

I don't know if by Powershell it still possible or by templating bicep.

**Comment by Francisco-Gamino** [comment] 2022-12-09 19:34
> > @Francisco-Gamino can you comment on the rollout of the updated Azure Functions in January and the situation between now and then with PowerShell 7.0 Azure Functions being deprecated?
> 
> The `PowerShell 7.2` language worker with the fix will start rolling out January 3rd, and it is expected to complete in one or two weeks. In the meantime, we are committing to provide support for the apps that are on `PowerShell 7.0` until this deployment completes.
> 
> /cc @anirudhgarg @AnatoliB @MadhuraBharadwaj-MSFT @michaelpeng36 @VpOfEngineering

To downgrade your function app from `PowerShell 7.2` to `PowerShell 7.0`, follow these steps:

Prerequisites: `Az.Functions` and `Az.Resources`, which can be downloaded from the PowerShell Gallery. 

``` powershell
$SubId = "<your sub id>"
$ResourceGroupName = "<your resource group name>"
$AppName = "your app name"

Set-AzContext -Subscription $Subscription | Out-Null

```
For a Windows function app
``` powershell
Set-AzResource -ResourceId "/subscriptions/$SubId/resourceGroups/$ResourceGroupName/providers/Microsoft.Web/sites/$AppName/config/web" -UsePatchSemantics -Properties @{ powerShellVersion = '~7' } -Force

# Restart your app for the version changes to take effect
Restart-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName -Force

# Verify that version was updated
$app = Get-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName 
$app.SiteConfig.PowerShellVersion

```

For a Linux function app 
``` powershell
Set-AzResource -ResourceId "/subscriptions/$SubId/resourceGroups/$ResourceGroupName/providers/Microsoft.Web/sites/$AppName/config/web" -UsePatchSemantics -Properties @{ linuxFxVersion = 'PowerShell|7' } -Force

# Restart your app for the version changes to take effect
Restart-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName -Force

# Verify that version was updated
$app = Get-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName 
$app.SiteConfig.LinuxFxVersion
```

If you have any questions on why `PowerShell 7.0` is `"~7"`, please see https://github.com/Azure/azure-functions-powershell-worker/issues/885

**Comment by gabbsmo** [comment] 2022-12-11 08:11
Please try to stay on topic. This error about the error in the title. Create new issues for other problems.

**Comment by TMVUpShare** [comment] 2022-12-11 08:14
> Please try to stay on topic. This error about the error in the title. Create new issues for other problems.

I'm getting the same error as in this thread 

2022-12-11T07:19:52Z   [Error]   ERROR: Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope

**Comment by Ofer-Gal** [comment] 2022-12-26 07:22
As of today, I can't select PowerShell 7.0 anymore and both 1.12.0 and 1.11.0 show the error
Could not load type 'Microsoft.Extensions.Logging.Abstractions.Internal.NullScope
Any solution in the future?

**Comment by gautamdsheth** [comment] 2022-12-26 21:33
@Ofer-Gal - Right now, you can create a PS 7.2 function app and downgrade to 7.0 using the script in the comments above [here](https://github.com/pnp/powershell/issues/2136#issuecomment-1344710434). You will be able to use PnP PS 1.11 and 1.12

After [mid-Jan](https://github.com/pnp/powershell/issues/2136#issuecomment-1343111706), when Microsoft's rollout of the fix is completed, you will be able to use PnP PowerShell in PS 7.2 function app. But then, you will need to use the PnP PowerShell nightly build's which are based on .NET 6.

**Comment by Ofer-Gal** [comment] 2022-12-27 08:22
Now it runs only with 1.12.0 but the statement: 
`Set-PnPListItem  -List $sitesList -Identity $item -Values @{ "LastMaintenance" = (Get-Date) ; } -Connection $appConn `
 Errors:
` EXCEPTION: The collection has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.`
same code runs fine on the desktop.
is there a another way to do the update ?

**Comment by myatix** [comment] 2023-01-03 15:06
I am also having an issue with my Azure Function... I have downgraded the Azure Function to .Net Core 7.0 and am using PnP.PowerShell v1.12.0 with Connect-PnPOnline and -CertificateBase64Encoded authentication to connect to a AzureKeyVault

I have numerous errors with thing like Get-PnPList which works fine on my local client connecting via -Interactive but not in the Function APP using -CertificateBase64Encoded? 
Super frustrating... Any suggestions would be appreciated on how to get around this?

**Comment by Francisco-Gamino** [comment] 2023-01-06 21:00
> > @Francisco-Gamino can you comment on the rollout of the updated Azure Functions in January and the situation between now and then with PowerShell 7.0 Azure Functions being deprecated?
> 
> The `PowerShell 7.2` language worker with the fix will start rolling out January 3rd, and it is expected to complete in one or two weeks. In the meantime, we are committing to provide support for the apps that are on `PowerShell 7.0` until this deployment completes.
> 
> /cc @anirudhgarg @AnatoliB @MadhuraBharadwaj-MSFT @michaelpeng36 @VpOfEngineering

The Functions release with the fix for the `PowerShell 7.2` language worker has been delayed. Currently, the release is set to start deploying on January 17th, 2023 and it is expected to be completed in one or two weeks if no blocking issues are found. I will continue to update this issue with the deployment status as more information becomes available. Thank you.

**Comment by gajcowan** [comment] 2023-01-11 11:27
Do we expect the fix to also be rolled out at the same time to Azure Function Core Tools as we get the same issue with 4.9.495 x64, which means it is not possible to test locally before deployment.

The DLL Hell, if I remove the "FUNCTIONS_WORKER_RUNTIME_VERSION" : "7.2" statement from my settings it works, the  MSGraph PowerShell modules no longer longer work due to a different DLL issue!!!!!

**Comment by Ofer-Gal** [comment] 2023-01-11 12:29
How were you able to delete the "FUNCTIONS_WORKER_RUNTIME_VERSION"? 
I only see it as a dropdown with 7.0 and 7.2 options.
Is there a file I can edit anywhere?

**Comment by myatix** [comment] 2023-01-11 13:58
> How were you able to delete the "FUNCTIONS_WORKER_RUNTIME_VERSION"? I only see it as a dropdown with 7.0 and 7.2 options. Is there a file I can edit anywhere?

@Ofer-Gal  What are you trying to achieve? To role back to version 7.0 you can use a PowerShell script.

```
# Configure App to use .Net Core 7.0
$SubId = "<SubScriptionID>"
$ResourceGroupName = "RGXXX"
$AppName = "func-AppName"
$TenantID = "TenantID"

Connect-AzAccount -Tenant $TenantID -SubscriptionId $SubId

Set-AzContext -Subscription $SubId | Out-Null

Set-AzResource -ResourceId "/subscriptions/$SubId/resourceGroups/$ResourceGroupName/providers/Microsoft.Web/sites/$AppName/config/web" -UsePatchSemantics -Properties @{ powerShellVersion = '~7' } -Force

# Restart your app for the version changes to take effect
Restart-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName -Force

# Verify that version was updated
$app = Get-AzFunctionApp -Name $AppName -ResourceGroupName $ResourceGroupName 
$app.SiteConfig.PowerShellVersion
```

Or you can see the FUNCTIONS_WORKER_RUNTIME_VERSION locally in VSCode in the local.settings.json file.
![image](https://user-images.githubusercontent.com/48433526/211824757-aa24ac1e-ee20-4f32-94f7-a8ebb43a3b7e.png)

**Comment by Ofer-Gal** [comment] 2023-01-11 15:55
I thought you removed it altogether.
I got it back to 7.0 with the script too.

**Comment by myatix** [comment] 2023-01-11 19:56
@Ofer-Gal  On your connection string have you remembered to add the parameter -returnconnection?

**Comment by Ofer-Gal** [comment] 2023-01-12 14:57
I did.

**Comment by sli701** [comment] 2023-01-12 22:50
As of 2023-01-12. the issue persists. And there is no option to go back to PowerShell 7.0.

**Comment by myatix** [comment] 2023-01-14 07:24
@sli701  You can use the powershell script above to rollback to powershell core 7.0 on your function spp.

**Comment by sli701** [comment] 2023-01-16 18:34
@myatix , was able to give a try on the Cloud Shell, it is able to rollback. not sure why it is not working when using Local Power Shell Command. However, it does work on the cloud shell, thanks for the help!

**Comment by gabbsmo** [comment] 2023-01-23 14:19
@Francisco-Gamino Has the fix for Azure Functions been released?  If yes, is it available in the West Europe region?

**Comment by Francisco-Gamino** [comment] 2023-01-23 18:55
> and it is expected to be completed in one or two weeks if no blocking issues are found.

The Functions version `14.15.1` deployment that was supposed to start on `1/17/23` has been delayed. However, the deployment started rolling out today `1/23/23`, and it is expected to be completed by the beginning of next week if no blocking issues are found.

/cc @anirudhgarg @AnatoliB @MadhuraBharadwaj-MSFT @michaelpeng36 @VpOfEngineering

**Comment by VpOfEngineering** [comment] 2023-01-24 20:25
Hi everyone, we're still facing delays in rolling out `4.15.1`. We will keep updates here as we fix the issues and continue the rollout. Thank you all for your patience.

**Comment by karthikramasubramanian** [comment] 2023-01-30 15:04
> Hi everyone, we're still facing delays in rolling out `4.15.1`. We will keep updates here as we fix the issues and continue the rollout. Thank you all for your patience.

Do we have any update on when we can expect the rollout of '4.15.1'

**Comment by VpOfEngineering** [comment] 2023-01-30 15:06
Barring any issues, we should be fully rolled out by the beginning of next week.

**Comment by Clam-** [comment] 2023-01-31 03:37
Will any action need to be taken? Will our currently failing Azure Functions start working again next week without interaction?
Thank you.

**Comment by svermaak** [comment] 2023-01-31 03:42
Will functions where a workaround was applied stop working?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Francisco-Gamino** [comment] 2023-01-31 19:29
The `PowerShell 7.2` language worker which is being deployed with `4.15.1` updates `Microsoft.Extensions.Logging.Abstractions` to version `6.0.3`. If the workaround was applied to the `PowerShell 7.0` language worker, then this should continue to work as no changes has been introduced to this version given that it has reached EOL.

@KoenZomers -- Could you please comment on next steps after `4.15.1` completes rolling out? Thank you.

**Comment by gautamdsheth** [comment] 2023-02-02 13:32
Just tested this in an environment which has version `4.15.x.x` , works perfectly fine !

To fix this issue in your environment, please wait till the fix is there.
Once the fix is available, you will need to update the PnP PowerShell to the latest nightly builds.

You need to explicitly specify the version number like `2.0.1-nightly` or later.
The code will keep working as it is.

Once a major release of PnP PowerShell is done, you can also specify it as a wildcard entry `2.x`

**Comment by thunderstorm654** [comment] 2023-02-02 14:45
It would be good to know when the next major release of PnP will be out that works with the Azure fix. Some clients don't like to use nightly versions in production :) thanks!

**Comment by Clam-** [comment] 2023-02-07 05:10
> Just tested this in an environment which has version `4.15.x.x`

How does one know if their environment is 4.15.x?

> You need to explicitly specify the version number like `2.0.1-nightly` or later.

How does one do this? 

Thank you.

**Comment by gautamdsheth** [comment] 2023-02-07 09:42
@Clam- 

It is in the Azure function overview page:

![image](https://user-images.githubusercontent.com/8832018/217207829-64c2701c-fb92-42dc-a7e7-fcf396e44d61.png)

You can specify the version of PnP PowerShell here:

`App Files > Requirements.psd1` file

![image](https://user-images.githubusercontent.com/8832018/217208392-67c0698c-a4b9-44ca-94ee-ed59d4ad0ded.png)

**Comment by gyadav-HBS** [comment] 2023-02-08 23:57
As a workaround, my Azure functions were working fine with PS 7.0. and PnP.PowerShell 1.2. To test the above fix I updated the functions to use PS 7.2 and switched PnP.PowerShell to 2.0.6-nightly. And I am seeing the following exception now when making a call to New-PnPWeb. Any thoughts??

ERROR: System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.. ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host. --- End of inner exception stack trace --- at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken) at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token) at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter) at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer) at System.Net.Http.HttpConnection.FillAsync(Boolean async)
.................................
.................................

**Comment by jrudley** [comment] 2023-02-09 02:16
If you are not running a consumption plan, but under an app service plan, I ran into a weird issue and found a workaround. I was on a B2 sku and kept getting the nullscope error. I was not downgrading my ps version due to other production functions running on the same app plan. Maybe Azure gov does not back patch existing hosts or not fully finished yet. To make it work, upgrade your plan to a PV2/V3 and it will move it to a new host which should have the patched runtime. I verified it worked, then moved it back to a B2 plan which was put on a host that was patched as well.

**Comment by desmay** [comment] 2023-02-10 15:44
@Francisco-Gamino  Do we know if 4.15.1 Azure function updates were pushed to Azure Gov ?

**Comment by gautamdsheth** [comment] 2023-02-16 09:09
Going to close this issue. It has been fixed from Microsoft side when using Az function 4.15.x or later version. To use PnP PowerShell, as we mentioned, please use the latest 2.x.x-nightly builds.

@desmay - no idea if this has been fixed for Azure Gov, but you can reach out to Microsoft support/PG for more information on this.

We have no ETA on the major release of PnP PowerShell as of now.

**Closed by gautamdsheth** 2023-02-16 09:09 UTC
Labels: bug, azure-automation

**Comment by karthikramasubramanian** [comment] 2023-05-18 14:20
Hi All,

I recently upgraded PnP.Powershell from the 2.x.x-nightly to 2.1.1 and can confirm that it is working fine.  I have deployed it to our prod tenant for almost a month now so far no errors or issues..

Regards

Karthik Ramasubramanian
Senior Digital Productivity Developer

Norton Rose Fulbright Canada LLP / S.E.N.C.R.L., s.r.l.
45 O'Connor Street, Suite 1500, Ottawa, ON K1P 1A4, Canada

T: +1 613.780.8674  |  M: +1 613.277.2840  |  F: +1 613.230.5459

***@***.******@***.***>
NORTON ROSE FULBRIGHT
