### ISSUE TITLE
[BUG] Getting error when use Add-PnPListItem with -Batch parameter

### ISSUE THREAD

**Issue by bva999** [pnp/powershell#1280] opened 2021-10-19 13:11 UTC
### Reporting an Issue or Missing Feature
Getting error when use Add-PnPListItem with -Batch parameter

### Steps to reproduce behavior
````
$batch = New-PnPBatch
Add-PnPListItem -List "Projects" -ContentType "Projects" -Values @{"Title" = "Project 13"; "ProjectName" = "Project Name 13"; "FinanceCode" = "Project Finance Code 13"; "EndDate1" = "05/06/2018 01:01"; "StartDate" = "05/06/2017 01:01" } -Batch $batch
Invoke-PnPBatch -Batch $batch
````

Error: 
Add-PnPListItem : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'.
At line:2 char:1
+ Add-PnPListItem -List "Projects" -ContentType "Projects" -Values @{"T ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Add-PnPListItem], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.AddListItem

But it works without -Batch 

### What is the version of the Cmdlet module you are running?
ModuleType  Version    Name                             
----------       -------      ----                                
Manifest        1.8.0        PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [ x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2021-10-30 21:25
@bva999 - unable to reproduce this issue in my local environment. 

OS - Win 10 with PS5.1

Not sure , could be something in your specific environment. 

Going to close this issue as a workaround exists for your case. Could you please try it in a different machine or VM ?

**Closed by gautamdsheth** 2021-10-30 21:25 UTC
Labels: bug, batch issue

**Comment by jackpoz** [comment] 2021-10-30 21:55
Is that method even present for .NET Framework ? To me it looks like some .NET Core specific code that is being referenced in the .NET Framework build (or .NET Standard one as that's what pnp uses)
