### ISSUE TITLE
[BUG] Get-PnPSitePolicy returns empty on recent sites while synced Site policy is visible in UI

### ISSUE THREAD

**Issue by Sheppounet** [pnp/powershell#2237] opened 2022-08-08 13:36 UTC
### Reporting an Issue or Missing Feature
I reuse the #1645 as i haven't see it well formatted and encounter same behaviour currently.

On recently created sites (less than few hours), when we execute `Get-PnPSitePolicy`, site policies synced from the contenttypehub are not retrieved. At the same time we do see the site policies in the SharePoint UI. Also from the UI the policy can be applied successfully.

We also see that the hidden contenttype which used to be created once the sync was done, is also not available.

We see the same behaviour on multiple tenants.
On older sites the policy is retrieved without any problem.

### Expected behavior 
It would be nice if we can apply site policies immediatly after site creation, without having to wait many hours the contenttypehub sync, as we can do it directly from the UI.

### Actual behavior 
On fresh created sites, the `Get-PnPSitePolicy -AllAvailable` give no results. The `Set-PnPSitePolicy` doesn't seem to aply anything too. We must wait few hour the automatic sync to do it.

We can apply the policy immediatly only from the UI, wich shows available policies immediatly.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

1. Create some Site Policies on ContentType Hub, Publish them & wait few hour at least.
2. Create a new site
3. Enable Site Policy Feature (`Enable-PnPFeature -Identity "2fcd5f8a-26b7-4a6a-9755-918566dba90a" -Scope Site`)
4. Try getting all available policies with cmd `Get-PnPSitePolicy -AllAvailable`

You get nothing as a result. No error, no result. Just nothing. At the same time, when getting on the UI `(/_layouts/15/ProjectPolicyAndLifecycle.aspx),` you can see the available Site Policies from the contenttypehub.

5. Few hour later, try again the cmd. This time, policies are available as the cmd result too.

### What is the version of the Cmdlet module you are running?
PnP.Powershell v1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

### Screenshots
List of available policies from the UI
![2022-08-08 15_27_53-Window](https://user-images.githubusercontent.com/7957821/183429301-7c65e57d-ad55-4dbe-b333-714024922798.jpg)

Results of cmdlets
![2022-08-08 15_30_03-Window](https://user-images.githubusercontent.com/7957821/183429775-3f262ef8-b838-4623-ab28-d7c8375943e2.jpg)

**Comment by gautamdsheth** [comment] 2022-09-16 21:09
Hi, looks like this is working as designed unfortunately.

As you mentioned, here , `Few hour later, try again the cmd. This time, policies are available as the cmd result too.`, this is how the server is responding. 

We use the standard CSOM SDK and API to retrieve the policy. If the server itself, doesnt provide us the immediate results , we can't do anything unfortunately from the client side. So, you will just have to wait till you get the results back from the server before you can apply the policies.

Will have to close this as it is not a bug, but a SharePoint design issue which we can't fix.

**Closed by gautamdsheth** 2022-09-16 21:09 UTC
Labels: bug

**Comment by Sheppounet** [comment] 2022-09-17 15:00
Sad :( Thanks for your feedback.

**Comment by tico1177** [comment] 2022-11-20 04:19
FYI... I have been attempting the usage of this as well.  I have given 24 hours and the policies don't seem to be coming up.  I also went into using the CSOM and it seems like it is not working there either...  You can see the comments at the below link from just in October.

[](https://www.sharepointdiary.com/2019/08/sharepoint-online-apply-site-policy-using-powershell.html)
