### ISSUE TITLE
[BUG] Export-PnPFlow - Not exporting all flows

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#865] opened 2021-06-28 18:21 UTC
### Reporting an Issue or Missing Feature
Export-PnPFlow is not exporting all flows accurately. 

### Expected behavior 
I should be able to get all flows from an environment, loop over them, and export them all out. 

### Actual behavior 
When I loop over the list of 42 flows only 13 export out. There are also no failures reported using try catch.  See issue [#617](https://github.com/pnp/powershell/issues/617) which might be related.

### Steps to reproduce behavior
$allFlows = Get-AdminFlow -EnvironmentName $globals.defaultEnvGUID
$allFlows.Count

foreach($flow in $allFlows) {
    $flow
    $flowID = $flow.FlowName
    try {
        Export-PnPFlow -Environment $globals.defaultEnvGUID -Identity $flowID -PackageDisplayName "ExportFlow" -AsZipPackage -OutPath "$flowID.zip" -Force
    }
    catch {
        Write-Host "Error"
    }
}

![123667220-90266600-d7ff-11eb-99c4-e8dc365524b8](https://user-images.githubusercontent.com/1613085/123684652-595a4b00-d813-11eb-9eb2-4784e397c83d.png)

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by KoenZomers** [comment] 2021-09-24 00:29
@robertcaretta  can you try this one again with the latest prerelease build since https://github.com/pnp/powershell/issues/617 has been resolved? Likely that fixes this one as well.

**Comment by veronicageek** [comment] 2021-09-28 18:09
Closing as issue is fixed.

**Comment by robertcaretta** [comment] 2021-09-28 18:26
Please re-open the ticket. This is not working for me.  I am using the latest nightly preview release, and explicitly importing it.
![2021-09-28_13-16-11](https://user-images.githubusercontent.com/1613085/135144187-f76e924c-5556-4d11-b72c-9b7761ba6f8c.png)

My code is pulling in the total number of files correctly now via the fix implemented with Get-PnPFlow, however it is hit and miss on the exports. There are a total of 74 flows, but only 24 export.  It doesn't throw an error. It just passes right over them. I've run this multiple times, and tried "foreach" and "ForEach-Object".   I also tried the -Parallel switch and the Export-PnPFlow just errors out when using that.

![2021-09-28_13-10-39](https://user-images.githubusercontent.com/1613085/135144576-5c7cd327-7af3-4f23-b945-671be2948f46.png)

![2021-09-28_13-13-56](https://user-images.githubusercontent.com/1613085/135144587-d2db851e-d6a1-486d-bce3-664448f25d26.png)

**Comment by KoenZomers** [comment] 2021-09-28 22:14
Looking into it

**Comment by KoenZomers** [comment] 2021-09-29 00:06
I can reproduce this issue. It basically means that some of your Flows cannot be exported due to various reasons such as them not having valid connections or containing actions that are not configured properly. I'm trying to see how I can make these details insightful.

**Comment by KoenZomers** [comment] 2021-09-29 00:28
Created it now that in verbose it writes the errors that may occur during the exports. I.e.

![image](https://user-images.githubusercontent.com/5940670/135182576-2e4324b2-331b-4370-ada0-f9c5b532cf31.png)

![image](https://user-images.githubusercontent.com/5940670/135182538-4d0bde23-18ac-49c2-9fb6-5eba6f98d36e.png)

![image](https://user-images.githubusercontent.com/5940670/135182546-cd83e9c9-d8a4-4a52-b97c-9effe0a239f9.png)

PR referenced above has been submitted to provide this insight. Wait for it to be merged. Then the day thereafter you can get the latest prerelease to try this out. Remember to include the -Verbose flag with your Export-PnPFlow to get these details. 

Closing this issue again assuming this will resolve it. Feel free to reopen if it doesn't work for you.

**Comment by robertcaretta** [comment] 2021-10-01 16:35
@KoenZomers - Tried PR 1.7.65 with the -Verbose flag and it's not working for me. Ensured only version installed is the latest PR, and I am explicitly importing that version. Tried the exact same format of the code, just like your example. Also tried restarting VS Code.  Only see the 24 exports, the others are invisible.

![2021-10-01_11-18-34](https://user-images.githubusercontent.com/1613085/135656142-bd723ab4-a427-417f-af9b-899ae16efcef.png)

![2021-10-01_11-32-13](https://user-images.githubusercontent.com/1613085/135656160-a990931b-1b69-4960-8f1f-411835d36b39.png)

**Comment by KoenZomers** [comment] 2021-10-03 10:00
Interesting one. Are you familiar with Fiddler and willing to privately share a trace from that while you run the cmdlet so I can see what is going on in your scenario? Do not post it here.

**Comment by robertcaretta** [comment] 2021-10-04 14:08
I upgraded to 1.7.68 and it's working now.  I do have Fiddler installed if we need to run that.
![2021-10-04_8-57-58](https://user-images.githubusercontent.com/1613085/135866164-8810dec4-b786-466a-9227-1292a0accd90.png)

**Comment by robertcaretta** [comment] 2021-10-04 14:37
Yes, my concern is addressed now. That extra verbose information is
helpful. Thank you!

**Comment by KoenZomers** [comment] 2021-10-04 14:40
Awesome, you're welcome. Going to close this issue again then.

**Closed by KoenZomers** 2021-10-04 14:40 UTC
Labels: bug, reproduced
