### ISSUE TITLE
PnPContext has overwritten after excute Get-PnPHubSite

### ISSUE THREAD

**Issue by mohammadamer** [pnp/powershell#1089] opened 2021-09-09 17:10 UTC
### Expected behavior 
The expected behavior here is to execute Get-PnPWeb using the first Context that we set but it turned out that Get-PnPWeb executed by the second Context.

### Actual behavior 
The actual behavior that has happened is Get-PnPWeb executed by the second Context.

### Steps to reproduce behavior
```
$site = "https://tenant.sharepoint.com/sites/xyz"
#First App
$client1 = "00000000-0000-0000-00000000"
$cert1 = "C:/Cert1.pfx"
$certPass1 = (ConvertTo-SecureString -String "Password1" -AsPlainText -Force)

#Second App
$client2 = "00000000-0000-0000-00000000"
$cert2 = "C:/Cert2.pfx"
$certPass2 = (ConvertTo-SecureString -String "Password2" -AsPlainText -Force)

#First Connection
Connect-PnPOnline  -Url $site -ClientId $client1 -CertificatePath $cert1 -CertificatePassword $certPass1 -Tenant "tenant.onmicrosoft.com"
$ctx1 = Get-PnPContext

#Second Connection
Connect-PnPOnline  -Url $site -ClientId $client2 -CertificatePath $cert2 -CertificatePassword $certPass2 -Tenant "tenant.onmicrosoft.com"
$ctx2 = Get-PnPContext

Set-PnPContext -Context $ctx1
Get-PnPHubSite -Identity $site

#After execute Get-PnPHubSite it turns out Context has overwritten and changed to the second Context
Get-PnPWeb
```

### What is the version of the Cmdlet module you are running?
It has been reproduced in 
1.7.0
nightly build

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

**Comment by veronicageek** [comment] 2021-09-19 18:02
Issue #1091 is similar with `Set-PnPContext`

**Comment by chuushi** [comment] 2021-11-17 19:40
I am having the same issue with `Get-PnPList`. Even the commands listed in the [official documentation](https://github.com/pnp/powershell/blob/17b61bede59fbe3e6acd5bac4b86e88f89dc1d91/documentation/Set-PnPContext.md) is not working properly between admin context and normal site

```pwsh
Connect-PnPOnline -Url https://tenant.sharepoint.com/sites/TestSite -Interactive
$ctx = Get-PnPContext
Get-PnPList # returns the lists from site specified with $siteAurl
Connect-PnPOnline -Url https://tenant-admin.sharepoint.com -Interactive
Get-PnPList # returns the lists from the admin site
Set-PnPContext -Context $ctx # switch back to site A
Get-PnPList # should return the lists from TestSite, but returns the lists from the admin site instead?!
```

PnP v1.8.0

There should ideally be a definitive way to set the context just by specifying the URL. I haven't been having a straightforward experience in tinkering with `Connect-PnPOnline` in code every time I have to flop between SP sites because a login screen occasionally comes up. There's no `Set-PnPConnection` or similar, and that makes things a bit harder.

**Comment by KoenZomers** [comment] 2022-02-08 14:45
I can reproduce the issue and have fixed it. Thanks for reporting it. Will be fixed in the latest PreRelease the day after this PR has been merged https://github.com/pnp/powershell/pull/1611.

**Closed** 2022-02-08 15:09 UTC
Labels: bug, reproduced
