### ISSUE TITLE
Unable to set context from connection

### ISSUE THREAD

**Issue by svermaak** [pnp/powershell#3311] opened 2023-07-31 02:11 UTC
### Reporting an Issue or Missing Feature
Unable to set context from connection obtained with certificate.

### Expected behavior 
Context successfully set

### Actual behavior 
![image](https://github.com/pnp/powershell/assets/12259728/cef87ee5-27da-4830-a4d7-a0065982321d)

### Steps to reproduce behavior
Get a $connection with a cert then
`Set-PnPContext -Connection $connection -Context $connection.Context
Get-PnPContext`

### What is the version of the Cmdlet module you are running?
2.2.30

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [x] Azure Functions
- [ ] Other : please specify

**Comment by svermaak** [comment] 2023-07-31 02:41
Doesn't work with interactive authentication either

![image](https://github.com/pnp/powershell/assets/12259728/7d57102b-445a-4870-a455-7c5858294eb3)

**Comment by gautamdsheth** [comment] 2023-07-31 10:07
closing as duplicate of https://github.com/pnp/powershell/issues/2150

**Closed by gautamdsheth** 2023-07-31 10:07 UTC
Labels: bug
