### ISSUE TITLE
[BUG] - Newly added Navigation node doesn't appear in the global navigation menu (in a hub site)

### ISSUE THREAD

**Issue by PARR55** [pnp/powershell#1881] opened 2022-05-20 05:03 UTC
**The issue:**
I am using Add-PnPNavigationNode to add a link to a Hub site global navigation and I am also setting audience targeting on the navigation node. 
The navigation node is correctly added and targeted to the correct group. The issue is the navigation node doesn't automatically appear in the top navigation bar unless an admin clicks on the Edit button even without making any changes to the navigation (clicked cancel and leave). 

$hubConnection = Connect-PnPOnline -Url $hubSiteUrl -Interactive
Add-PnPNavigationNode -Title $siteTitle -Url $siteUrl -Location TopNavigationBar -External -Connection $hubConnection

**Expected behaviour:**
Once a link is added to top navigation, it should appear without an admin intervention.

**Actual behaviour** 
Please describe what you see instead. Please provide samples of output or screenshots.

**The version of the Cmdlet module I am running is:**
PnP.PowerShell 1.10.1

### Which operating system/environment are you running PnP PowerShell on?
- Windows
- Azure Functions
- also MS Edge and Chrome are used to test

**Comment by Studermarc** [comment] 2022-06-16 20:46
Hi @PARR55, 

The behaviour you are observing is by design and doesn't have anything to do with the "Add-PnPNavigationNode" Cmdlet. 

The HubSite Navigation is beeing cached on the SharePoint Site. This means you have to refresh the HubSite Navigation Cache if you want the newly added NavigationNode to be displayed. (This occurs when you click on the "Edit" button of the HubSite Navigation.)

You can do this in your script as well, you simply need to call the same EndPoint as SharePoint is using to Refresh the cache:

Try this:

`
$HubSiteUrl = "YOUR_HUBSITE_URL"

#Set The EndPoint
$EndPoint = "$HubSiteUrl/_api/web/HubSiteData(true)"

#Connect to the Hubsite (Requires Delegated Access, as far as I know
$Connection = Connect-PnPOnline -Url $HubSiteUrl -ReturnConnection

#Get AppAuth Access Token (this is used to call the API EndPoint)
$AccessToken = Get-PnPAppAuthAccessToken -Connection $Connection

#Set Headers
$Headers = @{
    "Authorization" = "Bearer $AccessToken"
    "Accept"        = "application/json;odata=verbose"
}

#Call the Endpoint
$InvokeRestMethodParameters = @{
    "Headers" = $Headers
    "Uri"     = $EndPoint
    "Method"  = "GET"
}
$HubSiteData = Invoke-RestMethod @InvokeRestMethodParameters
`

**Comment by gautamdsheth** [comment] 2022-06-17 07:24
Thanks @Studermarc  for sharing this !
@PARR55  - as mentioned above this is by design, you need to refresh the HubSiteCache and after that it will start showing.

You can also use `Invoke-PnPSPRestMethod` as well to make this request which Marc mentioned.
Will be closing this issue as designed.

**Closed by gautamdsheth** 2022-06-17 07:24 UTC
Labels: bug

**Comment by kasperbolarsen** [comment] 2023-10-06 09:05
are you added the node to a Hub site global navigation ?
