### ISSUE TITLE
[BUG] Set-PnPPageTextPart is creating duplicate page title in SharePoint modern page

### ISSUE THREAD

**Issue by cibun** [pnp/powershell#4331] opened 2024-09-23 15:24 UTC
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
 Set-PnPPageTextPart is creating duplicate page title in SharePoint modern page
when trying to update the text value of OOTB text webpart. Automatically a new Banner Page title is getting added to the page.
### Expected behavior 
A Duplicate Page title should not get created when the webpart text is getting updated.

### Actual behavior 
But a duplicate page title is getting added

### Steps to reproduce behavior
Its very straight forward just by executing one line of code for adding text to a webpart easily can be reproducible

Set-PnPPageTextPart -Page Home -InstanceId a2875399-d6ff-43a0-96da-be6ae5875f82 -Text "MyText"

### What is the version of the Cmdlet module you are running?
powershell Version: 2.10.1
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2024-09-24 13:29
Closing as duplicate of https://github.com/pnp/powershell/issues/4313

**Closed by gautamdsheth** 2024-09-24 13:29 UTC
Labels: bug
