### ISSUE TITLE
[BUG] Connect-PNPOnline -interactive fails when MFA is enabled on 365 tenant

### ISSUE THREAD

**Issue by Luquos** [pnp/powershell#1920] opened 2022-05-31 11:08 UTC
### Reporting an Issue or Missing Feature
Reporting an issue

### Expected behavior 
Attempting to connect with MFA enabled on the tenant - Expect to login successfully.

### Actual behavior 
When attempting to connect, initial Microsoft authentication page is displayed, however when it reaches the URL "https://login.microsoftonline.com/common/reprocess?..." after completing the MFA process, the screen is blank and does not continue beyond this

### Steps to reproduce behavior
Connect-PnPOnline -Url https://hattrick.sharepoint.com -Interactive

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
Windows

**Comment by KoenZomers** [comment] 2022-05-31 21:37
@Luquos connecting like this in PnP PowerShell is used millions of times a day. I use it myself regularly as well. If this would be broken for some reason, I would expect many more issues to be reported, which is not the case. Can you check if it can be something on your side? Perhaps a proxy on your connection? Or some kind of weird policy? Try a different connection and/or machine and see if you get a different result. I.e. try [Azure Cloud Shell](https://pnp.github.io/powershell/articles/azurecloudshell.html) to rule out your machine.

**Comment by KoenZomers** [comment] 2022-06-01 09:29
Interesting. Technically PnP PowerShell uses MSAL to authenticate, which is nothing different from most other modern modules and applications such as Outlook and the rest of the Office products. Are you able and technically capable to capture a Fiddler trace while connecting and examine that? It could provide more insight into why it gets stuck. If you're not able to analyze it yourself, feel free to share it with me privately (don't share it here). It will contain your login information though, so if you do so, please use a temporary test account to log on with and disable or change password after capturing the Fiddler trace.

**Comment by KoenZomers** [comment] 2022-06-09 22:16
Any progress on this one @Luquos from your side? I cannot reproduce this from my side, so I'm afraid there's nothing I can do to resolve this for you.

**Comment by KoenZomers** [comment] 2022-06-20 07:00
Closing this as no further feedback received.

**Closed by KoenZomers** 2022-06-20 07:00 UTC
Labels: bug

**Comment by dgtheninja** [comment] 2022-06-28 14:20
I too have encountered this issue, and had to adjust my scripts to -UseWebLogin instead of -Interactive which does work.

After logging in I get the MFA challenge which I have completed both in the Authenticator App and using SMS but the auth box stays on the same page waiting to complete. I did try using Fiddler to check and it does appear that the result of the MFA is being returned to the client just not picked up
