### ISSUE TITLE
Suggest to change Owner to Owners

### ISSUE THREAD

**Issue by wonderplayer** [pnp/powershell#448] opened 2021-03-16 19:42 UTC
Currently, CommunicationSite and TeamSite templates have different parameters **Owner** and **Owners** respectively.
I understand that this is because of site creation information object, but it would be much more convenient in my opinion, if they would appear the same for command, so not to introduce **if** statement to check for site type.
https://github.com/pnp/powershell/blob/8d95de6f9faf1cde47e6ee155a193977828e22da/src/Commands/Admin/NewSite.cs#L80

**Comment by wonderplayer** [comment] 2021-03-16 19:49
Noticed that actually for communication sites, owner property is string rather than array. It would also be great if this could change as well, so not to add additional logic in script to add site collection administrators after site creation.

**Comment by gautamdsheth** [comment] 2021-03-17 14:15
Hello !
This is by design because the underlying API are different for the site types.
Communication site type accepts a single owner whereas a Team site accepts multiple owners. 
So, we cannot change them.

**Comment by gautamdsheth** [comment] 2021-03-26 15:06
Closing the issue as this is by API design and we cant change it.

**Closed by gautamdsheth** 2021-03-26 15:06 UTC
