### ISSUE TITLE
[BUG] Register-PnPEntraIDApp never completes

### ISSUE THREAD

**Issue by bcarnazzi** [pnp/powershell#4287] opened 2024-09-13 12:08 UTC
### Reporting an Issue or Missing Feature
The command Register-PnPEntraIDApp never finish. I got a warning saying "No permissions specified, using default permissions" and nothing else, no device code webpage, nothing.

### Expected behavior 
The command should give me a device code that I can use in the device code URL.

### Actual behavior 
Just a warning saying "No permissions specified, using default permissions". The cmdlet is stuck.

### Steps to reproduce behavior
$result = Register-PnPEntraIDApp -ApplicationName "PnP App Only Access" -Tenant xxxx.onmicrosoft.com -OutPath c:\mycertificates -DeviceLogin

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [X] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

(Tried both, same behavior)

**Comment by gautamdsheth** [comment] 2024-09-13 12:26
The issue with DeviceLogin is fixed in the nightly builds, can you please try the latest nightly `2.12.4-nightly` and let us know ?

**Comment by kjellbrandes** [comment] 2024-09-18 11:07
Same behavior for me, fixed it by using nightly build 2.12.9

**Comment by veronicageek** [comment] 2024-09-18 13:28
Thanks for confirming @kjellbrandes.
@bcarnazzi - Please update to the nightly. Closing this now.

**Closed as completed by veronicageek** 2024-09-18 13:28 UTC
Labels: bug

**Comment by renewtx** [comment] 2024-10-17 16:02
Hello -- i am running into this issue currently, but when I try to upgrade to 2.12.4-nightly I get this error:

Install-Package: The version '2.12.4' of the module 'PnP.PowerShell' being installed is not catalog signed. Ensure that the version
'2.12.4' of the module 'PnP.PowerShell' has the catalog file 'PnP.PowerShell.cat' and signed with the same publisher
'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module
'PnP.PowerShell' with version '1.12.0' under the directory 'C:\Program
Files\WindowsPowerShell\Modules\PnP.PowerShell\1.12.0'. If you still want to install or update, use -SkipPublisherCheck
parameter.

![image](https://github.com/user-attachments/assets/7710fc74-5150-43ce-bc68-31742198fe93)

Any idea how to resolve?  I am using PowerShell v7.4.5

![image](https://github.com/user-attachments/assets/86176f97-937c-494b-88ef-4cf181d615f1)

**Comment by frazeraccount** [comment] 2024-10-25 19:04
I installed 2.99.23-nightly.  I got a few steps further.  It received the pop-up window, entered the code provided, signed in using my Entra ID and password (and entering code in MS Authenticator) as prompted by the pop-up Window, then closed the pop-up Window as instructed.  Now it's stuck, displaying the following.

WARNING:
 No permissions specified, using default permissions


WARNING:
 Please login.
  
 We opened a popup window and navigated to https://microsoft.com/devicelogin
  
 Enter code: E5LQZXYYE (we copied this code to your clipboard)
  
 NOTICE: close the popup after you authenticated successfully to continue the process.

**Comment by renewtx** [comment] 2024-10-25 22:15
I’ve finally figured out how to get past the issue I encountered with the running the cmdlet ... below are the steps I followed.   Hopefully this will help others ...

I was able to register PowerShell for APP-based access as (sort of) described [here](https://pnp.github.io/powershell/articles/registerapplication.html#setting-up-access-to-your-own-entra-id-app-for-app-only-access) using the following steps:
1.	I first had to remove my existing version of PnP.PowerShell under PowerShell v7.x … So, I opened a PowerShell v7.x window and then executed the command “**Uninstall-Module PnP.PowerShell**”
2.	Once uninstalled, I then ran the command “**Install-Module PnP.PowerShell -AllowPrerelease -SkipPublisherCheck -Force**” – that installed the very latest ‘nightly’ release of PnP.PowerShell

 
![image](https://github.com/user-attachments/assets/a70f0792-b326-4f9f-9560-838967b1c9b6)


3.	Once that was installed, I was able to run the command

$result = Register-PnPAzureADApp -ApplicationName "PnP PowerShell Task" -Tenant mysticdev.onmicrosoft.com -OutPath c:\certs -CertificatePassword (ConvertTo-SecureString -String "password" -AsPlainText -Force) -Interactive

as described [here](https://pnp.github.io/powershell/cmdlets/Register-PnPAzureADApp.html)

NOTE a couple of things:
-	The command I ran is slightly different than described in the original post above … when you look up the cmdlet “Register-PnPEntraIDApp”, it is actually a pseudonym for Register-PnPAzureADApp, and this latter command provided me with additional functionality that it looks like I needed
-	After the command executes and completes, run the command **$result.Base64Encoded > c:\certs\Base64Key.txt** to save the Base64Key value to a file just in case it is needed later

4.	This opened a login pop-up window asking me to login 
5.	The cmdlet then initiated a consent workflow which (after a few secs) displayed another login window

![image](https://github.com/user-attachments/assets/0eca2f45-4a3c-43ce-8793-5d99b172b63a)

6.	After logging in the following was displayed, and I clicked Accept 

![image](https://github.com/user-attachments/assets/c518ecb9-91c7-45bf-ac65-d5d6e4814145)

7.	The result was creation of the relevant app reg with corresponding ID

![image](https://github.com/user-attachments/assets/c9991dd4-a4c7-45a0-bc56-8311bc52aed4)

![image](https://github.com/user-attachments/assets/2c19c2b9-594b-4ef8-a5bb-4233e9fc82fb)

8.	In addition, the relevant certificates were created and stored in the location specified with the -Outpath parameter

![image](https://github.com/user-attachments/assets/86077218-8db7-45ee-b716-2f76b4c8cbad)

**Comment by githubarrix** [comment] 2024-12-04 12:40
I can confirm that Register-PnPEntraIDApp with the -DeviceLogin parameter hangs after successfully authenticating and having closed the tab as requested.

![image](https://github.com/user-attachments/assets/7d602002-5f2e-4ba6-ae70-48f92c8fb30a)

**Comment by joelvmalibu** [comment] 2024-12-18 16:18
I'm getting this error still as well. I'm on the newest version of the nightly. I followed @renewtx instructions. I removed the -Interactive flag because it said it was invalid. I got the pop-up for login, logged in with my account, but my Powershell window is still stuck on 

WARNING:
 No permissions specified, using default permissions

**Comment by AlNoes** [comment] 2025-01-08 08:44
In our company we could narrow it down to SentinelOne.
When enabled, the registration is stuck without any logs.

Disabling SentinelOne helps immediately. But since this can only be done by our central IT, this is nothing we can do on a daily basis.
There are also no logs in SentinelOne about anything blocked.

**Comment by acalvin-cab** [comment] 2025-01-08 14:13
> In our company we could narrow it down to SentinelOne. When enabled, the registration is stuck without any logs.
> 
> Disabling SentinelOne helps immediately. But since this can only be done by our central IT, this is nothing we can do on a daily basis. There are also no logs in SentinelOne about anything blocked.
> 
> See here as well: #4215

We also have SentinelOne so that could definitely be the source of the issue. I ended up creating the app manually, but it would be nice to have this fixed. I wonder if its something SentinelOne needs to fix then?

**Comment by joelvmalibu** [comment] 2025-01-08 14:20
> In our company we could narrow it down to SentinelOne. When enabled, the registration is stuck without any logs.
> 
> Disabling SentinelOne helps immediately. But since this can only be done by our central IT, this is nothing we can do on a daily basis. There are also no logs in SentinelOne about anything blocked.
> 
> See here as well: #4215

We also have SentinelOne. You might be on to something here.

**Comment by richjnsn** [comment] 2025-01-09 12:51
I can confirm, that I also have this problem, and my centrally managed Win11 have Sentinel One installed as well.

**Comment by richjnsn** [comment] 2025-01-09 12:51
> In our company we could narrow it down to SentinelOne. When enabled, the registration is stuck without any logs.
> 
> Disabling SentinelOne helps immediately. But since this can only be done by our central IT, this is nothing we can do on a daily basis. There are also no logs in SentinelOne about anything blocked.
> 
> See here as well: #4215


I can confirm, that I also have this problem, and my centrally managed Win11 have Sentinel One installed as well.

**Comment by p-bojkowski** [comment] 2025-02-20 16:54
Here is a working solution:

`#Requires -RunAsAdministrator

<#
.SYNOPSIS
    Registers an Entra ID Application for PnP PowerShell with App-Only access.

.DESCRIPTION
    This script automates the registration of an Entra ID Application specifically configured
    for use with PnP PowerShell. It includes proper permission setup for Sites.FullControl.All
    and generates necessary certificates for authentication.

    Note: If the script hangs during registration (especially with SentinelOne), try using the
    -UseInteractive switch parameter instead of DeviceLogin.

.PARAMETER TenantName
    The name of your tenant (e.g., contoso.onmicrosoft.com)

.PARAMETER ApplicationName
    The display name for the Entra ID Application

.PARAMETER CertificatePath
    The path where the certificate files will be saved

.PARAMETER UseInteractive
    Switch to use Interactive login instead of DeviceLogin (may help if DeviceLogin hangs)

.PARAMETER CertificatePassword
    Optional password for the certificate

.EXAMPLE
    .\Register-PnPEntraApp.ps1 -TenantName "contoso.onmicrosoft.com" -ApplicationName "PnP PowerShell Automation" -CertificatePath "C:\Certificates"

.EXAMPLE
    .\Register-PnPEntraApp.ps1 -TenantName "contoso.onmicrosoft.com" -ApplicationName "PnP PowerShell Automation" -CertificatePath "C:\Certificates" -UseInteractive -CertificatePassword (ConvertTo-SecureString -String "MyPassword" -AsPlainText -Force)

.NOTES
    Version:        1.2
    Author:         Pawel Bojkowski
    Creation Date:  2025-02-20
    Purpose/Change: Added timeout and progress bars
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [ValidatePattern('\.onmicrosoft\.com$')]
    [string]$TenantName,

    [Parameter(Mandatory = $true)]
    [ValidateNotNullOrEmpty()]
    [string]$ApplicationName,

    [Parameter(Mandatory = $true)]
    [ValidateScript({Test-Path $_ -IsValid})]
    [string]$CertificatePath,

    [Parameter()]
    [switch]$UseInteractive,

    [Parameter()]
    [SecureString]$CertificatePassword,

    [Parameter(DontShow)]
    [Switch]$InPwsh
)

function Install-PowerShell7 {
    try {
        Write-Host "Checking latest PowerShell version from GitHub API..." -ForegroundColor Cyan
        $apiUrl = "https://api.github.com/repos/PowerShell/PowerShell/releases/latest"
        $release = Invoke-RestMethod -Uri $apiUrl
        
        $asset = $release.assets | Where-Object { 
            $_.name -like "*win-x64.msi" 
        } | Select-Object -First 1

        if (-not $asset) {
            throw "Could not find PowerShell MSI installer"
        }

        $installerPath = Join-Path $env:TEMP $asset.name
        
        Write-Host "Downloading PowerShell installer..." -ForegroundColor Cyan
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $installerPath

        if (Test-Path $installerPath) {
            Write-Host "Installing PowerShell..." -ForegroundColor Cyan
            $arguments = "/i `"$installerPath`" /quiet ADD_EXPLORER_CONTEXT_MENU_OPENPOWERSHELL=1 ENABLE_PSREMOTING=1 REGISTER_MANIFEST=1 USE_MU=1 ENABLE_MU=1 ADD_PATH=1"
            $process = Start-Process msiexec.exe -ArgumentList $arguments -Wait -PassThru

            if ($process.ExitCode -eq 0) {
                Write-Host "PowerShell installation completed successfully." -ForegroundColor Green
                return $true
            } else {
                throw "Installation failed with exit code: $($process.ExitCode)"
            }
        }
    }
    catch {
        Write-Error "Failed to install PowerShell 7: $_"
        return $false
    }
    finally {
        if (Test-Path $installerPath) {
            Remove-Item $installerPath -Force
        }
    }
}

function Install-PnPPowerShell {
    try {
        Write-Host "Checking PowerShell Gallery access..." -ForegroundColor Cyan
        if (-not (Get-PSRepository -Name "PSGallery" -ErrorAction SilentlyContinue)) {
            Register-PSRepository -Default
        }
        Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted

        # Get all available versions including prerelease
        Write-Host "Checking latest available PnP.PowerShell version..." -ForegroundColor Cyan
        $availableModules = Find-Module PnP.PowerShell -AllVersions -AllowPrerelease | Sort-Object Version -Descending
        $latestVersion = $availableModules[0].Version
        
        # Check current installation
        $currentModule = Get-Module -Name PnP.PowerShell -ListAvailable | 
            Sort-Object Version -Descending | 
            Select-Object -First 1

        Write-Host "Latest available version: $latestVersion" -ForegroundColor Cyan
        if ($currentModule) {
            Write-Host "Currently installed version: $($currentModule.Version)" -ForegroundColor Cyan
        } else {
            Write-Host "No version currently installed" -ForegroundColor Yellow
        }

        # Install/Update if needed
        if (-not $currentModule -or $currentModule.Version -lt $latestVersion) {
            Write-Host "Installing latest PnP.PowerShell module..." -ForegroundColor Cyan
            
            # Remove any existing versions first
            Get-Module PnP.PowerShell -ListAvailable | ForEach-Object {
                Write-Host "Removing old version: $($_.Version)" -ForegroundColor Yellow
                Uninstall-Module -Name PnP.PowerShell -RequiredVersion $_.Version -Force -ErrorAction SilentlyContinue
            }

            # Install latest version
            Install-Module -Name PnP.PowerShell -AllowPrerelease -Force -SkipPublisherCheck -Scope CurrentUser -RequiredVersion $latestVersion
            Import-Module PnP.PowerShell -Force -RequiredVersion $latestVersion
            
            $verifyModule = Get-Module PnP.PowerShell
            Write-Host "Successfully installed PnP.PowerShell version: $($verifyModule.Version)" -ForegroundColor Green
        } else {
            Write-Host "Already on latest version." -ForegroundColor Green
            Import-Module PnP.PowerShell -Force -RequiredVersion $latestVersion
        }
        
        return $true
    }
    catch {
        Write-Error "Failed to install/update PnP.PowerShell module: $_"
        Write-Host "Troubleshooting steps:" -ForegroundColor Yellow
        Write-Host "1. Try removing existing versions manually: Uninstall-Module PnP.PowerShell -AllVersions -Force" -ForegroundColor Yellow
        Write-Host "2. Clear local PowerShell Gallery cache: Clear-Item -Path 'Microsoft.PowerShell.Core\FileSystem::$env:LOCALAPPDATA\Microsoft\Windows\PowerShell\PowerShellGet\' -Force" -ForegroundColor Yellow
        Write-Host "3. Verify you have internet access to PowerShellGallery.com" -ForegroundColor Yellow
        return $false
    }
}

function Start-ScriptInPwsh {
    param(
        [string]$ScriptPath,
        [string]$TenantName,
        [string]$ApplicationName,
        [string]$CertificatePath,
        [switch]$UseInteractive,
        [SecureString]$CertificatePassword
    )

    $pwshPath = "$env:ProgramFiles\PowerShell\7\pwsh.exe"
    if (Test-Path $pwshPath) {
        Write-Host "Restarting script in PowerShell 7..." -ForegroundColor Cyan
        
        $arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$ScriptPath`" " +
                    "-TenantName `"$TenantName`" " +
                    "-ApplicationName `"$ApplicationName`" " +
                    "-CertificatePath `"$CertificatePath`" "

        if ($UseInteractive) {
            $arguments += "-UseInteractive "
        }

        if ($CertificatePassword) {
            $arguments += "-CertificatePassword (ConvertTo-SecureString -String `"$([Runtime.InteropServices.Marshal]::PtrToStringAuto([Runtime.InteropServices.Marshal]::SecureStringToBSTR($CertificatePassword)))`" -AsPlainText -Force) "
        }

        $arguments += "-InPwsh"
        
        Start-Process -FilePath $pwshPath -ArgumentList $arguments -Wait
        exit
    }
    return $false
}

function Show-ProgressTimeout {
    param (
        [int]$TimeoutSeconds,
        [string]$Activity,
        [System.Management.Automation.Job]$Job
    )
    
    $startTime = Get-Date
    $timeElapsed = 0
    
    while ($timeElapsed -lt $TimeoutSeconds) {
        $timeElapsed = ((Get-Date) - $startTime).TotalSeconds
        $remainingSeconds = [math]::Round($TimeoutSeconds - $timeElapsed)
        $percentComplete = ($timeElapsed / $TimeoutSeconds) * 100
        
        # Check if job has completed successfully
        if ($Job.State -eq 'Completed') {
            Write-Progress -Activity $Activity -Completed
            return $true
        }
        
        # Check if job has failed
        if ($Job.State -eq 'Failed') {
            Write-Progress -Activity $Activity -Completed
            return $false
        }
        
        Write-Progress -Activity $Activity `
                     -Status "Waiting for authentication... Time remaining: $remainingSeconds seconds" `
                     -PercentComplete $percentComplete
        
        # More granular sleep to be more responsive
        Start-Sleep -Milliseconds 500
    }
    
    Write-Progress -Activity $Activity -Completed
    return $false
}

# Main script execution
try {
    # Check if running in PowerShell 7
    if (-not $InPwsh -and $PSVersionTable.PSVersion.Major -lt 7) {
        Write-Host "PowerShell 7 is required. Current version: $($PSVersionTable.PSVersion)" -ForegroundColor Yellow
        
        # Install PowerShell 7 if not present
        if (-not (Test-Path "$env:ProgramFiles\PowerShell\7\pwsh.exe")) {
            Write-Host "Installing PowerShell 7..." -ForegroundColor Cyan
            if (-not (Install-PowerShell7)) {
                throw "Failed to install PowerShell 7"
            }
        }

        # Restart script in PowerShell 7
        Start-ScriptInPwsh -ScriptPath $PSCommandPath -TenantName $TenantName -ApplicationName $ApplicationName -CertificatePath $CertificatePath -UseInteractive:$UseInteractive -CertificatePassword $CertificatePassword
        exit
    }

    # Now we're in PowerShell 7, check for PnP.PowerShell module
    if (-not (Get-Module -ListAvailable -Name PnP.PowerShell)) {
        Write-Host "PnP.PowerShell module is required." -ForegroundColor Yellow
        if (-not (Install-PnPPowerShell)) {
            throw "Failed to install PnP.PowerShell module"
        }
    }

    # Create certificate directory if it doesn't exist
    if (-not (Test-Path $CertificatePath)) {
        New-Item -ItemType Directory -Path $CertificatePath -Force | Out-Null
    }

    # Register the application
    Write-Host "Starting Entra ID Application registration..." -ForegroundColor Cyan
    
    $timeoutSeconds = 90
    $result = $null

    # Try interactive mode first as it's more reliable
    Write-Host "Attempting registration with Interactive mode (timeout: $timeoutSeconds seconds)..." -ForegroundColor Cyan
    $params = @{
        ApplicationName = $ApplicationName
        Tenant = $TenantName
        OutPath = $CertificatePath
        Interactive = $true
        SharePointApplicationPermissions = "Sites.FullControl.All"
        Verbose = $true
    }
    if ($CertificatePassword) {
        $params['CertificatePassword'] = $CertificatePassword
    }
    
    try {
        # Create a background job for Interactive login
        $interactiveJob = Start-Job -ScriptBlock {
            param($Params)
            Import-Module PnP.PowerShell
            Register-PnPAzureADApp @Params
        } -ArgumentList $params

        $success = Show-ProgressTimeout -TimeoutSeconds $timeoutSeconds -Activity "Interactive Authentication" -Job $interactiveJob
        
        if ($success) {
            $result = Receive-Job -Job $interactiveJob
            if ($result) {
                Write-Host "Interactive registration successful!" -ForegroundColor Green
            }
        } else {
            Write-Host "Interactive registration timed out after $timeoutSeconds seconds" -ForegroundColor Yellow
            Stop-Job -Job $interactiveJob -ErrorAction SilentlyContinue
            Remove-Job -Job $interactiveJob -Force
        }
    }
    catch {
        Write-Host "Interactive registration failed: $_" -ForegroundColor Yellow
        if ($interactiveJob) {
            Remove-Job -Job $interactiveJob -Force -ErrorAction SilentlyContinue
        }
    }

    # Try DeviceLogin if Interactive failed or timed out
    if (-not $result) {
        Write-Host "Trying DeviceLogin as fallback (timeout: $timeoutSeconds seconds)..." -ForegroundColor Yellow
        
        $params['Interactive'] = $false
        $params['DeviceLogin'] = $true
        
        try {
            # Create a background job for DeviceLogin
            $deviceLoginJob = Start-Job -ScriptBlock {
                param($Params)
                Import-Module PnP.PowerShell
                Register-PnPAzureADApp @Params
            } -ArgumentList $params

            $success = Show-ProgressTimeout -TimeoutSeconds $timeoutSeconds -Activity "Device Login Authentication" -Job $deviceLoginJob
            
            if ($success) {
                $result = Receive-Job -Job $deviceLoginJob
                if ($result) {
                    Write-Host "DeviceLogin registration successful!" -ForegroundColor Green
                }
            } else {
                Write-Host "DeviceLogin registration timed out after $timeoutSeconds seconds" -ForegroundColor Yellow
                Stop-Job -Job $deviceLoginJob -ErrorAction SilentlyContinue
                Remove-Job -Job $deviceLoginJob -Force
                throw "Registration timed out"
            }
        }
        catch {
            Write-Host "DeviceLogin registration failed: $_" -ForegroundColor Red
            if ($deviceLoginJob) {
                Remove-Job -Job $deviceLoginJob -Force -ErrorAction SilentlyContinue
            }
            throw "Failed to register application using both Interactive and DeviceLogin methods"
        }
    }

    if (-not $result) {
        throw "Failed to register Entra ID Application (both methods timed out or failed)"
    }

    # Store the Base64Encoded certificate separately
    if ($result.Base64Encoded) {
        $base64Path = Join-Path $CertificatePath "$ApplicationName.b64"
        $result.Base64Encoded | Set-Content $base64Path
        Write-Host "Base64 encoded certificate saved to: $base64Path" -ForegroundColor Green
    }

    # Store application details
    $appDetails = @{
        ClientId = $result.AzureAppId
        CertificatePath = Join-Path $CertificatePath "$ApplicationName.pfx"
        TenantId = $result.AzureTenantId
    }

    $appDetailsPath = Join-Path $CertificatePath "app_details.json"
    $appDetails | ConvertTo-Json | Set-Content $appDetailsPath

    # Generate connection script for both certificate methods
    $connectionScriptPath = Join-Path $CertificatePath "connect_script.ps1"
    @"
# PnP PowerShell Connection Script - Certificate File Method
Connect-PnPOnline -Url "https://$($TenantName.Split('.')[0]).sharepoint.com" ``
    -ClientId "$($result.AzureAppId)" ``
    -CertificatePath "$($appDetails.CertificatePath)" ``
    -Tenant "$TenantName"

# Alternative Base64 Certificate Method
Connect-PnPOnline -Url "https://$($TenantName.Split('.')[0]).sharepoint.com" ``
    -ClientId "$($result.AzureAppId)" ``
    -Tenant "$TenantName" ``
    -CertificateBase64Encoded (Get-Content "$base64Path")
"@ | Set-Content $connectionScriptPath

    # Final output
    Write-Host "`nApplication Registration Successful!" -ForegroundColor Green
    Write-Host "Application ID: $($result.AzureAppId)" -ForegroundColor Cyan
    Write-Host "Certificate Path: $($appDetails.CertificatePath)" -ForegroundColor Cyan
    Write-Host "Base64 Certificate: $base64Path" -ForegroundColor Cyan
    Write-Host "Connection script generated at: $connectionScriptPath" -ForegroundColor Cyan
    Write-Host "`nUse the generated connection script to connect to your tenant." -ForegroundColor Yellow

} catch {
    Write-Error "An error occurred: $_"
    throw
}`

![Image](https://github.com/user-attachments/assets/a85d24c3-f087-4ffc-a335-b344ea17302b)

**Comment by gaiking-uk** [comment] 2025-03-04 01:58
I also have this issue (have been having it since before Christmas)... I can't re-open this issue, so I have created a #4768 to log the fault.

**Comment by danielheuer** [comment] 2025-03-28 16:02
I also have same issue using Sentinel One on Windows
