### ISSUE TITLE
[FEATURE] Set-PnPTeamsTeamPicture should update image for any group

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#750] opened 2021-05-31 23:23 UTC
**Is your feature request related to a problem? Please describe.**
It seems as of now `Set-PnPTeamsTeamPicture` allows to set photo for groups an admin is an owner of. Otherwise it would throw an error.
If working through PnP,PowerShell app and Global Admin an error would be: `Set-PnPTeamsTeamPicture: User does not have permissions to execute this action.`
In case a separate Azure app granted `Group.ReadWrite.All` permission is being used, the error will change to: `Set-PnPTeamsTeamPicture: Access is denied. Check credentials and try again.`

**Describe the solution you'd like**
`Set-PnPTeamsTeamPicture` should update image for any group regardless of the ownership both using a standalone app or PnP PowerShell App and global admin credentials.

**Describe alternatives you've considered**
There is just one workaround:

1. Make yourself an owner of a Team
2. Add image from Teams desktop app

**Additional context**
![image](https://user-images.githubusercontent.com/5260172/120248524-3a05e780-c280-11eb-8344-bbba6dd6451e.png)

![image](https://user-images.githubusercontent.com/5260172/120248481-088d1c00-c280-11eb-8822-6dfe44f0cb5f.png)

`PnP.PowerShell 1.5.59`

**Comment by gautamdsheth** [comment] 2021-06-01 07:30
Hello @YuriySamorodov , that is not how authentication works.  `Group.ReadWrite.All` in the PnP management shell is a delegated permission. So, only if the user has access to the team will they be able to update its photo. It doesn't matter if the user is Global admin or not, what matters is that user is owner of the team.

For a scenario you are describing, you should create a new Azure AD app and ensure that `Group.ReadWrite.All` has application permission and authenticate to PnP using clientId + certificate. This way you will be able to update teams picture of any teams without having to manually add yourself as owner of a team.

**Comment by YuriySamorodov** [comment] 2021-06-01 10:45
Thanks @gautamdsheth 
That's the thing! When I am trying to use separate app with `Group.ReadWrite.All` **application** permission it would throw an error `Set-PnPTeamsTeamPicture: Access is denied. Check credentials and try again`

**Comment by YuriySamorodov** [comment] 2021-06-01 11:26
@gautamdsheth , Just tried to set image for a group I am an owner of and got an error:
`Set-PnPTeamsTeamPicture: User does not have permissions to execute this action` while connected with PnP.Management app.

**Comment by gautamdsheth** [comment] 2021-06-01 19:55
@YuriySamorodov - not sure what's the issue at your end, am not able to repro it. 
Tried it using Global admin account + owner of team using PnP management shell app. It worked.

![image](https://user-images.githubusercontent.com/8832018/120382513-5ae24180-c341-11eb-81aa-7cc709873800.png)

**Comment by YuriySamorodov** [comment] 2021-06-01 20:14
Hi @gautamdsheth,

Thanks for the prompt response. Have you had a chance to try png instead of jpg?

**Comment by gautamdsheth** [comment] 2021-06-01 20:18
Yep, that works as well.

![image](https://user-images.githubusercontent.com/8832018/120384952-726ef980-c344-11eb-91a9-d83ff7953f98.png)

Just ensure that you are not using old version of PnP PowerShell, you can remove the old versions from the file system. Usually from Prog Files > Windows PowerShell > ... > PnP.PowerShell

**Comment by YuriySamorodov** [comment] 2021-06-01 21:01
Thanks @gautamdsheth. Does this mean it won't work with under app with **Group.ReadWriteAll** permissions?

**Comment by YuriySamorodov** [comment] 2021-06-01 21:05
@gautamdsheth just noticed you are connecting to some site without -admin portion.
I am connecting to Admin site. Am I doing it wrong?
![image](https://user-images.githubusercontent.com/5260172/120390349-46e51280-c336-11eb-80d0-97ae6e33e72a.png)

**Comment by gautamdsheth** [comment] 2021-06-02 07:25
Well it shouldn't matter which site you are connecting to. 
What happens if connect to non-admin site and try setting the teams picture ?

**Comment by gautamdsheth** [comment] 2022-01-16 13:42
Closing this issue.
Not able to reproduce this one and also tested it multiple times, it does work both delegated and application permissions.
It does take some time for the picture to appear/update, so need to wait for it. Sometimes might take 24 hours as well.

**Closed by gautamdsheth** 2022-01-16 13:42 UTC
Labels: enhancement

**Comment by pl4nty** [comment] 2022-01-24 07:25
@gautamdsheth I can repro this with application permissions (Groups.ReadWrite.All). Aren't the group photo endpoints [known to only support delegated perms](https://docs.microsoft.com/en-us/graph/known-issues#some-group-apis-dont-support-delegated-or-app-only-permissions)?
