### ISSUE TITLE
[BUG] Microsoft.Graph and PnP.PowerShell conflict (Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider')

### ISSUE THREAD

**Issue by nicole-ge** [pnp/powershell#3920] opened 2024-04-26 10:04 UTC
Describe the bug
When using the Microsoft.Graph and [PnP.PowerShell](https://github.com/pnp/powershell) module in the same script

fails with the following exception:
Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=315'.

The error occurs if the script is executed locally as well as an Azure Automation runbook.

Using module 2.4.0 | PnP.PowerShell in Azure Automation

**Comment by nicole-ge** [comment] 2024-04-26 10:25
Hello @gautamdsheth 

Can you help to fix this issue?

My bug seemed to similar to 
[Bug #2285](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2285)

**Comment by gautamdsheth** [comment] 2024-04-27 10:37
Closing as duplicate of #3637 .

We are tracking that via the above linked issue, no updates as yet for that unfortunately.

**Closed by gautamdsheth** 2024-04-27 10:37 UTC
Labels: bug

**Comment by nicole-ge** [comment] 2024-04-27 17:37
Hi @gautamdsheth 

Thank you for your answer. This bug seems to concern a lot of people and we have no workaround for it. How can I help to solve this bug? Please let me know I need to work with pnp and graph in one powershell script within one runbook

**Comment by RobIreland-OastHouseLtd** [comment] 2024-04-30 16:29
Seeing the same issue, my DEV VM is Windows 11 and has the following installed 

PowerShell Version: 7.4.2
PnP PowerShell Version: 2.4.0
Microsoft.Graph Version: 2.18.0
Microsoft.Graph.Beta Version: 2.18.0
Microsoft.Identity.Client: 4.53.0

The error happens in the following line of code
```
$eid = get-mggroup -consistencylevel eventual -search $groupSearchTerm …
     | Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly      
     | 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```
Consistently happens when I'm running the script via VS Code Terminal Window (Powershell 7.4.2 process) or from my Terminal Window (PowerShell 7.4.2)

**Comment by scm7ak** [comment] 2024-07-08 17:18
if you run the Graph stuff in a separate runspace (in my case a job), then you can circumvent the issue.

It's not a fix, but a workaround.

I hope there is a resolution soon.

**Comment by nicole-ge** [comment] 2024-11-14 22:38
> Seeing the same issue, my DEV VM is Windows 11 and has the following installed 
> 
> PowerShell Version: 7.4.2
> PnP PowerShell Version: 2.4.0
> Microsoft.Graph Version: 2.18.0
> Microsoft.Graph.Beta Version: 2.18.0
> Microsoft.Identity.Client: 4.53.0
> 
> The error happens in the following line of code
> ```
> $eid = get-mggroup -consistencylevel eventual -search $groupSearchTerm …
>      | Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly      
>      | 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
> ```
> Consistently happens when I'm running the script via VS Code Terminal Window (Powershell 7.4.2 process) or from my Terminal Window (PowerShell 7.4.2)

I have the same issue. Have someone a workaround?

**Comment by khha** [comment] 2024-11-18 09:33
I have the same issue. Im using pnp version 2.12.0 and get the error: 

```
Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0,
      | Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

**Comment by carl0ski** [comment] 2024-12-04 02:52
Not sure why this keeps getting closed as it is a genuine conflict of services

PNP is genuinely conflicting with 3rd party module Microsoft.Graph
PNP loading an object with the same name as Microsoft.Graph.Core, 
the resolution would be stop bundling the library and call the local installed version as a dependency?

The Bundled one confuses the Microsoft.Graph.Authentication from loading the real Microsoft.Graph.Core

```
get-module -Name Microsoft.Graph* -ListAvailable
    Directory: C:\Program Files\PowerShell\Modules
ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.9.1                 Microsoft.Graph.Authentication

```

```
get-module -Name PNP* -ListAvailable

    Directory: C:\Program Files\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   2.99.63    nightly    PnP.PowerShell
```


```
Get-MgUser
Get-MgUser_List: Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, 
```
*Note PNP Microsoft.Graph.Core, Version 1.25.1.0  != Microsoft.Graph installed 2.9.1

**Comment by carl0ski** [comment] 2024-12-04 02:58
> > Seeing the same issue, my DEV VM is Windows 11 and has the following installed
> > PowerShell Version: 7.4.2
> > PnP PowerShell Version: 2.4.0
> > Microsoft.Graph Version: 2.18.0
> > Microsoft.Graph.Beta Version: 2.18.0
> > Microsoft.Identity.Client: 4.53.0
> > The error happens in the following line of code
> > ```
> > $eid = get-mggroup -consistencylevel eventual -search $groupSearchTerm …
> >      | Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly      
> >      | 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Consistently happens when I'm running the script via VS Code Terminal Window (Powershell 7.4.2 process) or from my Terminal Window (PowerShell 7.4.2)
> 
> I have the same issue. Have someone a workaround?

The work around is to do all the work you need to do in Graph first, 

then afterwards do all the work you need in PNP
Like 
Connect-mggraph
$alltheUsersINeed = Get-MGUser

connect-pnponline
# MG will no longer be available
$alltheUsersINeed
# i could not get remove-pnp module to fix graph either for that session 
# if someone could unload PNP then repair the loaded Graph in the same script would be helpful


But if you're like me pulling data from PNP and feeding it back to activities in Graph can't really think of anything other that passing chunks of infor across different Shell sessions

**Comment by carl0ski** [comment] 2024-12-04 03:42
> > Seeing the same issue, my DEV VM is Windows 11 and has the following installed
> > PowerShell Version: 7.4.2
> > PnP PowerShell Version: 2.4.0
> > Microsoft.Graph Version: 2.18.0
> > Microsoft.Graph.Beta Version: 2.18.0
> > Microsoft.Identity.Client: 4.53.0
> > The error happens in the following line of code
> > ```
> > $eid = get-mggroup -consistencylevel eventual -search $groupSearchTerm …
> >      | Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly      
> >      | 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Consistently happens when I'm running the script via VS Code Terminal Window (Powershell 7.4.2 process) or from my Terminal Window (PowerShell 7.4.2)
> 
> I have the same issue. Have someone a workaround?

https://github.com/pnp/powershell/issues/3637

They had 1 Delete the 125 file Microsoft.Graph.Core.dll from Modules PNP.Powershell Core Folder 
but some modules like Get-PnPSiteTemplate have a hard coded dependency to 1.25
which i guess is why it has not been fixed for so long overall

Another was to do all the MG work first to force it to load the native Microsoft.Graph.Core.dll first
but that too seems to fail to allow MG run after any PNP occurs
PNP unloads the real Microsoft.Graph.Core.dll and breaks all MG as soon as PNP commands are run

**Comment by Borgquite** [comment] 2025-05-27 10:00
If you are still experiencing this issue, it may be resolved in the latest nightly builds
https://github.com/pnp/powershell/issues/3637
