### ISSUE TITLE
[BUG] Get-PnPAzureADAppSitePermission claims no permissions

### ISSUE THREAD

**Issue by timtatam** [pnp/powershell#4266] opened 2024-09-11 12:22 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Using Get-PnPAzureADAppSitePermission to get the permissions to for the current site

### Actual behavior 
I get an 'Need admin approval' to request more permissions. It was confirmed that the requested permission Sites.FullControl.All is present on the app

### Steps to reproduce behavior
1. Connect-PnPOnline -Url <URL> -ClientId <clientid> -Interactive
2. Get-PnPAzureADAppSitePermission

If I use the Graph cmdlet it works:
1. $result = Invoke-PnPGraphMethod -Url "/sites/<siteId>/permissions"
2. $permissions = Invoke-PnPGraphMethod -Url "/sites/<siteId>/permissions/$($result.value.id)"

This shows to me that it is not an actual permission issue.

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2024-09-11 12:45
Hello, can you please use the latest 2.12.0 and check ? v3 is the PnP PowerShell is not supported anymore.

**Comment by timtatam** [comment] 2024-09-11 13:26
sorry, that was a typo 🤦 
I´m using 2.12.0

**Comment by gautamdsheth** [comment] 2024-09-15 14:13
Can you try it as and check ? 

```
Get-PnPAzureADAppSitePermission -Site https://contoso.sharepoint.com/sites/projects
```

**Comment by timtatam** [comment] 2024-09-16 11:53
@gautamdsheth I do get the same error. The same is true for 'Grant-PnPAzureADAppSitePermission'

**Comment by gautamdsheth** [comment] 2024-09-28 19:02
Looks like an API limitation or something.

In the docs , it is mentioned that you need to be a site collection admin. 

https://pnp.github.io/powershell/cmdlets/Get-PnPAzureADAppSitePermission.html

If permissionId is not present, it doesn't return any roles according to the docs, maybe that must be the issue.

```
Get-PnPAzureADAppSitePermission -PermissionId TowaS50fG1zLnNwLmV4dHwxYxNmI0OTI1
```

Closing this , looks like some configuration thing. Haven't made any changes to this in the recent past.

**Closed by gautamdsheth** 2024-09-28 19:02 UTC
Labels: bug

**Comment by jhholm** [comment] 2024-09-30 07:36
Just commenthing for reference. I was running into the same issue. This is by design for now. The default permissions from **Register-PnPEntraIDAppForInteractiveLogin** is not providing delegated **Sites.FullControl.All** for Graph API. You need to add that permission manually on your app registration that you are using for interactive login. This is documented on the the cmdlet as required permissions, but can be easily overlooked.
