### ISSUE TITLE
[BUG] Get-PnPHubSiteChild Metod not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8....

### ISSUE THREAD

**Issue by ZzyzxIsAlreadyTaken** [pnp/powershell#1643] opened 2022-02-22 13:27 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Get a list of associated hub sites

### Actual behavior 
```
Get-PnPHubSiteChild : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'.
At line:1 char:1
+ Get-PnPHubSiteChild -Identity "https://contoso.sharep ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPHubSiteChild], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Admin.GetHubSiteChild
```

### Steps to reproduce behavior
VS Code 1.6.42 with PowerShell v2021.12.0
`Get-PnPHubSiteChild -Identity <hubsiteURL>`

Works in regular PowerShell window :\

### What is the version of the Cmdlet module you are running?
1.9.0

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2022-03-31 07:56
This is a duplicate of #727 , so will close this issue. Please follow that issue for updates.

Unfortunately, we don't have a fix for this . The workaround is, unfortunately, to use PowerShell outside of  VSCode :(

**Closed by gautamdsheth** 2022-03-31 07:56 UTC
Labels: bug
