### ISSUE TITLE
[BUG] Unauthorized Operation Error with PnP PowerShell Cmdlets Get-PnpTenant

### ISSUE THREAD

**Issue by prattay56** [pnp/powershell#3944] opened 2024-05-10 15:32 UTC
**Bug Report: Unauthorized Operation Error with PnP PowerShell Cmdlets**

**Description:**
When using the `Get-PnPTenant`, `Set-PnPTenant`, `Get-PnPTenantSite`, and `Set-PnPTenantSite` cmdlets, encountering an "unauthorized operation" error. This issue arises consistently across all tenants globally. 

**However it works with -interavtive (user login)**

**Error Message:**
Upon execution, the following error is thrown: "Attempted to perform an unauthorized operation." Additionally, when monitoring the network traffic with Fiddler, the error `X-MSDAVEXT_Error: 917656; Access denied. Before opening files in this location, you must first browse to the web site and select the option to login automatically.` is observed.

**Reproducibility:**
The error occurs consistently since May 9, 2024. It is reproducible on various tenants worldwide. 

**Steps to Reproduce:**
1. Execute the `Connect-PnPOnline` cmdlet with the `-ClientId` and `-ClientSecret` parameters to authenticate.
   ```powershell
   Connect-PnPOnline -Url $url -ClientId $id -ClientSecret $sec -Verbose
   ```
2. Attempt to use any of the following cmdlets: `Get-PnPTenant`, `Set-PnPTenant`, `Get-PnPTenantSite`, or `Set-PnPTenantSite`.

Permission of the app:
`<AppPermissionRequests AllowAppOnlyPolicy="true">
  <AppPermissionRequest Scope="http://sharepoint/content/sitecollection" Right="FullControl" />
  <AppPermissionRequest Scope="http://sharepoint/social/sitecollection" Right="FullControl" /> 
</AppPermissionRequests>`

**Expected Behavior:**
The cmdlets should execute without encountering unauthorized operation errors, given valid authentication credentials.

**Actual Behavior:**
The cmdlets consistently throw unauthorized operation errors, hindering their execution.

**Additional Information:**
- The error specifically occurs when using the `-ClientId` and `-ClientSecret` parameters to connect to PnP.
- Interestingly, the `Get-PnPWeb` cmdlet connects to SharePoint sites without any issues, indicating a specific problem with the tenant-related cmdlets.

**Environment:**
- PowerShell Version: [e.g., PSVersion  : 7.4.2 | PnP PowerShell Cmdlets (2.4.0)
- SharePoint Online Environment: [e.g., Office 365]
- Operating System: [e.g., Windows 11]

---

![image](https://github.com/pnp/powershell/assets/74849664/1fb3e5d0-391e-43a2-9990-3f5617e3d257)

**Comment by prattay56** [comment] 2024-05-10 15:32
Previous ticket was closed: 
https://github.com/pnp/powershell/issues/3943

**Comment by shrike94** [comment] 2024-05-10 20:14
Seeing similar issue.  
![Get-PnPTenantSite](https://github.com/pnp/powershell/assets/32710760/00a19185-3484-4183-96aa-ef520c8660cf)

**Comment by Barbarur** [comment] 2024-05-11 01:08
Have you tried to use App Certificate instead of the Secret. 

ACS authentication using secret has been deprecated in various operations and it's on the way to be fully deprecated this year.

**Comment by suhanacharya** [comment] 2024-05-11 01:31
It seemed to be some regression that's now fixed. 
Refer this:
https://github.com/SharePoint/sp-dev-docs/issues/9678#issuecomment-2105320914

**Comment by veronicageek** [comment] 2024-05-12 15:19
@prattay56 - Please DO NOT open other issues for the same problem because the other one was closed. That creates duplicates and we cannot follow all the threads into a single issue.

If there's a problem we can fix on our end, then we'll reopen the issue, otherwise we need to wait for MSFT to resolve their issues so we can automatically consume the fix.

**Closed by veronicageek** 2024-05-12 15:19 UTC
Labels: bug

**Comment by faisaleem-na** [comment] 2024-10-24 11:10
still an issue
