### ISSUE TITLE
[BUG] -OpenInNewTab parameter not working

### ISSUE THREAD

**Issue by MelvisBass** [pnp/powershell#3232] opened 2023-06-29 19:10 UTC
When adding -OpenInNewTab parameter to Add-PnPNavigationNode no errors received, and the node is added to menu but it does not have Open in new tab set.

code example:
Add-PnPNavigationNode -Title $mmTitle -Location "TopNavigationBar" -Url $mmUrl -Parent $mmParentNode -PreviousNode $mmPrevNode -AudienceIds $mmAudID -OpenInNewTab

Running on Windows 10.

**Comment by gautamdsheth** [comment] 2023-06-29 19:38
hi @MelvisBass , this is by design.

It will only work if the location is QuickLaunch and that too only for modern site collections.

Afraid we can't anything about since it is an API limitation.
Will have to close it. 
Will update the docs to better document this limitation.

**Closed by gautamdsheth** 2023-06-29 19:38 UTC
Labels: bug
