### ISSUE TITLE
[BUG] get-pnpsitescriptfromweb throws an error if you don't use one of the -include parameters

### ISSUE THREAD

**Issue by spg-iwilson** [pnp/powershell#869] opened 2021-06-29 08:23 UTC
### Reporting an Issue or Missing Feature
The get-pnpsitescriptfromweb command threw an error unless I included -IncludeAll, -IncludeBranding etc. According to the documentation, these parameters are optional

### Expected behavior 
If I use the -Lists parameter without any -Include* parameter, the command should output the JSON for the specified lists

### Actual behavior 
**PowerShell 5.1: **
```
Get-PnPSiteScriptFromWeb : Parameter set cannot be resolved using the specified named parameters.
At line:1 char:1
+ get-pnpsitescriptfromweb -url https://mytenant.sharepoint.com/sites/te ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-PnPSiteScriptFromWeb], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,PnP.PowerShell.Commands.GetSiteScriptFromWeb
```

**PowerShell 7.1:**
`Get-PnPSiteScriptFromWeb: Parameter set cannot be resolved using the specified named parameters. One or more parameters issued cannot be used together or an insufficient number of parameters were provided.`

### Steps to reproduce behavior
`get-pnpsitescriptfromweb -url https://mytenant.sharepoint.com/sites/test -Lists "MyLibrary"`

### What is the version of the Cmdlet module you are running?
1.6

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

---
The following command ran successfully:
`get-pnpsitescriptfromweb -url https://mytenant.sharepoint.com/sites/test -Lists "MyLibrary" -IncludeAll`

Also, I'm confused by the parameter -IncludeAll. I expected this to include lists and libraries. I'd suggest updating the documentation to indicate that -IncludeAll does not include lists, or changing the behaviour of the command.

**Comment by veronicageek** [comment] 2021-09-07 20:38
@spg-iwilson - Indeed, I can reproduce the problem in the latest `1.7.43`. We'll work on that.

**Comment by KoenZomers** [comment] 2021-09-30 00:16
@spg-iwilson issue has been fixed in the above referenced PR. Once this PR is merged, the following day you can get the latest prerelease to test this out. Assuming this will fix the issue you are describing, I will proceed with closing this issue. If it turns out not to be fixed, feel free to reopen.

**Closed by KoenZomers** 2021-09-30 00:16 UTC
Labels: bug, documentation, reproduced
