### ISSUE TITLE
Connection with Credential Object Fails

### ISSUE THREAD

**Issue by danmyhre** [pnp/powershell#2985] opened 2023-04-06 14:49 UTC
### Reporting an Issue or Missing Feature
When connecting with a credential object, you get an error. Using -Interactive on the same machine works fine.

### Expected behavior 
Connection would be established.  

### Actual behavior 
Connect-PnPOnline: Could not load file or assembly 'System.IdentityModel.Tokens.Jwt, Version=6.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. Could not find or load a specific file. (0x80131621)

### Steps to reproduce behavior
Connect-PnPOnline -Url:"https://tenant-admin.sharepoint.com" -Credentials (Get-Credential)

### What is the version of the Cmdlet module you are running?
2.1.1

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by danmyhre** [comment] 2023-04-06 20:52
This cmdlet also throws the same error: Get-PnPGraphAccessToken

**Comment by veronicageek** [comment] 2023-04-07 09:18
@danmyhre - Cannot reproduce the issue. Works fine on `2.2.1`

![image](https://user-images.githubusercontent.com/25181757/230582310-d76fd1c0-0522-4ab2-838d-889862ca52c8.png)

**Comment by gautamdsheth** [comment] 2023-04-12 12:06
Can't repro either , using PS 7.2.10 on Win 11.

If you have any other modules loaded, can you please remove them and try again ?
In 2.1.1 , we bumped quite a few underlying dependencies like `MSAL`, `System.IdentityModel.Tokens.Jwt` and others, maybe some other module is using an older version of these DLLs ? 

<img width="941" alt="image" src="https://user-images.githubusercontent.com/8832018/231452033-b1ceb8e6-345b-4c25-9712-f554a8d4e7dd.png">

**Comment by veronicageek** [comment] 2023-04-16 07:55
Closing as we can't repro.

**Closed by veronicageek** 2023-04-16 07:55 UTC

**Comment by danmyhre** [comment] 2023-04-18 21:25
I am on VSCode 1.77.0
PowerShell extension v2023.3.3

**Comment by veronicageek** [comment] 2023-04-19 08:17
@danmyhre - Those would be external dependencies that we cannot control and won't be troubleshooting VSCode nor the PowerShell Extension.

I've still done the test and again it works fine here with PowerShell Extension `v2023.3.3` and VSCode `1.77.3`

![image](https://user-images.githubusercontent.com/25181757/233012625-a8da81ab-ff95-4d0d-a636-4d9705a5aad5.png)
