### ISSUE TITLE
[BUG] 'Connect-PnPOnline -credentials $credential' Not Working For set-pnpuserprofileproperty cmdlet

### ISSUE THREAD

**Issue by dbfithen** [pnp/powershell#1396] opened 2021-11-29 17:09 UTC
### Reporting an Issue or Missing Feature
Using the following cmdlets with Connect-PnPOnline, connecting with the same account, only succeeds when using the '-UseWebLogin' parameter.  No CA policies or MFA policies are restricting access to the account, and the credentials are stored directly from 'get-credential'

The account connecting to PnPOnline has the Sharepoint Administrator role.

-----------

$credential = get-credential
Connect-PnPOnline -url https://contoso.sharepoint.com/ -Credentials $credential
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

>>set-pnpuserprofileproperty : This operation requires you to be managing your own data or have administrator privileges.

-----------

Connect-PnPOnline -url https://contoso.sharepoint.com/ -Interactive
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

>>set-pnpuserprofileproperty : This operation requires you to be managing your own data or have administrator privileges.

------------

Connect-PnPOnline -url https://contoso.sharepoint.com/ -UseWebLogin
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

>>Property set as expected

-----------

Example:

![image](https://user-images.githubusercontent.com/44844670/143911531-462783e0-8111-4720-ac2c-966f38e2af35.png)

### Expected behavior 

Connect-PnPOnline -url https://contoso.sharepoint.com/ -Credentials $credential
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

>>Property set as expected

### Actual behavior 

$credential = get-credential
Connect-PnPOnline -url https://contoso.sharepoint.com/ -Credentials $credential
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

>>set-pnpuserprofileproperty : This operation requires you to be managing your own data or have administrator privileges.

![image](https://user-images.githubusercontent.com/44844670/143911531-462783e0-8111-4720-ac2c-966f38e2af35.png)

### Steps to reproduce behavior

Using account with the Sharepoint administrator role with no MFA/CA policies applied, running PnPOnline Module 1.8.0, run the following cmdlets modified for your SPO tenant:

$credential = get-credential
Connect-PnPOnline -url https://contoso.sharepoint.com/ -Credentials $credential
set-pnpuserprofileproperty -Account janedoe@contoso.com -PropertyName "isactive" -Value $false

### What is the version of the Cmdlet module you are running?
1.8.0

![image](https://user-images.githubusercontent.com/44844670/143911913-4fb14655-887d-4c75-86ec-37ae5f5a661c.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2021-11-30 06:01
Going to close this as it is a duplicate of this issue https://github.com/pnp/powershell/issues/277

Please check the linked issue for a workaround.

**Closed by gautamdsheth** 2021-11-30 06:01 UTC
Labels: bug
