### ISSUE TITLE
[BUG] Set-PnPPage translation a full width section page

### ISSUE THREAD

**Issue by TycoMoon** [pnp/powershell#4382] opened 2024-10-04 15:19 UTC
### Reporting an Issue or Missing Feature

Issue: `Set-PnPPage` cmdlet error when trying to translate a page with a full width section.

### Expected behavior 

I expect the `Set-PnPPage` cmdlet to successfully copy the translated page without errors.

### Actual behavior 

When running the command:
```powershell
Set-PnPPage -Identity "Yo.aspx" -Translate -TranslationLanguageCodes 1036 -LayoutType "Article"
```
I receive the following error:
```
2024-10-04T14:23:15Z   [Error]   ERROR: You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed

Exception             : 
    Type        : System.Management.Automation.PSInvalidOperationException
    ErrorRecord : 
        Exception             : 
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed
            HResult : -2146233087
        CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : InvalidOperation
    TargetSite  : 
        Name          : ProcessRecord
        DeclaringType : [PnP.PowerShell.Commands.Base.PnPConnectedCmdlet]
        MemberType    : Method
        Module        : PnP.PowerShell.dll
    Message     : You cannot host text controls inside a one column full width section, only an image web part or hero web part are allowed
    Source      : PnP.PowerShell
    HResult     : -2146233079
    StackTrace  : 
   at PnP.PowerShell.Commands.Base.PnPConnectedCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPConnectedCmdlet.cs:line 101
   at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 126
   at System.Management.Automation.Cmdlet.DoProcessRecord()
   at System.Management.Automation.CommandProcessor.ProcessRecord()
CategoryInfo          : InvalidOperation: (:) [Set-PnPPage], PSInvalidOperationException
FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Pages.SetPage
InvocationInfo        : 
    MyCommand        : Set-PnPPage
    ScriptLineNumber : 107
    OffsetInLine     : 5
    HistoryId        : 1
    ScriptName       : C:\home\site\wwwroot\translation\run.ps1
    Line             :     Set-PnPPage -Identity $pageName -Translate -TranslationLanguageCodes $lcid -LayoutType $pageSource.LayoutType

    Statement        : Set-PnPPage -Identity $pageName -Translate -TranslationLanguageCodes $lcid -LayoutType $pageSource.LayoutType
    PositionMessage  : At C:\home\site\wwwroot\translation\run.ps1:107 char:5
                       +     Set-PnPPage -Identity $pageName -Translate -TranslationLanguageCo …
                       +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    PSScriptRoot     : C:\home\site\wwwroot\translation
    PSCommandPath    : C:\home\site\wwwroot\translation\run.ps1
    InvocationName   : Set-PnPPage
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, C:\home\site\wwwroot\translation\run.ps1: line 107
```

Despite using only an image in the full width section.

### Steps to reproduce behavior

1. Create a page in a site with translation enabled in any language.
2. Create a full width section and add an image WebPart in it.
3. Attempt to translate the page using the following command:
```powershell
Set-PnPPage -Identity "yourpage.aspx" -Translate -TranslationLanguageCodes 1036 -LayoutType "Article"
```
### Error Message
```

```
### What is the version of the Cmdlet module you are running?

"2.99.2-nightly" (also tried "1.12.0")

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [X] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment] 2024-10-04 20:47
This is the stacktrace:
>at PnP.Core.Model.SharePoint.PageWebPart.ToHtml(Single controlIndex)
at PnP.Core.Model.SharePoint.CanvasColumn.ToHtml()
at PnP.Core.Model.SharePoint.CanvasSection.ToHtml()
at PnP.Core.Model.SharePoint.Page.ToHtml()
at PnP.Core.Model.SharePoint.Page.SaveAsync(String pageName)
at PnP.Core.Model.SharePoint.Page.Save(String pageName)
at PnP.PowerShell.Commands.Pages.SetPage.ExecuteCmdlet() in PnP\powershell\src\Commands\Pages\SetPage.cs:line 152

So the issue is more related to PnP.Core than PnP.PowerShell by the look of it.

**Comment by jackpoz** [comment] 2024-10-04 21:46
It seems that image webpart is missing the `isFullWidth` property somehow. See below how `properties.TryGetProperty("isFullWidth", ...)` returned false:
![image](https://github.com/user-attachments/assets/cbb8fe94-29da-4d19-b558-8b14e55b0a94)

**Comment by TycoMoon** [comment] 2024-10-07 08:59
Thank you !It would be great if we could fix/disable this condition. I'm having trouble dodging this bug on my end. 😄

**Comment by jackpoz** [comment] 2024-12-23 21:01
Tried with 2.99.80 and it works correctly without throwing any error anymore:
![image](https://github.com/user-attachments/assets/24eaf114-7d5c-4889-8585-7307ad7d7f8e)

Given a page at /SitePages/Test.aspx , it created /SitePages/sv/Test.aspx when running `Set-PnPPage -Identity "Test.aspx" -Translate -TranslationLanguageCodes 1053 -LayoutType "Article"`

**Comment by gautamdsheth** [comment] 2024-12-25 14:13
Thanks @jackpoz for confirming the fix, going to close this as it has been fixed in the latest nightly builds.

**Closed by gautamdsheth** 2024-12-25 14:13 UTC
Labels: bug
