### ISSUE TITLE
[BUG]Restore-PnPRecycleBinItem: The Attempted operation is prohibited because it exceeds the list view threshold

### ISSUE THREAD

**Issue by soumyadeep22** [pnp/powershell#3491] opened 2023-10-12 23:35 UTC
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. Restore-PnPRecycleBinItem -Identity GUID -Force does not work for a single item. Throws "The Attempted operation is prohibited because it exceeds the list view threshold"
1. **It seems  the issue related to the cmdlet itself, 

### Expected behavior 
It should restore the item from recycle bin to original location

### Actual behavior 
Throws "The Attempted operation is prohibited because it exceeds the list view threshold"
Restore-PnPRecycleBinItem : The attempted operation is prohibited because it exceeds the list view threshold.
At Powershell\RestoreFromRecycleBin.ps1:7 char:12
+ $restore | Restore-PnPRecycleBinItem -Force
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Restore-PnPRecycleBinItem], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.RecycleBin.RestoreRecycleBinItem
### Steps to reproduce behavior

Connect-PnPOnline -Url https://abc.sharepoint.com/sites/xyz
$restore = Get-PnPRecycleBinItem -RowLimit 500000 | Where {($_.DeletedByEmail -eq $DeletedByEmail)} 

$restore | Restore-PnPRecycleBinItem -Force

--this is also not working--, tried below also to loop through each item

foreach ($r in $restore) {
$id = $r.Id.GUID
Restore-PnPRecycleBinItem -Identity $id -Force
}
### What is the version of the Cmdlet module you are running?

1.12
### Which operating system/environment are you running PnP PowerShell on?
- Windows
- 

Regards,
Soumyadeep

**Comment by gautamdsheth** [comment] 2023-10-13 05:42
Closing as duplicate of https://github.com/pnp/powershell/issues/3382

check the comments there for possible workaround

**Closed by gautamdsheth** 2023-10-13 05:42 UTC
Labels: bug
