### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by NewReactUser28** [pnp/powershell#675] opened 2021-05-12 05:11 UTC
Hi, 

We have been trying to hide OOTB Search on pages using Set-PnPSearchSettings in SPO Modern site.

We are using the below script.

#Script to hide search box in modern sites
#Enter Target Site URL
$SiteURL = ""
Connect-PnPOnline -Url $SiteURL -UseWebLogin
try{
 $web = Get-PnPWeb
 #0 - Inherit, #1 - AllPages, #2 - ModernOnly, #3 - Hidden enums for Global (Modern Search)
 $web.SearchBoxInNavBar=3
 $web.Update()
 Invoke-PnPQuery
 Write-Host "Done" -BackgroundColor Green  
}
catch{
 Write-Host "No permission" -BackgroundColor Red   
}
Write-Host "All Done"

We have also tried with the below script:
#Script to hide search box in modern sites
#Enter Target Site URL
$SiteURL = ""
Connect-PnPOnline -Url $SiteURL -UseWebLogin

Set-PnPSearchSettings -SearchBoxInNavBar Hidden -Scope Web -Force 

![SearchSettings](https://user-images.githubusercontent.com/80849954/117921318-2b29b600-b30e-11eb-90b5-e514e08fa8a7.JPG)
When we try to retrieve the search settings, we see the OOTB search is hidden. 
However it is still appearing in our site.

**Comment by wobba** [comment] 2021-05-18 08:51
If you in a new browser windows with clear cache (e.g. private mode) is still seeing the search box in the navigation bar, then this should be logged as a bug with Microsoft.

**Comment by wobba** [comment] 2021-05-18 09:33
I have repro and will log it internally.

**Comment by wobba** [comment] 2021-05-21 07:55
The issue is being worked on but don't have an ETA. I'll close this issue as the cmdlet is working as expected - it's the page which don't read the setting correctly.

**Closed by wobba** 2021-05-21 07:55 UTC
Labels: bug
