### ISSUE TITLE
[BUG] Clear-PnPDefaultColumnValues does not work for Managed Metadata/Taxonomy fields

### ISSUE THREAD

**Issue by paropstad** [pnp/powershell#1110] opened 2021-09-15 14:24 UTC
### Reporting an Issue 
I am reporting an issue/Bug when using the 'Clear-PnPDefaultColumnValues' on a Managed Metadata fieldtype.

### Expected behavior 
I expected the cmdlet to remove any default column values for the specified column on the specified document library.

### Actual behavior 
The cmdlet returns an error stating that "object reference not set to an instance of an object". The cmdlet works for other field types, but not for type "Managed metadata".

**Example of output:**

```
Clear-PnPDefaultColumnValues : object reference not set to an instance of an object.
At line:1 char:16
+ ... earvalues = Clear-PnPDefaultColumnValues -List 'SitePages' -Field 'pu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Clear-PnPDefaultColumnValues], NullReferenceException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Lists.ClearDefaultColumnValues
```

### Steps to reproduce behavior
1. Create a standard SharePoint Communication site
2. Add the enterprise keyword column (TaxKeyword) to the Site Pages library (or create a new Managed metadata site column and add that to the site pages library)
3. Go to Library settings and open Column default value settings
4. Set a default value for your Managed metadata column using either GUI or Set-PnPDefaultColumnValues
5. Try to remove the values using 'Clear-PnPDefaultColumnValues' (see example script below)

```
Import-Module PnP.PowerShell

$pnpconn = Connect-PnPOnline -Url "https://testtenant.sharepoint.com/sites/testsite" -UseWebLogin -ReturnConnection

$clearvalues = Clear-PnPDefaultColumnValues -List 'Site Pages' -Field 'TaxKeyword' -Connection $pnpconn
```

**Default values as seen from GUI or Get-PnPDefaultColumnValues':**
![image](https://user-images.githubusercontent.com/90777709/133450746-ce39d1cd-2b57-4662-813c-9ea5ac99aa46.png)
![image](https://user-images.githubusercontent.com/90777709/133450981-fc4aeb01-2f6f-4ab5-af67-5115b4d78223.png)

**Error message when trying to remove values using 'Clear-PnPDefaultColumnValues':**
![image](https://user-images.githubusercontent.com/90777709/133451394-a82c6583-6d86-49f6-b5cf-050ce9619e4b.png)

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.5.0
(also tested on 1.7.0 in Azure Automation with same result)

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Azure automation

**Comment by paropstad** [comment] 2021-09-16 12:39
After some more testing it also looks like the Clear-PnPDefaultColumnValues only works when there are more then one column with default value set on the library.
Meaning that if there is only one column where default values have been set - the cmdlet will go through without any errors - but it will actually not do anything.

This can be easily testet if you add more columns to the site pages library, but only set default values for one of them. Then try to remove those values using 'Clear-PnPDefaultColumnValues'. Nothing happens.
Then you set default values for at least one more column and try the 'Clear-PnPDefaultColumnValues' again. This time it will remove the default values for the specified column.

**Comment by CallumCrowley** [comment] 2021-10-20 14:01
@paropstad thanks for the update!

It seems this [issue](https://github.com/pnp/PnP-PowerShell/issues/1978) has existed for quite a while now. I'm presuming the problem is related to how PnP PowerShell clears columns. Clearing managed metadata columns isn't as straightforward as clearing other columns and has been discussed on a lot of [forums](https://sharepoint.stackexchange.com/questions/7009/nulling-clearing-updating-managed-metadata-taxonomyfieldvalue).

**Comment by zumiek** [comment] 2022-01-13 13:35
STILL an issue when trying to clear a taxonomy field.
I have tried internal name, Id, field reference object and still get:
"Clear-PnPDefaultColumnValues: Object reference not set to an instance of an object."
Running PnP.PowerShell 1.9.0 / PowerShell 7.2

**Comment by jackpoz** [comment] 2022-01-14 13:47
I'm working on a fix for this issue and will open a PR in the next days

**Closed** 2022-02-07 07:02 UTC
Labels: bug
