### ISSUE TITLE
[BUG] Set-PnPLabel [Access denied]

### ISSUE THREAD

**Issue by dimitargeorgievmitev** [pnp/powershell#2129] opened 2022-07-11 13:35 UTC
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Set-PnPLabel stopped working since the beginning of July with error related to permissions for
all sites, all labels we have published, it just errors out with Access Denied. Same operation works
from the UI with the same account. Get-PnPLabel works properly as well returning the available
labels.

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

Expected is that the label would be applied as default on the document library, PowerShell
does not return output on success for this command.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

Set-PnPLabel : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At line:1 char:1
+ Set-PnPLabel -list "Audit Logs" -Label "Audit Log Retention Label ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-PnPLabel], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.InformationManagement.SetLabel

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

Connect-PnPOnline "https://xxx.sharepoint.com/sites/xxxx"
Set-PnPLabel -list "Audit Logs" -Label "Audit Log Retention Label" 

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.11.0     PnP.PowerShell  
### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by dimitargeorgievmitev** [comment] 2022-07-15 08:04
Tested same with latest version of CSOM, same behavior:

[Microsoft.SharePoint.Client.CompliancePolicy.SPPolicyStoreProxy]::SetListComplianceTag($context,$listUrl,$nameOfPolicy,$false,$false,$false)
$context.ExecuteQuery()

Exception calling "ExecuteQuery" with "0" argument(s): "Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))"
At C:\Temp\SharePoint\TestApplyTag.ps1:55 char:1
+ $context.ExecuteQuery()
+ ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ServerUnauthorizedAccessException

**Comment by dimitargeorgievmitev** [comment] 2022-07-15 09:51
On Dev tenant I was able to apply label if I grant Global Admin role to the executing user, the error returns as soon as I removed it. There must be underlying change on the backend to require Global Admin for some reason.

**Comment by dimitargeorgievmitev** [comment] 2022-07-15 12:02
Found culprit to be the legacy Compliance Policy Center site, for some reason the code checks against it for access and only Global Admin is in there by default, you can modify it with SPO Management shell to include the accounts you need. Maybe you can add the dependency in the commandlet help file to show there is such dependency.

**Comment by greenblackfrog** [comment] 2022-07-21 16:58
> 

Having the same issue, would you be able to elaborate please with the commands you used in the SPO Management shell to resolve this?

**Comment by dimitargeorgievmitev** [comment] 2022-07-21 20:15
Install-UnifiedCompliancePrerequisite, we were missing the site, test with load only key first. Once you have it add the users you need as admins on the site collection, and the commandlet should start working.

**Comment by greenblackfrog** [comment] 2022-07-22 13:02
> 

Thanks, I've connected ok and run -loadonly
to make the change did you change the owner? -PolicyCenterSiteOwner

**Comment by dimitargeorgievmitev** [comment] 2022-07-22 13:17
I got the site url and browsed it, it is a Sharepoint site, so I just added the group I needed as admin on it.

**Comment by greenblackfrog** [comment] 2022-07-22 13:33
> legacy Compliance Policy Center site

Great, thank you.
Think I'd also just solved it by adding the Compliance Administrator role in PIM

**Comment by gautamdsheth** [comment] 2022-08-23 15:09
Closing as not a bug, seems like an issue with the permissions and nothing to do with the cmdlets

**Closed** 2022-08-23 15:09 UTC
Labels: bug
