### ISSUE TITLE
[FEATURE] Make it possible to Update Fields, Content Types and Lists

### ISSUE THREAD

**Issue by PerOve** [pnp/powershell#2318] opened 2022-09-05 11:12 UTC
**Is your feature request related to a problem? Please describe.**

The problem is: It is not possible to update site columns, content-types and lists using Invoke-SiteTemplate

I am frustrated when I want to update a site with new site columns, content types and Lists. If a site column already exist, Invoke-PnPSiteTemplate fails. 
I can provision to a new site, but then I do not get the data in the list in the existing site.

I am working with ALM on Power Platform projects using SharePoint Lists as the storage. 
On a DEV site, I create Lists holding the data. 
I use Site Content Types (Not from the Content Type HUB). We do not want to mess up the HUB with our experiments.
And of course I use Site Columns (Fields) in the Content Types.

A User-Acceptance (UA) site is used to test the solutions by Users.
I provision the DEV site to the UA site. All fine the first time.
After a while users have been filling up the lists with their test data. And they have used a lot off effort getting the data into these lists.

After a while developing, new columns, content-types and lists must be added to the UA site.
And changes to existing Content-types, columns and list must also be applied.
This is ongoing work, so we want to implement it into Azure DevOps running PnP PowerShell.

**Describe the solution you'd like**
I want to be able to use some kind of parameter to specify what I want to overwrite.
I also would like to have a filter for Fields, like: -FieldGroupsToInclude, similar to the parameter -ContentTypeGroups
`
$sourceTemplate = Get-PnPSiteTemplate -OutputInstance -Connection $pnpSourceConnection -Handlers Fields,ContentTypes,Lists
Invoke-PnPSiteTemplate -InputInstance $sourceTemplate -Connection $pnpTargetConnection -OverwriteHandlers ["Fields","ContentTypes","Lists"]

`

**Describe alternatives you've considered**
I have created my own scripts using PnP PowerShell cmdlets, using Get-PnPField, Get-PnPContentType and Get-PnP-List.
Then I filter them using group names so only the ones my team has created is stored in a variable.
Then I test the target Site for existing fields, content-types and lists, and I group them by "Create, Update and Delete".
Then my script can create the new ones, update the existing ones and even delete obsolete ones.

**Comment by CallumCrowley** [comment] 2022-09-05 13:56
When you say update columns, do you mean update the internal field name as well?

**Comment by PerOve** [comment] 2022-09-05 18:08
No. Internal names should stay the same.

Per Ove
________________________________

**Comment by CallumCrowley** [comment] 2022-09-06 09:36
@PerOve since Invoke-PnPSiteTemplate relies on the [PnP.Framework](https://github.com/pnp/pnpframework) to apply provisioning templates to sites, the requested enhancements would need to be completed on that project (rather than the PnP.PowerShell project).

**Comment by PerOve** [comment] 2022-09-07 05:10
@CallumCrowley Thanks for looking into this request! :)

Still: I am not sure, yet,  if it is impossible without updating the framework. 
The cmdlet Set-PnPField can update Site Columns. Is this not based on the same framework?

If not:
I would wish it should be possible to continue with the template provisioning when there is existing columns, content-types or Lists, by skipping them and try the next one.

**Comment by CallumCrowley** [comment] 2022-09-07 08:46
@PerOve the two cmdlets are different. Invoke-PnPSiteTemplate simply calls the PnP provisioning engine which is part of the PnP.Framework project, rather than PnP.PowerShell itself. See the [code](https://github.com/pnp/powershell/blob/6eef6dbc55a15b58dff2bffb2957ed64d9ada287/src/Commands/Provisioning/Site/InvokeSiteTemplate.cs#L327) itself for more information.

[Set-PnPField](https://github.com/pnp/powershell/blob/dev/src/Commands/Fields/SetField.cs) is very different in this regard, as it doesn't utilise the PnP provisioning engine.

**Comment by PerOve** [comment] 2022-09-07 11:23
@CallumCrowley Thank you for the explanation. 
My understanding now is that Set-PnPField does not use the PnP.Framework but the SharePoint.Client.

Invoke-PnPSiteTemplate, do use PnP.Framework.
And PnP.Framework, cannot at this time handle changes to Columns, nor can it be asked to continue with the next column if it already exist.

To make it do so, PnP.Framework will need to be modified.
Is this correct?

**Comment by CallumCrowley** [comment] 2022-09-07 11:45
@PerOve yes, the provisioning engine is part of PnP.Framework, so that would need to be updated to achieve the enhancements that you are requesting.

**Comment by CallumCrowley** [comment] 2022-09-07 14:52
@PerOve can this issue be closed, since I think you've now created a request on the PnP.Framework project?

@gautamdsheth

**Comment by gautamdsheth** [comment] 2022-09-15 19:10
Thanks @CallumCrowley for looking into this !
Will close the issue here as it belongs to PnP Framework repo.

Looking at this issue @PerOve , its not really clear what the issue is. 
PnP provisioning does exactly that. It creates a new column/CT/List if not doesn't exist. It will update the existing column/CT/List if it is already present.

**Closed by gautamdsheth** 2022-09-15 19:10 UTC
Labels: enhancement

**Comment by PerOve** [comment] 2022-09-16 05:45
If this is how it should work, then there is an issue since it doesn't work in my environment. 🙂
