### ISSUE TITLE
[BUG] Running the Get-PnPTenantSite -Detailed cmdlet does not display the actual value of keys

### ISSUE THREAD

**Issue by SjoerdV** [pnp/powershell#1739] opened 2022-03-31 21:15 UTC
### Reporting an Issue or Missing Feature
This is actually the same issue, that was/is present on the legacy module 
https://github.com/pnp/PnP-PowerShell/issues/2596
https://github.com/pnp/PnP-PowerShell/issues/2598

Running ```Get-PnPTenantSite -Detailed``` gives wrong values for site property keys. When you run the command focused on a single site ```Get-PnPTenantSite -Identity https://... -Detailed```, the results are correct.

### Expected behavior 
I would expect the ```Get-PnPTenantSite -Detailed``` command to show actual values of properties of all sites in scope.

### Actual behavior 
Instead the command seems to 'guess' at property values, so it is not clear that the returned values are actually incorrect. If the actual issue cannot be fixed I would prefer to have the command not output anything for properties like 'DefaultSharingLinkType' and 'DisableCompanyWideSharingLinks' (these are just examples, much more properties are returned incorrectly) as returning incorrect results is worse than returning nothing.

### Steps to reproduce behavior
Just run the command without Identity parameter and compare output to the command with an Identity parameter. 

### What is the version of the Cmdlet module you are running?
1.8.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by PowerBugi** [comment] 2022-06-15 09:08
Hello @SjoerdV and thank you for this report.

I was also going to open an issue about this as well.

I need to run this kind of filter :
```powershell
$Sites = Get-PnPTenantSite -Detailed | Where-Object {
    ($_.DefaultLinkToExistingAccess -eq $false)
}
```

But i can't because, it's useless since the property "DefaultLinkToExistingAccess" return false for ALL sites in my tenant... While this is not the case.

As you said, if we run the command site by site, the result is correct at that time.

It's really disabling when you want to make a filter on all the sites in order to do reporting.

Is there a workaround in the meantime ? Without making a `Get-PnPTenantSite -Detailed | Foreach-Object {Get-PnPTenantSite -Identity $_}` ?

**Comment by PowerBugi** [comment] 2022-06-15 09:17
I think it that's the because of the SharePoint REST/API bug : https://github.com/SharePoint/sp-dev-docs/issues/8012

**Comment by SjoerdV** [comment] 2022-06-15 10:46
> I think it come from the SharePoint REST/API bug : https://github.com/SharePoint/sp-dev-docs/issues/8012

That's a great find! I sure hope someone in the PnP Team can forward this to the right MS team, when appropriate. On the other hand, maybe investing in the Graph API to deliver these properties might be a better bet IMHO.

**Comment by PowerBugi** [comment] 2022-06-16 10:40
I try using the PowerShell SDK or pure Graph API call, but currently I can't get the properties we are looking for.
Some docs if you want to try...

Graph API : 
- [Search Sites](https://docs.microsoft.com/en-us/graph/api/site-search?view=graph-rest-1.0&tabs=http)
- [Get Site Settings (beta)](https://docs.microsoft.com/en-us/graph/api/sitesettings-get?view=graph-rest-beta&tabs=http)

With PowerShell, you can use something like this to reproduce the API with the SDK : 
```powershell
Connect-MgGraph -Scopes Sites.Read.All, Sites.ReadWrite.All
Select-MgProfile -Name "beta"

$sites = Get-MgSite -Search "TEST"
$settings = Invoke-MgGraphRequest -Method GET -Uri "/beta/sites/$($sites[0].Id)/settings"
```

But, my conclusion currently is that Graph cannot give the properties we need, even in beta... I can only get "Language, TimeZone, URL...", not usefull in our case, sadly.

**Comment by SjoerdV** [comment] 2022-06-16 11:50
Yeah, having some property exposure 'parity' between the API's would be nice. 

Same goes for the properties of a 'Team'. I really love the properties the EXOv2 cmdlet for Get-UnifiedGroup is pooping out, especially getting the Urls for all connected services (site, team, mailbox, calendar, etc). Can't have that with Graph at this point.

**Comment by gautamdsheth** [comment] 2022-09-16 20:55
hi @SjoerdV / @PowerBugi - as you all rightly found out, the issue lies at the API level. Would request you to also raise a support ticket with Microsoft about. Unfortunately, we wont be able to do anything from our side here as we are simply consuming the response.

Once Microsoft fixes it, maybe via API or update of CSOM SDk, it will be automatically available here since we always use the latest CSOM SDK in our code.
Will close the issue here as we wont be able to fix it.

You have opened the issue at the correct location , sp-dev-docs, but for added measure would also suggest that you open a Microsoft ticket or a premium ticket if possible so that Product group is aware of this.

**Closed by gautamdsheth** 2022-09-16 20:55 UTC
Labels: bug

**Comment by GeoffOrlebeck** [comment] 2022-12-22 20:21
Submitted request via SharePoint's Feedback portal here: https://feedbackportal.microsoft.com/feedback/idea/92bcc9df-3582-ed11-a81b-6045bdaf6a9e
