### ISSUE TITLE
Set-PnPTenantSite Not setting value for StorageQuotaWarningLevel

### ISSUE THREAD

**Issue by NikCharlebois** [pnp/powershell#795] opened 2021-06-14 16:39 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
```Set-PnPTenantSite -StorageQuotaWarningLevel 11111100 -Identity <url>``` should set the warning level for the site.

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Run
```Set-PnPTenantSite -StorageQuotaWarningLevel 11111100 -Identity <url>```

Then use Get-PnPTenantSite to review the properties, the value of StorageQuotaWarningLevel remains unchanged.

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [- ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2021-06-20 18:08
@NikCharlebois - No issue on my side with `1.6.0`. Can you try again?

![image](https://user-images.githubusercontent.com/25181757/122684004-dc1f4c80-d1fa-11eb-991b-b084da44bdb1.png)

**Comment by NikCharlebois** [comment] 2021-06-21 10:58
Definitively not working for me with 1.6.0...
![image](https://user-images.githubusercontent.com/2547149/122751708-1b32b980-d25e-11eb-9f46-5deee6952be5.png)
I will continue my investigation

**Comment by NikCharlebois** [comment] 2021-07-05 17:48
Just to be clear, was there a fix submitted for this since it is now closed? This is still a blocking issue for the Microsoft365DSC project and we are waiting for a solution. I am able to replicate this on every one of my test tenants. Can we please re-open the issue. Thanks

**Comment by veronicageek** [comment] 2021-07-05 18:09
We removed the `no-issue-activity` automation for the holiday period, so I've closed it manually. As far as I can see, you were "continuing your investigation". 

>was there a fix submitted for this

While testing I had no issue. If we can't reproduce your issue, we can't see what's happening on your side.
Is there anything particular about your test tenants? Can you try on a non-test one?

**Comment by NikCharlebois** [comment] 2021-07-05 18:30
Ok thanks for the update. I should have updated the thread earlier. My investigations did not unveil anything. We have tried against various types of tenants (demo, sponsored, prod, etc.) and all of them exhibit the exact same behavior. I just created a brand new prod tenant (E5) as a test to validate the issue and am able to replicate it on every site.
![image](https://user-images.githubusercontent.com/2547149/124508224-7a83e400-dd9d-11eb-9bdb-155204ca2308.png)

**Comment by NikCharlebois** [comment] 2021-07-08 17:13
Can we please re-open this issue as it is still a blocker, still occurring across multiple tenants, and we are able to repro on demand. Thanks

Adding /@SebastienLevert for visibility

**Comment by KoenZomers** [comment] 2021-07-15 11:40
Works well for me too

![image](https://user-images.githubusercontent.com/5940670/125782133-62013029-3e5e-49c6-afbf-6a7034208530.png)

@NikCharlebois Are you experiencing the same when using the SPO PowerShell Module? In PnP we really just directly pass this on to CSOM, so there's nothing PnP does to it. Feels like a server side issue.

Could it perhaps play a role that you do not have manual storage assignment set on your tenant?

**Comment by NikCharlebois** [comment] 2021-07-15 11:58
Thanks Koen,

I was able to replicate with the SPO MS. The issue was indeed with the automatic storage limits. The moment I switched out tenant to manual, then both the SPO MS and PnP cmdlets started working the way I intended them to. Thanks for your help, we can now close the issue!

***@***.***D7794F.37D03C10]
Nik Charlebois
Senior Program Manager - Microsoft Graph
Principal Lead - Microsoft365DSC<https://github.com/Microsoft/Microsoft365DSC>
613-790-2331


From: Koen Zomers ***@***.***>
Sent: Thursday, July 15, 2021 7:41 AM
To: pnp/powershell ***@***.***>
Cc: Nik Charlebois ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [pnp/powershell] Set-PnPTenantSite Not setting value for StorageQuotaWarningLevel (#795)


Works well for me too

[image]<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F5940670%2F125782133-62013029-3e5e-49c6-afbf-6a7034208530.png&data=04%7C01%7CNik.Charlebois%40microsoft.com%7C8bce3f0a2553465a249e08d947855df6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619460449388390%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5WJbolRDhz3f%2F2mkU%2FKQ3%2FCdUkEUy677SYEYDsKqkVk%3D&reserved=0>

@NikCharlebois<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNikCharlebois&data=04%7C01%7CNik.Charlebois%40microsoft.com%7C8bce3f0a2553465a249e08d947855df6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637619460449398388%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=eF3XAeQIHzz84y0UaRRB%2F6YhR%2FeqnRmn3O0Flas7eqk%3D&reserved=0> Are you experiencing the same when using the SPO PowerShell Module? In PnP we really just directly pass this on to CSOM, so there's nothing PnP does to it. Feels like a server side issue.

Could it perhaps play a role that you do not have manual storage assignment set on your tenant?

-

**Closed** 2021-07-15 13:14 UTC
