### ISSUE TITLE
Restore-PnPRecycleBinItem: -All invalid parameter

### ISSUE THREAD

**Issue by wmadm90** [pnp/powershell#273] opened 2021-02-14 19:26 UTC
error message indicates that -All is not a valid parameter, even though it's documented here as an example: https://github.com/pnp/powershell/blob/dev/documentation/Restore-PnPRecycleBinItem.md

unsure if this is an error in documentation or the code?

**Comment by bhishma** [comment] 2021-02-14 21:03
Looks like the documentation (example 3) needs to be updated.
If you'd like to  restore all items, you can omit  rowlimit.
Just `Restore-PnPRecycleBinItem` will give you what you need.

**Comment by LeonArmston** [comment] 2021-02-15 10:14
I raised a [PR](https://github.com/pnp/powershell/pull/278) for this to update the documentation and ask what the intended behaviour is regarding using Restore-PnPRecycleBinItem on it's own as currently the -identity parameter is mandatory.

**Comment by erwinvanhunen** [comment] 2021-02-15 17:07
The documentation has been updated, thank you @LeonArmston ! I will close this issue now.

**Closed by erwinvanhunen** 2021-02-15 17:07 UTC
