### ISSUE TITLE
Using Managed Identity in Azure Automation Runbook to connect to SharePoint Online

### ISSUE THREAD

**Issue by joostvdlinden** [pnp/powershell#2568] opened 2022-11-18 12:10 UTC
### Discussed in https://github.com/pnp/powershell/discussions/2559

<div type='discussions-op-text'>

<sup>Originally posted by **joostvdlinden** November 16, 2022</sup>
Hi folks,

I am trying to connect to SharePoint Online from within an Azure Automation Runbook using a system assigned managed identity.
I noticed that 6 days ago a new release of pnp has been published, which includes the remark "_Added system assigned Managed Identity support for SharePoint Online cmdlets. https://github.com/pnp/powershell/pull/2354_"

Well I have been trying to use this feature for a couple of days now, but somehow I am not able to make it work.
I have enabled the system assigned identity on the 'Identity' tab of the Automation Account. Next, I have assigned permissions to the Enterprise application which had been created automatically by enabling the managed identity. Currently I have assigned the following permissions:

- Microsoft Graph - Group.Read.All | Application type
- Microsoft Graph - User.Read.All | Application type
- Microsoft Graph - Sites.FullControl.All | Application type
- Office 365 SharePoint Online - Sites.FullControl.All | Application type

Eventually I want to limit it down to the least permissive permission level.

So what I want to achieve is that I can connect to any random SharePoint site collection and perform the Rename-PnPTenantSite cmdlet.

When I try the script below (just for testing purposes), I get the error: **Unable to connect to the SharePoint Online Admin Center at 'https://orgname-admin.sharepoint.com' to run this cmdlet. Please ensure you pass in the correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl and you have access to it. Error message: The remote server returned an error: (401) Unauthorized..**

```
Connect-PnPOnline -Url orgname.sharepoint.com -ManagedIdentity

Get-PnPTenantSite -Identity "https://orgname.sharepoint.com/sites/TestSite"

Disconnect-PnPOnline
```

When I try the script below (just for testing purposes), I get the error: **Suspended
The runbook job was attempted 3 times, but it failed each time.  Common reasons that runbook jobs fail can be found here:  https://docs.microsoft.com/en-us/azure/automation/automation-troubleshooting-automation-errors**

```
Connect-PnPOnline -Url "https://orgname.sharepoint.com/sites/TestSite" -ManagedIdentity

Get-PnPSite

Disconnect-PnPOnline
```

Can someone help me figure out what I'm doing wrong here?

Thanks for all help provided!</div>

**Comment by ScaryTerry177** [comment] 2022-11-21 17:28
Same exact issue here.

**Comment by joostvdlinden** [comment] 2022-12-05 12:03
Hi @lukju still no solution yet, unfortunately.

**Comment by dremillard** [comment] 2022-12-13 12:43
I have a similar (but different) issue connecting from a runbook using AppID and Cert thumbprint.  Noticed it around the same timeframe as this issue.  Wonder if there's any connection?  My issue is described in discussion #2585

**Comment by davem365** [comment] 2022-12-20 08:01
same issue here..

**Comment by GnXeyTfY7zBWhzUw** [comment] 2023-01-17 23:50
I have also been experiencing this issue. It was odd because I had it working just fine in another tenant, but looking at my  working service principal's permissions I discovered something. It appears to be caused by the existence of **both** the Graph and SharePoint Sites.FullControl.All permissions existing for the service principal.

After removing the Graph permission and leaving the SharePoint Sites.FullControl.All I was able to run my Azure Automation runbooks using -ManagedIdentity without receiving a 401 error.

**Comment by martinlingstuyl** [comment] 2023-02-13 13:32
Hi @joostvdlinden,

It might just be that the problem you are facing has nothing to do with auth.

The command Get-PnPSite tries to log to the console, which is problematic in Azure Automation. I'm not sure exactly why. 

What you can do is assign the result to a variable: `$site = Get-PnPSite` and use `Write-Output` to check if it holds a value.

Reference:
https://social.msdn.microsoft.com/Forums/en-US/d232d7d1-53ce-4778-b6f8-2de6bcba272a/the-runbook-job-was-attempted-3-times-but-it-failed-each-time?forum=azureautomation

**Comment by kingy444** [comment] 2023-02-13 23:03
> I have also been experiencing this issue. It was odd because I had it working just fine in another tenant, but looking at my working service principal's permissions I discovered something. It appears to be caused by the existence of **both** the Graph and SharePoint Sites.FullControl.All permissions existing for the service principal.
> 
> After removing the Graph permission and leaving the SharePoint Sites.FullControl.All I was able to run my Azure Automation runbooks using -ManagedIdentity without receiving a 401 error.

Thanks for the suggestion, had my hopes up for a moment - unfortunately this didn't work in my case
System Managed Identity is throwing the same error
``
Unable to connect to the SharePoint Online Admin Center at 'https://mytenant-admin.sharepoint.com' to run this cmdlet. Please ensure you pass in the correct Admin Center URL using Connect-PnPOnline -TenantAdminUrl and you have access to it. Error message: The remote server returned an error: (401) Unauthorized..
``

The identity did have both the graph and SharePoint permissions but still having the same issue after removing the Graph Permission.
```
Connect-PnPOnline -Url "https://mytenant.sharepoint.com" -ManagedIdentity
```
```
Microsoft Graph\Group.Read.All
Microsoft Graph\User.Read.All
Office 365 SharePoint Online\Sites.FullControl.All
```

From https://pnp.github.io/powershell/articles/azurefunctions.html#by-using-a-managed-identity you need to be running >version 1.11.95-nightly and I am using 1.12.0 so that shouldn't be an issue.

**Comment by martinlingstuyl** [comment] 2023-02-14 02:57
Hi @kingy444, 
If you want to run commands that require an admin context, you should sometimes connect to it yourself. PnP PowerShell doesnt always switch for you. 

Did you try to do that? (By Adding the -admin part in your url that you're connecting to) Just to be sure, your comment does not suggest this.

**Comment by kingy444** [comment] 2023-02-14 03:41
Hi @martinlingstuyl 

Thank you for the suggestion. The error message threw me off as it was suggesting to use the **-TenantAdminUrl** parameter which I could not get to work and not to add the '-admin' into the **-Url** parameter

This isn't documented over at https://pnp.github.io/powershell/cmdlets/Connect-PnPOnline.html#example-12 but great tip as we are up and running using the below. Never needed to do this when using the RunAsAccount but at least it is working now.
``
Connect-PnPOnline -Url "https://mytenant-admin.sharepoint.com" -ManagedIdentity
``

**Comment by martinlingstuyl** [comment] 2023-02-14 08:32
Happy to hear its working now!

**Comment by joostvdlinden** [comment] 2023-02-14 19:28
Well finally, got it working too.
For assistance to others, this is working for me in the Runbook:

```
Connect-PnPOnline -Url "https://tenantname-admin.sharepoint.com" -ManagedIdentity

$site = Get-PnPTenantSite -Identity "https://tenantname.sharepoint.com/sites/TestSite"
Write-Output $site

Disconnect-PnPOnline
```

Thanks all

**Comment by martinlingstuyl** [comment] 2023-02-14 21:42
🦾 That's awesome @joostvdlinden, in that case, could you close this issue?

**Comment by kingy444** [comment] 2023-02-14 21:46
Could I potentially suggest a documentation update around this before closing ?

**Comment by martinlingstuyl** [comment] 2023-02-15 14:03
You mean [something like this](https://pnp.github.io/powershell/articles/azurefunctions.html?q=managedidentity), but targeted at Automation Runbooks @kingy444?

**Closed** 2023-02-26 16:25 UTC

**Comment by ImAheadofU** [comment] 2023-09-22 21:52
Enough of the social graces. 
Has this issue been resolved or can we expect the IT Pro community to continue dealing with these nuances?

**Comment by erose96** [comment] 2023-12-29 16:52
The error should point users towards the solution, I do not believe this issue should have been closed

**Comment by nicole-ge** [comment] 2024-02-20 20:37
> Well finally, got it working too.
> For assistance to others, this is working for me in the Runbook:
> 
> ```
> Connect-PnPOnline -Url "https://tenantname-admin.sharepoint.com" -ManagedIdentity
> 
> $site = Get-PnPTenantSite -Identity "https://tenantname.sharepoint.com/sites/TestSite"
> Write-Output $site
> 
> Disconnect-PnPOnline
> ```
> 
> Thanks all

Have your Managed Identity only Site.Selected permissions?

**Comment by martinlingstuyl** [comment] 2024-02-20 21:17
@nicole-ge, you cannot use this commandlet with Sites.Selected permissions. It requires access to the tenant administration site, so you'll need Sites.Read.All at least.

**Comment by nicole-ge** [comment] 2024-02-20 21:31
@martinlingstuyl 
I m trying to run a runbook with connection to SPO but it is Kot working maybe you can help.

Environment

- Azure Automation Account with enabled system assigned managed identity
- Powershell 7.2 Runbook
- SharePoint Online Team Site

Permissions
Write" role on target SharePoint Site, granted with "grant-PnPAzureADAppSitePermission" and visible with "get-pnpazureadAppSitePermission"

Scripts:
$Connection = Connect-PnPOnline -Url $SiteURL -ManagedIdentity -ReturnConnection
$Lists = Get-PnPList -Connection $Connection
Write-Output $Lists

Error 
401 unauthorized

What i am dringend wrong?

**Comment by martinlingstuyl** [comment] 2024-02-21 07:29
@nicole-ge, did you assign Sites.Selected permissions as well? You'll need that in combination with the site permission
If so: do check that you've used the correct one. There's one for SharePoint and one for Microsoft Graph. In this case, the commandlet Get-PnPList uses the SharePoint API, so you need SharePoint Sites.Selected.

If you've configured all that correctly and it still does not work: you may need the "Manage" role instead of the "Write" role. I think that one only pertains to list-items, not lists.

**Comment by nicole-ge** [comment] 2024-02-21 09:46
@martinlingstuyl 
So for my right understanding I need this 2 commands to make it work

1) Sites.Selected for SharePoint API 
And then I make 
 2) Get-PnPAzureADAppSitePermission -AppIdentity <AppId>

Is this the correct script for the site.selected to sharepoint? I have run this script, but I couldn't see it in the enterprise application of the managed identity 

# Add the correct 'Application (client) ID' and 'displayName' for the Managed Identity
$application = @{
    id = "xxxx"
    displayName ="xxx"
}

# Add the correct role to grant the Managed Identity (read or write)
$appRole = "write"

# Add the correct SharePoint Online tenant URL and site name
$spoTenant = "tenant.sharepoint.com"
$spoSite  = "xxxx"

# No need to change anything below
$spoSiteId = $spoTenant + ":/sites/" + $spoSite + ":"

Import-Module Microsoft.Graph.Sites
Connect-MgGraph -Scope Sites.FullControl.All

New-MgSitePermission -SiteId $spoSiteId -Roles $

**Comment by martinlingstuyl** [comment] 2024-02-21 10:38
Hi,
If you're using PnP PowerShell, you can run the following:

```powershell
# Use the object ID of the managed identity
$appObjectId = "<some guid>" 
Add-PnPAzureADServicePrincipalAppRole -Principal $appObjectId -AppRole "Sites.Selected" -BuiltInType SharePoint

# Use the App ID of the managed identity
$appId = "<some guid>"
Grant-PnPAzureADAppSitePermission -AppId $appId -DisplayName "AppName" -Permissions Manage -Site https://contoso.sharepoint.com/sites/projects
```

You can also follow along with my blog post on this here. In which case I'm using the CLI for Microsoft 365 to assign the permissions to the Identity:
https://www.blimped.nl/running-application-with-limited-sharepoint-permissions/

**Comment by nicole-ge** [comment] 2024-02-21 11:22
Thank you @martinlingstuyl I will test it and let you know

I am not very família with the m365 cli

**Comment by nicole-ge** [comment] 2024-02-23 13:06
Hello @martinlingstuyl 
Thank you for your Quick help. This commands works and I can access SPO from my runbook.

**Comment by martinlingstuyl** [comment] 2024-02-23 18:09
Awesome! Thanks for letting me know and happy coding!

**Comment by NiklasJegg1** [comment] 2024-08-16 08:35
Hi @martinlingstuyl can i also use this approach to Edit/Get/Update Listitems in SPO?

I Have a runbook in my automation account. The managed Identity of the Runbook is also set up. Permissions are as follows for the Identity: 
Application Permission: 
Graph - Sites.ReadWrite.All
Office 365 SharePoint Online Sites.Selected and Sites.Read.All

I am running Powershell 7.2 with PnP.Powershell version

I am succesfully connecting but my error is 
"The current connection holds no SharePoint context. Please use one of the Connect-PnPOnline commands which uses the -Url argument to connect."

I am useing $Connection = Connect-PnPOnline -Url $SiteURL -ManagedIdentity -ReturnConnection  to connect and $listItems = Get-PnPListItem -List $listName to get the listitems

**Comment by martinlingstuyl** [comment] 2024-08-16 14:37
Hi @NiklasJegg1, you should certainly be able to do so.

I think what you're missing is adding the `-Connection $Connection` parameter to the commandlets. If you're using the `-ReturnConnection` parameter you always have to do this, and it's easy to forget.

**Comment by NiklasJegg1** [comment] 2024-08-19 04:44
Hi @martinlingstuyl oh wow thanks i did oversee the -Connection $ Connection part.
Now i am just getting 401 Unauthorized. This means i need so check my permission settings for the Managed Identity.
It has MS Graph Sites.ReadWrite.All but i guess i am missing Office 365 Sharepoint Online permissions (they are needed right)

**Comment by martinlingstuyl** [comment] 2024-08-19 05:04
> It has MS Graph Sites.ReadWrite.All but i guess i am missing Office 365 Sharepoint Online permissions (they are needed right)

Yes, AFAIK you need "Office 365 Sharepoint Online" permissions for most of the PnP commandlets relating to SharePoint.

**Comment by NiklasJegg1** [comment] 2024-08-19 05:11
and now there is another weird "error" : The Push Notifications feature is not activated on the site

I have tried to activate it with this https://github.com/pnp/powershell/issues/3729 but i can't even find the Feature ID with powershell.
I have checked in Admin Center and Notifications are Enabled.

**Comment by martinlingstuyl** [comment] 2024-08-19 05:18
I have sometimes received that error message in the past as well. Not sure what the cause is, seems totally unrelated to what you're doing most of the time.
Anyway, you activated the feature, did that resolve the issue? I'm seeing the tops of some red letters in your screenshot 😁

**Comment by NiklasJegg1** [comment] 2024-08-19 05:25
it solved the issue yes :D it was just the verbose message of the feature not being activated. 
thank you so much for the help. Almost would have went back to Certificate auth with a Hybrid runbook worker :D

**Comment by martinlingstuyl** [comment] 2024-08-19 05:34
Managed Identity is much better! :-)
