### ISSUE TITLE
[BUG] Import-PnPTaxonomy ignores Lcid

### ISSUE THREAD

**Issue by FrancisGoeminne** [pnp/powershell#3096] opened 2023-05-07 09:10 UTC
### Reporting an Issue or Missing Feature
I'm trying to use Import-PnPTaxonomy to import a localized termset in SharePoint online. I can only update labels in the default language (1033) . The LCID parameter is ignored. I tested this with the language Dutch and French.

I also tried it on a SP 2019. it has the same behaviour => only the labels in the default language get updated instead of the of the localized label.

### Expected behavior 
Add/update the labels of the term for LCID 1043 (French).
Add: it the term label doesn't exist yet
Update if the term label for the LCID exists

### Actual behavior 
It updates the default language1033 terms, no localized labels are added nor updated. Even if a French label of the term exists, it's ignored and only the default label is updated.

### Steps to reproduce behavior

Import-PnPTaxonomy -Path "c:\temp\tax.txt" -Lcid 1043

contents of tax.txt:

AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800|AAA_FR;#c36f4b5b-c168-4223-aed0-33dd383cfb51|MyFirstTest_FR;#ea083f96-7198-4f2a-b68e-8cf615be222b
AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800|AAA_FR;#c36f4b5b-c168-4223-aed0-33dd383cfb51|Test_FR;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039
AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800|AAA_FR;#c36f4b5b-c168-4223-aed0-33dd383cfb51|Test_FR;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039|SubTest_FR;#570de8fb-83e0-4543-9da7-8444e4f96cdb

I also tried it directly (without file), but it has the same behavior:
Import-PnPTaxonomy -Terms 'AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800|AAA_FR;#c36f4b5b-c168-4223-aed0-33dd383cfb51|Test_FR;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039|SubTest_FR1111;#570de8fb-83e0-4543-9da7-8444e4f96cdb' -lcid 1036

### What is the version of the Cmdlet module you are running?
1.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2023-05-07 12:15
@FrancisGoeminne - The first think we'll ask is to update the module to the latest `2.1.1` (major), and possibly the `nightly` release, and let us know. 

You **must** be on PS 7.2 minimum for version `2.x` of the module (no support for PS5 not the ISE).

**Comment by FrancisGoeminne** [comment] 2023-05-07 16:16
Thanks for the response.
I ran the same commands for 2.1.1, and the nightly build, the results are the same: the LCID is ignored, and the label in the default language gets updated.

**Comment by veronicageek** [comment] 2023-09-21 20:32
@gautamdsheth - Can you confirm if the answer you gave to #3411 (by design), applies for this command too?

**Comment by koskila** [comment] 2023-10-26 06:43
This seems to be an oversight in the PnP.Framework library. Updating terms isn't really supported, labels are completely ignored in that case and any found terms' names are just overwritten with whatever is supplied.

This issue was already reported in 2017 here:
https://github.com/pnp/PnP-Sites-Core/issues/662

I have a possible fix in PnP.Framework repo here:
https://github.com/pnp/pnpframework/pull/934

**Comment by veronicageek** [comment] 2023-10-26 20:20
Thanks a lot @koskila 🙂 I can see it's been merged.

@FrancisGoeminne - Can you please try again tomorrow (Fri 27-Oct or later).

**Comment by FrancisGoeminne** [comment] 2023-10-26 22:01
Hi, thank you both! 
I'll give it a try this weekend 


Van: "Veronique Lengelle" ***@***.***> 
Aan: "pnp/powershell" ***@***.***> 
Cc: "francis" ***@***.***>, "Mention" ***@***.***> 
Verzonden: Donderdag 26 oktober 2023 22:20:32 
Onderwerp: Re: [pnp/powershell] [BUG] Import-PnPTaxonomy ignores Lcid (Issue #3096) 





Thanks a lot [ https://github.com/koskila | @koskila ] 🙂 I can see it's been merged. 

[ https://github.com/FrancisGoeminne | @FrancisGoeminne ] - Can you please try again tomorrow (Fri 27-Oct or later).

**Comment by koskila** [comment] 2023-10-27 06:24
Just to set expectations: I didn't change the way it renames the terms (I wasn't sure if changing that had would have side effects and if it would match with how people generally want this to work) but it should now add/update labels properly :)

**Comment by FrancisGoeminne** [comment] 2023-11-03 00:11
Thanks for the changes! 
I've tested them. I can update the labels now. If I update a label for a specific languale it will update the label for that langues together with the default language (en-US, LCID 1033) 
My current workaround is to call the Import-PnPTaxonomy for LCID 1033 after the languages for a specific term are updated. Updates for LCID 1033 are only applied on the LCID 1033 labels. All other calls will update their corresponding language + the default label 

Sample: 

Import-PnPTaxonomy -Terms 'AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800| AAA_NL ;#c36f4b5b-c168-4223-aed0-33dd383cfb51| Test_NL ;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039| SubTest_NL ;#570de8fb-83e0-4543-9da7-8444e4f96cdb' -lcid 1043 -connection $pnpConnection 
Import-PnPTaxonomy -Terms 'AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800| AAA_FR ;#c36f4b5b-c168-4223-aed0-33dd383cfb51| Test_FR ;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039| SubTest_FR ;#570de8fb-83e0-4543-9da7-8444e4f96cdb' -lcid 1036 -connection $pnpConnection 
Import-PnPTaxonomy -Terms 'AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800| AAA_DE ;#c36f4b5b-c168-4223-aed0-33dd383cfb51| Test_DE ;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039| SubTest_DE ;#570de8fb-83e0-4543-9da7-8444e4f96cdb' -lcid 1031 -connection $pnpConnection 
Import-PnPTaxonomy -Terms 'AAMigrationTest;#25e742e7-169f-4e49-8763-1b8b2e1f3800| AAA_EN ;#c36f4b5b-c168-4223-aed0-33dd383cfb51| Test_EN ;#5d8d0d9b-b800-49a9-81e8-1866bfe9f039| SubTest_EN ;#570de8fb-83e0-4543-9da7-8444e4f96cdb' -lcid 1033 -connection $pnpConnection

**Closed** 2023-11-03 13:19 UTC
Labels: bug
