### ISSUE TITLE
GCC Issue with Register-PnPAzureADApp

### ISSUE THREAD

**Issue by JuddG-Microsoft** [pnp/powershell#4134] opened 2024-08-06 14:50 UTC
### Reporting an Issue or Missing Feature
I am setting up PnP PowerShell in a GCC environment and we are getting an error running Register-PnPAzureADApp.  

### Expected behavior 
We are expecting this command to create the App registration in our GCC tenant.

### Actual behavior 
On running the command,we immediately receive an error:

![image](https://github.com/user-attachments/assets/2f59f1bf-24b6-48df-ac9c-ddd498918795)

### Steps to reproduce behavior
We are using the syntax from the Install instructions:

Register-PnPAzureADApp -ApplicationName "PnP PowerShell" -Tenant uspsgcctenant.onmicrosoft.com -Interactive -AzureEnvironment USGovernment -SharePointDelegatePermissions AllSites.FullControl -SharePointApplicationPermissions Sites.FullControl.All -GraphApplicationPermissions Group.ReadWrite.All -GraphDelegatePermissions Group.ReadWrite.All

### What is the version of the Cmdlet module you are running?
2.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by SteveWinward** [comment] 2024-08-07 03:02
I created a pull request in the PnP Core framework to fix the AuthenticationManager class.  It was pointing AzureEnvironment.UsGovernment to the incorrect login URLs.  The PR is here => https://github.com/pnp/pnpframework/pull/1047

How can we get this updated in the PnP Core Framework, and then get this PowerShell project to use the newer Nuget package reference?

**Comment by gautamdsheth** [comment] 2024-08-09 20:04
Hi @SteveWinward / @JuddG-Microsoft - the necessary changes have been merged in PnP Framework. It will be automatically updated in PnP PowerShell as well and available in tomorrow's nightly builds as well the next major version. Closing it, please reopen if the issue is still there.

**Closed by gautamdsheth** 2024-08-09 20:04 UTC
Labels: bug
