### ISSUE TITLE
[BUG] VSCode Move-PnPFile : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan1)'.

### ISSUE THREAD

**Issue by ingepepe** [pnp/powershell#727] opened 2021-05-26 20:29 UTC
1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? 
No

### Reporting an Issue or Missing Feature
When trying to execute the command

`Move-PnPFile -SourceUrl "/sites/Leadership-365/Shared Documents/Regional Managers" -TargetUrl "/sites/operations.leaders/Shared Documents" -AllowSchemaMismatch`

I get the following error:

`Move-PnPFile : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan1)'.`

What is this error about?

### Expected behavior 
Run the cmdlet

### Actual behavior 
Error: Method not Found

### Steps to reproduce behavior
When trying to execute the command

`Move-PnPFile -SourceUrl "/sites/Leadership-365/Shared Documents/Regional Managers" -TargetUrl "/sites/operations.leaders/Shared Documents" -AllowSchemaMismatch`

I get the following error:

`Move-PnPFile : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan1)'.`

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
```
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.5.38     PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, Add-PnPAzureADGroupMember...}
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment] 2021-05-26 23:10
Hi @ingepepe , could you please update module? We are already on `PnP,PowerShell 1.5.54`
Personally I am not able to replicate that issue even on `PnP.PowerShell 1.5.42`

Could you please also update Title of this request to better reflect the problem?

**Comment by ingepepe** [comment] 2021-05-26 23:21
Just did. Same error.

Sent from my iPhone

On May 26, 2021, at 17:10, Yuriy Samorodov ***@***.***> wrote:

﻿

Hi @ingepepe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fingepepe&data=04%7C01%7C%7Cb79d1e16f86f40a06f8308d9209b7886%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637576674376873496%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Y6MBIv8g1kKm4e4dUlTT3yvtSvpkdbZldceeQuj5vYo%3D&reserved=0> , could you please update module? We are already on PnP,PowerShell 1.5.54
Personally I am not able to replicate that issue even on PnP.PowerShell 1.5.42

Could you please also update Title of this request to better reflect the problem?

**Comment by YuriySamorodov** [comment] 2021-05-26 23:23
Hey @ingepepe , could you please confirm endpoint you are connecting to? Please note you have to connect to source site to move files and folders.

**Comment by ingepepe** [comment] 2021-05-27 00:28
I’m using Connect-PnPonline to the source site
Ran get-pnplist to make sure I was there

Sent from my iPhone

On May 26, 2021, at 17:23, Yuriy Samorodov ***@***.***> wrote:

﻿

Hey @ingepepe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fingepepe&data=04%7C01%7C%7C0ce7359898a44cc0a25c08d9209d56d6%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637576682393319031%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Q%2BioCcjvsXAfW%2FAs0NXXYy6kA1xlVTuBUElSyCAHQDQ%3D&reserved=0> , could you please confirm endpoint you are connecting to? Please note you have to connect to source site to move files and folders.

**Comment by veronicageek** [comment] 2021-05-27 11:09
@ingepepe - I'm using `1.5.55-nightly` and have no issue. Please update the module and try again, or try another site.

Also, what is that dot (.) in your target site?

**Comment by ingepepe** [comment] 2021-05-27 14:21
@veronicageek 

This is what I get from another site:

VERBOSE: PnP PowerShell Cmdlets (1.5.54.0)
PS C:\> Move-PnPFile -SourceUrl "/sites/test01/lead/Team Meetings/MyFile.docx" -TargetUrl "/sites/test02/Shared Documents/General" -NoWait -Force -AllowSchemaMismatch -AllowSmallerVersionLimitOnDestination

Move-PnPFile : Method not found: 'Int32 System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)'.
At line:1 char:1
+ Move-PnPFile -SourceUrl "/sites/test01/lead/Team Meetings/MyFile.docx ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Move-PnPFile], MissingMethodException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Files.MoveFile

**Comment by ingepepe** [comment] 2021-05-27 15:13
Not sure if it has to do with the fact that I'm executing it from VS Code?

**Comment by veronicageek** [comment] 2021-05-28 08:22
@ingepepe - I don't think VSCode is not an issue as I've been able to successfully run your code. 
I'm still not able to reproduce unfortunately and it's working fine for me.

Let's see if @gautamdsheth / @erwinvanhunen have any ideas / insights.

**Comment by colonelclaypoo** [comment] 2021-05-28 09:55
I've been experiencing a similar issue with a for example `Add-PnPPage`. In VSCode I'm getting:
`Method not found: "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable1<Boolean>  
Enumerator.MoveNextAsync()"`

Using 1.5.55-nightly.

It works fine in PowerShell 5 and 7 standalone console.

So it might be VSCode related after all what do you think?

**Comment by ingepepe** [comment] 2021-05-28 13:10
I tried and it worked on PowerShell for Windows (5.1)

Sent from my iPhone

On May 28, 2021, at 03:55, colonelclaypoo ***@***.***> wrote:

﻿

I've been experiencing a similar issue with a for example Add-PnPPage. In VSCode I'm getting:
Method not found: "System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable1<Boolean> Enumerator.MoveNextAsync()"

Using 1.5.55-nightly.

It works fine in PowerShell 5 and 7 standalone console.

So it might be VSCode related after all what do you think?

**Comment by SergeiAtML** [comment] 2021-06-15 13:29
I had the same exact issue with different command-lets.  Ended up downgrading to 1.5.0 and issue went away.

**Comment by colonelclaypoo** [comment] 2021-06-15 14:01
It's unfortunate but I can confirm your two statements @SergeiAtML. Ended up downgrading as well on one machine end try to use the PowerShell 7 default shell when necessarily have to make use of a newer version than 1.5.0.

**Comment by jpwegmuller50** [comment] 2021-06-23 18:15
I can also confirm that downgrading to 1.5.0 resolves the issue in VSCode (mine was with the Add-PnPGroupMember cmdlet).

**Comment by RoSchoe** [comment] 2021-07-27 09:03
What has been done in 1.6.0 / 1.70 from 1.5.0 with the 
.net library or sth?

downgrade to 1.5.0 solved it - but why? 
Without vscode all is fine.

**Comment by mcihon-inwk** [comment] 2021-08-06 18:16
Also ran into this issue with Copy-PnPFile and VSCode.  Works fine if run outside of VSCode.

**Comment by RoSchoe** [comment] 2021-08-09 06:45
Same with Move-PnPFile :)
VS Code 1.59

**Comment by Tom-CK** [comment] 2021-08-18 11:12
I am having the same issue using Get-PNPListItem in vscode.
The error does not exist when running Get-PNPListItem in regular PowerShell.

Steps to reproduce:
- Install-Module PNP.PowerShell -Required Version 1.7.0
  When running Get-PNPListItem in vscode an exception is thown:
  System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> 
  System.MissingMethodException:  
                        Methode nicht gefunden: "Int32 
  System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)".  

Maybe "System.Text.Encodings.Web.TextEncoder.FindFirstCharacterToEncodeUtf8(System.ReadOnlySpan`1<Byte>)" indicates a type-mismatch in source-code somewhere ?

I then call Uninstall-Module PNP.PowerShell followed by Install-Module PNP.PowerShell -RequiredVersion 1.5.0.
After this, evertything works fine, no error vscode.

So it seems like the error does not exist in PNP.PowerShell 1.5.0 but in version 1.7.0.
And it is only thrown usin vscode powershell.

**Comment by andschwa** [comment] 2021-09-28 20:42
Repeating ping but over here...

@KoenZomers and @gautamdsheth are you two also looking at this? It seems to have been introduced when a custom ALC with a resolver was added to PNP.PowerShell, and it's not expecting another ALC (the one in Editor Services) to exist and possibly resolve dependencies. But we're still not entirely sure.

See: https://github.com/PowerShell/vscode-powershell/issues/3510

**Comment by erkanch** [comment] 2021-09-30 00:44
Try running it in regular VS Code terminal, not in the PowerShell Integrated Console. I had a similar issue with Add-PnPApp and it works on the regular terminal. If you check the versions of the 2 consoles running Get-Host | Select-Object Version, regular console is 5.1.18362.1801, whereas the PowerShell Integrated Console is 2021.9.0.

**Comment by gautamdsheth** [comment] 2023-03-24 14:01
@andschwa , @ingepepe  - we have updated quite a few dependencies in the latest nightly builds as part of prep for an upcoming v2, maybe it fixes the issue ? 

To test it, you can download the latest nightly builds and maybe let us know if the issue still persists ? 
The v2 supports only PowerShell 7.2 or later versions .

**Comment by gautamdsheth** [comment] 2023-04-05 13:38
Closing this issue now. 
Since v2.1.1 , PnP PowerShell is fully on .NET 6, so we have dropped support for PS5.1 or ISE.
If the issue still exists, please feel free to reopen it.

**Closed by gautamdsheth** 2023-04-05 13:38 UTC
