### ISSUE TITLE
[BUG] - Get-PnPException fails when setting ErrorAction switch parameter

### ISSUE THREAD

**Issue by Tinathnath** [pnp/powershell#792] opened 2021-06-14 12:38 UTC
### Reporting an Issue or Missing Feature
Reporting a minor bug

### Expected behavior 
When using Get-PnPException, I should get the full exception details.

### Actual behavior 
There was actually an exception while trying to get the exception. It only occurs if I provide the `-ErrorAction Stop` switch. If I left it empty, I can get the actual exception.

![image](https://user-images.githubusercontent.com/3273299/121893064-d36fd780-cd1d-11eb-8a6e-d34d64c5dc64.png)

### Steps to reproduce behavior
Try a failing cmdlet with and without the `ErrorAction` switch and try to get the inner exception.
I don't whether it's related to the Provisioning Engine or not, please let me know if it's the case.

### What is the version of the Cmdlet module you are running?
1.6.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows

Thank you !

**Comment by KoenZomers** [comment] 2021-09-23 22:32
Looking into this one.

**Comment by KoenZomers** [comment] 2021-09-23 22:42
Can reproduce this. Fixing it now.

**Comment by KoenZomers** [comment] 2021-09-23 22:53
Issue resolved. Thanks for reporting it @Tinathnath! The day after above mentioned PR has been merged, you can get the latest prerelease to check if the problem has been resolved for you. Assuming that this PR will fix it, I will proceed with closure of this issue. If it turns out not to fix it for you, feel free to reopen this issue.

**Closed by KoenZomers** 2021-09-23 22:53 UTC
Labels: bug, reproduced

**Comment by Tinathnath** [comment] 2021-09-23 23:02
Hi ! 
Thanks for the fix. I’ll try this and let you know if it fails.
