### ISSUE TITLE
[BUG] Get-PnPTenantSite not returning correct information related to Hub and Owner when returning a list of site collections

### ISSUE THREAD

**Issue by ooiming** [pnp/powershell#664] opened 2021-05-08 01:49 UTC
Get-PnPTenantSite  -Identity < url >
- This returns correct info for "IsHubSite", "HubSiteId", "Owner", "OwnerEmail", "OwnerLoginName", "OwnerName" for that specific site collection.

Get-PnPTenantSite  
- This does not return correct info for "IsHubSite", "HubSiteId" --> IsHubSite is FALSE for all site collections, even there are several site collections that are Hub sites.
- This does not return correct info for "Owner", "OwnerEmail", "OwnerLoginName", "OwnerName"  
--> If "Owner" is an account/ID, this column has value, but blank for the remaining 3 columns (stated above)
--> If "Owner" is a group, all 4 columns are shown as blank

**Comment by veronicageek** [comment] 2021-05-08 08:47
@ooiming - Please don't delete the template when opening an issue, it's here for a reason: help troubleshooting your issue faster.

@gautamdsheth / @erwinvanhunen: Can reproduce the issue on `v1.5.36-nightly`. The values returned with `Get-PnPTenantSite` are not correct or blank.

![image](https://user-images.githubusercontent.com/25181757/117532953-e4704f00-afe1-11eb-919e-389120f21254.png)

**Comment by gautamdsheth** [comment] 2021-05-15 20:56
Looks like we are getting incorrect data from CSOM. Will check this internally.

**Comment by robertcaretta** [comment] 2021-05-28 16:39
Same issue as this. Was reported a long time ago and was archived. 
https://github.com/pnp/PnP-PowerShell/issues/2469

**Comment by robertcaretta** [comment] 2021-06-12 02:32
Not stale. Keep open

**Comment by robertcaretta** [comment] 2021-07-02 04:01
Not stale. Keep open. Turn the bot off.

**Comment by gautamdsheth** [comment] 2021-07-02 13:13
@robertcaretta - Debugged this issue, looks like an issue with CSOM not returning correct information. Would suggest that you open a case with Microsoft about this, unfortunately we can't do anything about it as we are simply consuming CSOM methods.

**Comment by robertcaretta** [comment] 2021-07-02 14:53
Are there any other details you can provide regarding the CSOM methods?  If
I open a ticket with Microsoft they are going to ask for more information,
such as which methods are not working correctly and what the specific
error is that needs to be fixed.

**Comment by veronicageek** [comment] 2021-07-02 15:09
@gautamdsheth - Please provide some details you can / aware of, so we keep a trace in this thread to help people in the future. Then we can close the issue if there's nothing we can do unfortunately.

**Comment by robertcaretta** [comment] 2021-07-02 18:37
I think it would be appropriate to add a "Known Limitations" section to the official documentation. 
https://pnp.github.io/powershell/cmdlets/Get-PnPTenantSite.html

**Comment by veronicageek** [comment] 2021-07-02 19:15
A lot of the cmdlets are depending on CSOM in the background, so updating each of them is unlikely to happen. We might add a section in the [Articles](https://pnp.github.io/powershell/articles/index.html) and/or in the issue templates though.

**Comment by gautamdsheth** [comment] 2021-07-22 12:08
The method that is returning is incorrect data is this one - `GetSitePropertiesFromSharePointByFilters` 

You can check how its implemented from here which you can use in your support case:

https://github.com/pnp/powershell/blob/22985f6f3d15c0d23919a24288d7f92a175c2ab9/src/Commands/Admin/GetTenantSite.cs#L67-L99                

Going to close this one because there's nothing we can do here.
If/When Microsoft fixes this via CSOM, we will get the fix as we always use the latest CSOM SDK in the module.

**Closed by gautamdsheth** 2021-07-22 12:08 UTC
Labels: bug, reproduced
