### ISSUE TITLE
[BUG]Guid formatting exception when retrieving TermGroups with Export-PnPTermGroupToXml

### ISSUE THREAD

**Issue by IrCheema** [pnp/powershell#2749] opened 2023-01-25 15:15 UTC
### Expected behavior 
An xml file is expected to be generated with all term groups

### Actual behavior 
```
 Export-PnPTermGroupToXml : Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).
At C:\Users\xxx.xxx\TempPs\TestPnPExport.ps1:14 char:1
+ Export-PnPTermGroupToXml -Identity "People" -Out $ReportOutput
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Export-PnPTermGroupToXml], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,PnP.PowerShell.Commands.Taxonomy.ExportTermGroup
```

### Steps to reproduce behavior
**Termsets have default sortorder. Special characters like ":" in the prefix or suffix have not been used**
```
Connect-PnPOnline -Url $SiteUrl -Interactive
Export-PnPTermGroupToXml -Identity "People" -Out $ReportOutput
```
*$SiteUrl - SharePoint admin center
*$ReportOutput  - path to xml file

### What is the version of the Cmdlet module you are running?
```
ModuleType       Version          Name
Manifest          1.12.0           PnP.PowerShell
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2023-03-04 07:09
Hi, looks like a tenant specific issue.
Tried it on different tenants with steps you mentioned , but it always exported the term groups.

So, can't reliably reproduce this issue.
Can you try this on a different tenant or a site collection and let us know ?

**Comment by veronicageek** [comment] 2023-03-13 17:30
Closing for now but please reopen if the issue persists after trying on another site collection, and also maybe try with the latest nightly. Thanks.

**Closed by veronicageek** 2023-03-13 17:30 UTC
Labels: bug
