### ISSUE TITLE
[BUG] Get-PnPTenantSite returns erroneous value for DefaultSharingLinkType and DefaultLinkPermission

### ISSUE THREAD

**Issue by rajarshibhargav** [pnp/powershell#3938] opened 2024-05-06 11:24 UTC
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

The cmdlet Get-PnPTenantSite returns DefaultSharingLinkType and DefaultLinkPermission as one of the properties returned for a Sharepoint Site. However these 2 attributes constantly return the value 0 in output of Get-PnPTenantSite, irrespective of the advanced sharing external setting of the sharepoint site.
<img width="935" alt="image" src="https://github.com/pnp/powershell/assets/35682011/cbec7576-5ff1-4f87-9763-dab7954aa80c">

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

The command Get-PnPTenantSite should return the correct enum value for DefaultSharingLinkType and DefaultLinkPermission as in ( none, Direct, Internal, AnonymousAccess) and (none, View, Edit) respectively. 

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

The cmdlet Get-PnPTenantSite returns DefaultSharingLinkType and DefaultLinkPermission as one of the properties returned for a Sharepoint Site. However these 2 attributes constantly return the value 0 in output of Get-PnPTenantSite, irrespective of the advanced sharing external setting of the sharepoint site.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

1. Run the command Get-PnPTenantSite and note down the value of  DefaultSharingLinkType and DefaultLinkPermission  for a specific site. 
2. Change these settings for that site in sharepoint admin center. 
<img width="915" alt="image" src="https://github.com/pnp/powershell/assets/35682011/690206fa-f7fc-4606-841a-7722ad1baa5c">
3.  Run the command Get-PnPTenantSite again and note down the value of  DefaultSharingLinkType and DefaultLinkPermission.
4. The cmdlet will always return 0 for these attributes irrespective of upstream setting.

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

2.4.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [x] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ns-khp** [comment] 2024-05-08 08:17
@erwinvanhunen  - I see you are an active contributor.
Is there a timeline one can expect for the bugs to be taken up and fixed? 
Is there a process for prioritising bugs which you can share, so that we can have an expectation of the timeline for this fix thanks.

**Comment by rajarshibhargav** [comment] 2024-05-08 13:03
Hi @wilecoyotegenius , thanks for looking into this issue. 


We run the command `Get-PnPTenantSite | ConvertTo-Json  -Depth 4` to get the properties of all available sharepoint sites in a single output. 

When this command is run without an identity parameter, the value for DefaultSharingLinkType and DefaultLinkPermission always return 0 for all sites. For example: 

`PS /app> Get-PnPTenantSite

Url                                           Template             LocaleId
---                                           --------             --------
https://0br0g-my.sharepoint.com/              SPSMSITEHOST#0       1033
https://0br0g.sharepoint.com/                 SitePagePublishing#0 1033
https://0br0g.sharepoint.com/search           SRCHCEN#0            1033
https://0br0g.sharepoint.com/sites/sspm       GROUP#0              1033
https://0br0g.sharepoint.com/sites/test-team  GROUP#0              1033
https://0br0g.sharepoint.com/sites/testgroup1 GROUP#0              1033

PS /app> Get-PnPTenantSite | ConvertTo-Json  -Depth 4
[
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g-my.sharepoint.com/",
    "WebsCount": 0
  },
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g.sharepoint.com/",
    "WebsCount": 0
  },
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g.sharepoint.com/search",
    "WebsCount": 0
  },
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g.sharepoint.com/sites/sspm",
    "WebsCount": 0
  },
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g.sharepoint.com/sites/test-team",
    "WebsCount": 0
  },
  {
    "DefaultLinkPermission": 0,
    "DefaultLinkToExistingAccess": false,
    "DefaultSharingLinkType": 0,
    "Url": "https://0br0g.sharepoint.com/sites/testgroup1",
    "WebsCount": 0
  }
]`

However if we pass the Identity keyword and retrieve the attributes for a specific site, the data returned is correct: 

`PS /app> Get-PnPTenantSite -Identity https://0br0g.sharepoint.com/sites/testgroup1

Url                                           Template LocaleId
---                                           -------- --------
https://0br0g.sharepoint.com/sites/testgroup1 GROUP#0  1033

PS /app> Get-PnPTenantSite -Identity https://0br0g.sharepoint.com/sites/testgroup1 | ConvertTo-Json  -Depth 4
{
  "DefaultLinkPermission": 1,
  "DefaultLinkToExistingAccess": false,
  "DefaultSharingLinkType": 1,
  "Url": "https://0br0g.sharepoint.com/sites/testgroup1",
  "WebsCount": 1
}`

**_Can we please ensure that Get-PnPTenantSite returns correct property value for every sharepoint sites when retrieving site information for all sites without an identity filter?_**

**Comment by wilecoyotegenius** [comment] 2024-05-09 13:14
I was able to reproduce the problem. I also found out I have been looking into this issue some time ago (#3755 - the issue was with a different property, but the cause is the same).
As I mentioned [there](https://github.com/pnp/powershell/issues/3755#issuecomment-1945125390), the issue is not with PnP.PowerShell, but rather CSOM. Until Microsoft fixes the issue with `GetSitePropertiesFromSharePointByFilters` method, the only way to get actual values is to query individual site using -Identity parameter.

**Comment by reshmee011** [comment] 2024-05-12 04:59
@rajarshibhargav : I can reproduce the issue using SPO PowerShell, get-sposite versus get-sposite -identity <siteurl> with many properties differing e.g. SharingDomainRestrictionMode , LimitedAccessFileType, etc..  

If you can reproduce the issue using SPO PowerShell, I advise raising a case with Microsoft. As @wilecoyotegenius mentioned it is the underlying CSOM which has an issue. PnP PowerShell and SPO PowerShell is a wrapper /helper to access the CSOM function.

**Comment by rajarshibhargav** [comment] 2024-05-12 07:09
Yes @reshmee011 @wilecoyotegenius . Thanks for the update. We have raised a Microsoft Service Request for the same.

**Comment by veronicageek** [comment] 2024-05-12 15:21
Thanks @reshmee011 for your input. I'll close the issue here because there's not much we can do.

**Closed by veronicageek** 2024-05-12 15:21 UTC
Labels: bug
