### ISSUE TITLE
[BUG] Get-PnPTenantTheme cmdlet always returns null

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/powershell#1616] opened 2022-02-09 16:32 UTC
### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

Bug

### Expected behavior 

As per the [documentation](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnptenanttheme?view=sharepoint-ps), the cmdlet is supposed to return "all or a specific theme"

### Actual behavior 

Get-PnPTenantTheme with no parameters returns $null
Get-PnPTenantTheme -Name "Teal" returns "Unknown error"

Screenshot below:
![image](https://user-images.githubusercontent.com/10333583/153245442-18c53708-833d-4f87-b02f-15d71c65d5f4.png)

### Steps to reproduce behavior
Please see attached screenshot

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)
1.9.40

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by BaronSparky** [comment] 2022-03-07 15:42
I am seeing the same behaviour.

`Get-PnPTenantTheme` is only returning the "Company themes".

It is not retruned any of the ootb "SharePoint themes"

**Comment by gautamdsheth** [comment] 2022-04-16 20:00
Hi @DmitryVorobyov  , this behavior is by design. 

As @BaronSparky mentioned, the cmdlet only returns the custom themes or company themes that have been created in your tenant. 
We are not able to return OOTB themes as they are not exposed by the underlying CSOM SDK itself.

Will have to close this issue.

**Closed by gautamdsheth** 2022-04-16 20:00 UTC
Labels: bug
