### ISSUE TITLE
SharePoint Online Search Issue using PnP

### ISSUE THREAD

**Issue by jestinegoh** [pnp/powershell#890] opened 2021-07-05 07:19 UTC
### Notice
Many bugs reported are actually related to the PnP Framework which is used behind the scenes. Consider carefully where to report an issue:

1. **Are you using ```Invoke-PnPSiteTemplate``` or ```Get-PnPSiteTemplate```**? The issue is most likely related to the Provisioning Engine. The Provisioning engine is _not_ located in the PowerShell repo. Please report the issue here: https://github.com/pnp/pnpframework/issues.
1. **Is the issue related to the cmdlet itself, its parameters, the syntax, or do you suspect it is the code of the cmdlet that is causing the issue?** Then please continue reporting the issue in this repo.
1. **If you think that the functionality might be related to the underlying libraries that the cmdlet is calling** (We realize that might be difficult to determine), please first double check the code of the cmdlet, which can be found here: https://github.com/pnp/powershell/tree/master/src/Commands. If related to the cmdlet, continue reporting the issue here, otherwise report the issue at https://github.com/pnp/pnpframework/issues

### Reporting an Issue or Missing Feature
Please confirm what it is that your reporting

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Please describe what you see instead. Please provide samples of output or screenshots.

### Steps to reproduce behavior
Please include complete script or code samples in-line or linked from [gists](https://gist.github.com/)

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2021-07-05 07:54
Closing this as its not clear what the issue is with PnP.
Request you to please answer the issue template questions and reopen the issue.

**Closed by gautamdsheth** 2021-07-05 07:54 UTC
Labels: bug

**Comment by jestinegoh** [comment] 2021-07-05 08:01
Hi Elhadj,

My issue has been close due to the following reason.

Regards
Jestine GOH
Senior IT Consultant, Information Technology (Applications)
Tripartite Alliance Limited
80 Jurong East St 21, #05-05/06, Devan Nair Institute for Employment and Employability, Singapore 609607
T: 6956 6407 | ***@***.******@***.***> | TAL Personal Data Policy<https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tal.sg%2Fprivacy-statement%2F&data=02%7C01%7Cjestine_goh%40tal.sg%7C401a4a5984c443cc424108d8095629a9%7C0af12b508f1940928ace4dce8f8253e0%7C0%7C0%7C637269612992643648&sdata=yalG7HcSQL508xcqisIuQPsuOLUbCPKhNwAXPmV25%2FE%3D&reserved=0>

***@***.***D771B7.0167E960]

This message may contain confidential information intended only for the individual named. If you are not the named addressee, do not disseminate, distribute or copy this email. Please notify the sender immediately and delete this email from your system. Any views expressed in the email are those of the individual sender, except where the sender specifically states them to be the view of the Tripartite Alliance Limited (TAL). The information and/or comments provided or expressed in this message are not to be construed as legal advice and are not intended to replace legal advice. You should not rely on any information and/or comments provided or expressed in this message/research memorandum as legal advice. TAL shall not be responsible for any loss or damage arising from your reliance on any information and/or comments provided or expressed in this message.

**Comment by jestinegoh** [comment] 2021-07-05 08:24
Hello Jestine,

Good day!

Thank you for your email reply, kindly could you provide more description regarding the issue that you are facing?

Best regards,
Elhadj

From: Jestine Goh ***@***.***>
Sent: Monday, July 5, 2021 4:01 PM
To: Elhadj Mamoudou Diallo (Shanghai Wicresoft Co,.Ltd.) ***@***.***>
Cc: Author ***@***.***>; pnp/powershell ***@***.***>; pnp/powershell ***@***.***>
Subject: [EXTERNAL] RE: [pnp/powershell] SharePoint Online Search Issue using PnP (#890)

Hi Elhadj,

My issue has been close due to the following reason.

Regards
Jestine GOH
Senior IT Consultant, Information Technology (Applications)
Tripartite Alliance Limited
80 Jurong East St 21, #05-05/06, Devan Nair Institute for Employment and Employability, Singapore 609607
T: 6956 6407 | ***@***.******@***.***> | TAL Personal Data Policy<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tal.sg%2Fprivacy-statement%2F&data=04%7C01%7Cv-ediallo%40microsoft.com%7Cd642b24525844526f9b308d93f8b18e0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637610689586315681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1hFBkeMJm%2F8Velx7k7eRoL%2Bg3a25B5oSfRgHIY3aDpw%3D&reserved=0>

***@***.***D771BA.389E4070]

This message may contain confidential information intended only for the individual named. If you are not the named addressee, do not disseminate, distribute or copy this email. Please notify the sender immediately and delete this email from your system. Any views expressed in the email are those of the individual sender, except where the sender specifically states them to be the view of the Tripartite Alliance Limited (TAL). The information and/or comments provided or expressed in this message are not to be construed as legal advice and are not intended to replace legal advice. You should not rely on any information and/or comments provided or expressed in this message/research memorandum as legal advice. TAL shall not be responsible for any loss or damage arising from your reliance on any information and/or comments provided or expressed in this message.

**Comment by jestinegoh** [comment] 2021-07-05 08:31
Hi all,

We are using SharePoint web part Search function to search documents. Recently we noticed the search result is not working well. Some time ago, it was working.

If I tried to view source of the page and found the below codes for the Search input. Understand from Microsoft, PnP search is being used and there is a need to log issue with Github.

Please see below codes for your reference. For your advise please.

<div class="ms-tableCell ms-verticalAlignTop">
<div id="DeltaPlaceHolderSearchArea" class="ms-mpSearchBox ms-floatRight">
<div id="searchInputBox">
<div class="ms-webpart-chrome ms-webpart-chrome-fullWidth ">
<div WebPartID="00000000-0000-0000-0000-000000000000" HasPers="true" id="WebPartWPQ1" width="100%" class="ms-WPBody " OnlyForMePart="true" allowDelete="false" style="" ><div componentid="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr" id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr"><div id="SearchBox" name="Control"><div class="ms-srch-sb ms-srch-sb-border" id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_sboxdiv"><input type="search" value="Search..." maxlength="2048" title="Search..." id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_sbox" autocomplete="off" autocorrect="off" onkeypress="EnsureScriptFunc('Search.ClientControls.js', 'Srch.U', function() {if (Srch.U.isEnterKey(String.fromCharCode(event.keyCode))) {$find('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr').search($get('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_sbox').value);return Srch.U.cancelEvent(event);}})" onkeydown="EnsureScriptFunc('Search.ClientControls.js', 'Srch.U', function() {var ctl = $find('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr');ctl.activateDefaultQuerySuggestionBehavior();})" onfocus="EnsureScriptFunc('Search.ClientControls.js', 'Srch.U', function() {var ctl = $find('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr');ctl.hidePrompt();ctl.setBorder(true);})" onblur="EnsureScriptFunc('Search.ClientControls.js', 'Srch.U', function() {var ctl = $find('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr'); if (ctl){ ctl.showPrompt(); ctl.setBorder(false);}})" class="ms-textSmall ms-srch-sb-prompt ms-helperText" role="combobox" aria-owns="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_AutoCompList" aria-haspopup="true" aria-autocomplete="list" aria-expanded="false" /><a title="Search" role="button" class="ms-srch-sb-searchLink" id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_SearchLink" onclick="EnsureScriptFunc('Search.ClientControls.js', 'Srch.U', function() {$find('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr').search($get('ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_sbox').value);})" href="javascript: {}<about:blank>" aria-label="Search"><img src="/_layouts/15/images/searchresultui.png?rev=47#ThemeKey=searchresultui<https://talsg.sharepoint.com/_layouts/15/images/searchresultui.png?rev=47#ThemeKey=searchresultui>" class="ms-srch-sb-searchImg" id="searchImg" alt="Search" /></a><div class="ms-qSuggest-container ms-shadow" id="AutoCompContainer"><div id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_csr_AutoCompList" role="listbox" aria-label="Suggestions"></div></div></div></div></div><noscript><div id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1_noscript">It looks like your browser does not have JavaScript enabled. Please turn on JavaScript and try again.</div></noscript><div id="ctl00_PlaceHolderSearchArea_SmallSearchInputBox1">
</div><div class="ms-clear"></div></div>
</div>
</div>
</div>
</div>

Thank you


Regards
Jestine GOH
Senior IT Consultant, Information Technology (Applications)
Tripartite Alliance Limited
80 Jurong East St 21, #05-05/06, Devan Nair Institute for Employment and Employability, Singapore 609607
T: 6956 6407 | ***@***.******@***.***> | TAL Personal Data Policy<https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tal.sg%2Fprivacy-statement%2F&data=02%7C01%7Cjestine_goh%40tal.sg%7C401a4a5984c443cc424108d8095629a9%7C0af12b508f1940928ace4dce8f8253e0%7C0%7C0%7C637269612992643648&sdata=yalG7HcSQL508xcqisIuQPsuOLUbCPKhNwAXPmV25%2FE%3D&reserved=0>

***@***.***D771BA.BFCEB610]

This message may contain confidential information intended only for the individual named. If you are not the named addressee, do not disseminate, distribute or copy this email. Please notify the sender immediately and delete this email from your system. Any views expressed in the email are those of the individual sender, except where the sender specifically states them to be the view of the Tripartite Alliance Limited (TAL). The information and/or comments provided or expressed in this message are not to be construed as legal advice and are not intended to replace legal advice. You should not rely on any information and/or comments provided or expressed in this message/research memorandum as legal advice. TAL shall not be responsible for any loss or damage arising from your reliance on any information and/or comments provided or expressed in this message.


From: Elhadj Mamoudou Diallo (Shanghai Wicresoft Co,.Ltd.) ***@***.***>
Sent: Monday, July 5, 2021 4:24 PM
To: Jestine Goh ***@***.***>
Cc: Author ***@***.***>; pnp/powershell ***@***.***>; pnp/powershell ***@***.***>
Subject: RE: [pnp/powershell] SharePoint Online Search Issue using PnP (#890)

Hello Jestine,

Good day!

Thank you for your email reply, kindly could you provide more description regarding the issue that you are facing?

Best regards,
Elhadj

From: Jestine Goh ***@***.******@***.***>>
Sent: Monday, July 5, 2021 4:01 PM
To: Elhadj Mamoudou Diallo (Shanghai Wicresoft Co,.Ltd.) ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>; pnp/powershell ***@***.******@***.***>>; pnp/powershell ***@***.******@***.***>>
Subject: [EXTERNAL] RE: [pnp/powershell] SharePoint Online Search Issue using PnP (#890)

Hi Elhadj,

My issue has been close due to the following reason.

Regards
Jestine GOH
Senior IT Consultant, Information Technology (Applications)
Tripartite Alliance Limited
80 Jurong East St 21, #05-05/06, Devan Nair Institute for Employment and Employability, Singapore 609607
T: 6956 6407 | ***@***.******@***.***> | TAL Personal Data Policy<https://apc01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.tal.sg%2Fprivacy-statement%2F&data=04%7C01%7Cjestine_goh%40tal.sg%7Cd1c8b1283bad4c7cc8eb08d93f8e4f6c%7C0af12b508f1940928ace4dce8f8253e0%7C0%7C0%7C637610702733310554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gFCfq2SS92Z36kbcbB%2Br9l2tfgVAorFcZxMaJitrI7g%3D&reserved=0>

***@***.***D771BA.BFCEB610]

This message may contain confidential information intended only for the individual named. If you are not the named addressee, do not disseminate, distribute or copy this email. Please notify the sender immediately and delete this email from your system. Any views expressed in the email are those of the individual sender, except where the sender specifically states them to be the view of the Tripartite Alliance Limited (TAL). The information and/or comments provided or expressed in this message are not to be construed as legal advice and are not intended to replace legal advice. You should not rely on any information and/or comments provided or expressed in this message/research memorandum as legal advice. TAL shall not be responsible for any loss or damage arising from your reliance on any information and/or comments provided or expressed in this message.
