### ISSUE TITLE
[BUG] Get-PnPSiteTemplate : File Not Found.

### ISSUE THREAD

**Issue by andikrueger** [pnp/powershell#1156] opened 2021-09-23 13:24 UTC
### Reporting an Issue or Missing Feature
Currently I do see a strange error, when exporting a template. I'm facing a file not found error. The file should be created by PnP.

PS C:\temp> Get-PnPSiteTemplate -Connection $sourceConnection -Out template.pnp
Get-PnPSiteTemplate : File Not Found.
At line:1 char:1
+ Get-PnPSiteTemplate -Connection $sourceConnection -Out template.pnp
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Get-PnPSiteTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate
PS C:\temp> Get-PnPException

Message          : File Not Found.
Stacktrace       :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at                                                                                                                   Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()                         --- End of stack trace from previous location where exception was thrown ---                                               at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()                                                       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)                       at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext                        clientContext, Int32 retryCount, String userAgent)                                                                         at PnP.Framework.Provisioning.ObjectHandlers.ObjectWebSettings.PersistFile(Web web,                                  ProvisioningTemplateCreationInformation creationInfo, PnPMonitoredScope scope, String
                   serverRelativeUrl)
                      at PnP.Framework.Provisioning.ObjectHandlers.ObjectWebSettings.ExtractObjects(Web web,
                   ProvisioningTemplate template, ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.GetRemoteTemplate(Web web,
                   ProvisioningTemplateCreationInformation creationInfo)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExtractTemplate(XMLPnPSchemaVersion
                   schema, String path, String packageName, ExtractConfiguration configuration)
                      at PnP.PowerShell.Commands.Provisioning.Site.GetSiteTemplate.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()
ScriptLineNumber : 1
Is there any fix available?

PS C:\temp> get-module pnp.powershell

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.7.0      PnP.PowerShell                      {Add-PnPAlert, Add-PnPApp, Add-PnPApplicationCustomizer, A..

### Expected behavior 
PnP should create the file without the error.

### Actual behavior 
Template is not saved within a new file.

### Steps to reproduce behavior
```powershell
Get-PnPSiteTemplate -Connection $sourceConnection -Out template.pnp
```

### What is the version of the Cmdlet module you are running?
```
PS C:\dev\PnP.Migration> Get-Module -Name "PnP.PowerShell" -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   1.7.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-...
Manifest   1.2.0      PnP.PowerShell                      {Add-PnPClientSidePage, Add-PnPClientSidePageSection, Add-...
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2021-09-24 10:12
@andikrueger - I'm not able to reproduce your error, and works fine on Win/MacOS with `1.7.0`. It might have been at a point in time. Can you try again, or try on a different Site? Also, what AuthN are you using in the `$sourceConnection`?

![image](https://user-images.githubusercontent.com/25181757/134658107-18536c89-4371-47f7-bd22-e0fd40adb32a.png)

![image](https://user-images.githubusercontent.com/25181757/134658137-a042bd92-2e12-42f7-97ab-7416ce10468d.png)

**Comment by andikrueger** [comment] 2021-09-24 10:21
Yesterday I did some further tests On a fresh Windows server and did see the same error. 

Source connection is created by using

Connect-PnPOnline - Credential (Get-Credential)

**Comment by veronicageek** [comment] 2021-09-24 10:32
Then can you try on another site? And also on a Windows 10 machine (not server) so we can narrow the problem and check if related to something else. 

Was it working before on the machine where it's failing now?

**Comment by andikrueger** [comment] 2021-09-24 11:03
I tested it with several Windows 10 clients and it looks like it is related to the site collection, that I try to export. 

I did a further test with another site collection right now and the template is created. This is kind of strange. Is there any chance to track down the issue?

**Comment by veronicageek** [comment] 2021-09-24 12:59
OK - So this is not related to the command itself which is working fine. So I'm gonna have to close the issue.

You could look what differences would that site have compared to the other ones? Try the command with some parameters to (maybe) narrow down the issue.

Tagging @gautamdsheth & @KoenZomers in case they have seen this before, or have any other possible troubleshooting steps.

**Closed by veronicageek** 2021-09-24 12:59 UTC

**Comment by andikrueger** [comment] 2021-10-12 07:34
Not yet. I did start some further investigations and set up my own of PnP.PowerShell and PnP.Framework.  So far I was not able to step through the whole process of the template extraction.

Actually I think the exception happens in PnP.Framework and is only thrown through PnP.PowerShell.

My test site collection was a learning path ways solution within a tenant.

**Comment by AndreSchiemann** [comment] 2021-10-12 09:55
Thanks @andikrueger 

Meanwhile I found out, that in my used command from a comms site collection:
`Get-PnPSiteTemplate -OutputInstance -IncludeAllClientSidePages -Handlers PageContents,Pages -Schema LATEST -PersistBrandingFiles` 

The error "file not found" has a root cause in the option "PersistBrandingFiles" in my site collection.
I suppose a broken image hyperlink in a exported page. If I don't use this option, everything is exported without error message.

Maybe it helps you :-)

Cheers,
André

**Comment by drellik** [comment] 2024-07-29 14:15
I had the same issue. If it helps for anyone else I tracked it down to me changing the image filenames for the header and footer. I suspect the export tool uses an internal structure that gets created when you upload the images, and when you change the names, when it goes to export them, it can't find them in the site contents anymore. Changing the names back to the original file names resolved this for me.

By the way re-uploading the images with file names already changed didn't work for me.
