### ISSUE TITLE
[BUG] Cannot set site owner since version 1.60

### ISSUE THREAD

**Issue by nerodrom** [pnp/powershell#963] opened 2021-08-02 11:12 UTC
### Reporting an Issue or Missing Feature
Cannot add new site owners to existing sites as global admin via command Set-PnPTenantSite

### Expected behavior 
Set-PnPTenantSite should add new site owners even if you are not a current owner of this site. 

### Actual behavior 
Set-PnPTenantSite : The remote server returned an error: (401) Unauthorized.
At line:1 char:1
+ Set-PnPTenantSite -Url "https://****.sharepoint.com/sites/SetOwner ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Set-PnPTenantSite], WebException
    + FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.SetTenantSite

### What is the version of the Cmdlet module you are running?
This issue persists since version 1.6.0. 

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by ToddKlindt** [comment] 2021-08-02 14:06
Have you tried version 1.7.0? It fixed another PnPTenantSite authorization issue that existed in 1.6.0.

**Comment by nerodrom** [comment] 2021-08-02 14:18
Yes, both - 1.60 and 1.70

**Comment by ToddKlindt** [comment] 2021-08-02 15:20
I think the command is solid. I was just able to use it like this and it worked.
![image](https://user-images.githubusercontent.com/2659747/127884874-437f9d7d-05b3-463f-960e-c06895d3e227.png)
Do you have another user or another tenant you can test with?

**Comment by nerodrom** [comment] 2021-08-03 05:44
Hi Todd, have you tried to add an new site owner, too? Be sure that the user who is running the command, is not a site owner. My service account is a SharePoint admin, global admin should work, too.

**Comment by edmund-davis** [comment] 2021-08-04 15:29
I'm seeing similar behaviour on 2 tenants with 1.7.9 (preview) installed.
Could this be related to issues which were recently addressed relating to Get-PnPTenantSite? 
https://github.com/pnp/powershell/issues/927

**Comment by ollimenzel** [comment] 2021-08-05 09:43
I'm having the same Problem trying to update the sharing permissions for SiteCollections.
I'm running my Script under SharePoint App-only principal with tenant permissions
![image](https://user-images.githubusercontent.com/11551755/128329181-aaf97fbd-758e-4448-9864-1d66ee71b63f.png)
The script was running for month now, but stopped working 2-5 days ago. With 401 error.
I even tried to create a new App permission, but it's giving me the same error

**Comment by dbahnms** [comment] 2021-08-09 05:58
Same error here. We are not able to set owners to sites via Set-PnPTenantSite.
SharePointPnP modules are working

**Comment by ollimenzel** [comment] 2021-08-09 06:58
I was able to pin-point the problem even further for me.
This call is working fine:
Set-PnPTenantSite -Identity https://$($tenantName).sharepoint.com/sites/$($EMail) -SharingAllowedDomainList "xxx.com,YYY.com" -SharingDomainRestrictionMode AllowList 
but if I include **-SharingCapability ExistingExternalUserSharingOnly** as needed, I get a 401 message.
Seems to be really strange, that just one parameter isn't working, as of last week

**Comment by taisuke0710** [comment] 2021-08-14 05:24
Hi @ollimenzel,  your bug is similar to #968.
#968 was fixed and fix is included in current nightly version. Could you try nightly version?

**Comment by dbahnms** [comment] 2021-08-16 09:19
I am not sure doing something wrong, but:
Import-Module PnP.Powershell -RequiredVersion 1.7.21
![image](https://user-images.githubusercontent.com/84786547/129540304-16ae53eb-bfa1-4e40-8201-eef9ddf1137c.png)
![image](https://user-images.githubusercontent.com/84786547/129540396-9c7471e4-43c7-41f4-bde9-f50bc4f6c4ca.png)
Get-PnPConnection: 
![image](https://user-images.githubusercontent.com/84786547/129540650-f67a32aa-d3e0-40af-8f38-7d1ba75c23f5.png)

**Comment by ollimenzel** [comment] 2021-08-16 21:43
Hi I was able to use the command again thanks for this.
Also it seems to work with the old PowerShell library too again

**Comment by gautamdsheth** [comment] 2021-09-09 13:17
Hello, apologies for this regression.
Was able to fix it, will be available in tomorrow's nightly.

**Closed** 2021-09-09 13:17 UTC
Labels: bug
