### ISSUE TITLE
[BUG] Getting error when using New-PnPAzureCertificate

### ISSUE THREAD

**Issue by JAK1047** [pnp/powershell#214] opened 2021-02-04 15:00 UTC
### Reporting an Issue or Missing Feature
When trying to use New-PnPAzureCertificate on a Server 2019 box with Powershell 7.1 I get an error of "New-PnPAzureCertificate: The requested operation is not supported.". Running Get-PNPException gives me:

**Message          : The requested operation is not supported.
Stacktrace       :    at System.Security.Cryptography.CngKey.Export(CngKeyBlobFormat format)
                      at System.Security.Cryptography.RSACng.ExportKeyBlob(Boolean includePrivateParameters)
                      at System.Security.Cryptography.RSACng.ExportParameters(Boolean includePrivateParameters)
                      at PnP.PowerShell.Commands.Utilities.CertificateHelper.PrivateKeyToBase64(X509Certificate2
                   certificate, Boolean useLineBreaks)
                      at PnP.PowerShell.Commands.Base.NewPnPAdalCertificate.ProcessRecord()
                      at System.Management.Automation.Cmdlet.DoProcessRecord()
                      at System.Management.Automation.CommandProcessor.ProcessRecord()
ScriptLineNumber : 1**

This works fine in Powershell 5.1. Is the PNP.Powershell module not yet supported for Powershell 7.1?

### Expected behavior 
PFX is exported

### Actual behavior 
Error as stated above.

### Steps to reproduce behavior
$cert = New-PnPAzureCertificate -OutPfx pnp.pfx -OutCert pnp.cer

### What is the version of the Cmdlet module you are running?
1.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment] 2021-02-05 08:51
PnP PowerShell is 100% supported for PowerShell 7.1. Actually it's built-first for that version. Also I am not able to reproduce the issue unfortunately. 

We run different code when you execute the cmdlet on PS 5.1 due to a different underlying .NET Framework, e.g. the code for PS 5.1 is the same as in the legacy SharePointPnPPowerShellOnline module.

Could you try something else? Can you give `Register-PnPAzureADApp` a try? Please update to the latest nightly release (`Update-Module -Name PnP.PowerShell -AllowPrerelease`) as it provides a better experience. The cmdlet will try to create a new app registration on your tenant and it will create certificates too. If it succeeds you can always navigate to your Azure AD and remove the generated app again. However, uses a different approach to export the certificate data because of different requirements. It would help us to pinpoint where it goes wrong on your end.

**Comment by JAK1047** [comment] 2021-02-05 21:35
Sure thing. I'm not back into the office until Tuesday, but I'll give that a whirl to see and let you know.

**Comment by gautamdsheth** [comment] 2021-02-06 12:36
@JAK1047 / @erwinvanhunen  - I tested this issue in Win 10. It happens when you open PS 7 in admin mode. But if you open it normally, it doesn't happen.

**Comment by erwinvanhunen** [comment] 2021-02-06 12:58
That's an interesting finding. I'll debug that.

**Comment by JAK1047** [comment] 2021-02-07 15:41
I can confirm we have admin approval mode set for UAC on our server so all pwsh.exe instances only launch in admin mode. I had a coworker update to nightly and it didn't make a difference. I'll try Register-PnPAzureADApp when I can.

**Comment by erwinvanhunen** [comment] 2021-02-08 16:21
We just merged a fix for the creation of certificates in elevated mode. This fix will be available in the 1.2.18-nightly release which will be available on approximately 4 AM CET on 2021-02-09.

**Comment by JAK1047** [comment] 2021-02-10 18:44
I did get an error when updating

Install-Package: C:\Users\e0172010\Documents\PowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711
Line |
9711 |  … talledPackages = PackageManagement\Install-Package @PSBoundParameters
     |                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The version '1.2.19' of the module 'PnP.PowerShell' being installed is not catalog signed. Ensure that
     | the version '1.2.19' of the module 'PnP.PowerShell' has the catalog file 'PnP.PowerShell.cat' and
     | signed with the same publisher 'CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond,
     | S=Washington, C=US' as the previously-installed module 'PnP.PowerShell' with version '1.2.0' under the
     | directory 'C:\Program Files\PowerShell\Modules\PnP.PowerShell\1.2.0'. If you still want to install or
     | update, use -SkipPublisherCheck parameter.

But after skipping the publisher check I tried it and the issue seems fixed.

**Closed** 2021-02-14 05:04 UTC
Labels: bug
