### ISSUE TITLE
[BUG] - Error when connecting with PS7 and Conditional Access Policy

### ISSUE THREAD

**Issue by Panzerbjrn** [pnp/powershell#904] opened 2021-07-08 12:17 UTC
### Reporting an Issue or Missing Feature
When using Connect-PnPOnline in PowerShell 7 (pwsh), an error occurs.
The commands tried are:
Connect-PnPOnline -Url https://CorpDomain.sharepoint.com -Credentials $Credentials
Connect-PnPOnline -Url https://CorpDomain.sharepoint.com/sites/SiteName/ -Credentials $Credentials

The command works fine using the previous module, SharePointPnPPowerShellOnline, on Windows PowerShell 5.1.

### Expected behavior 
Expected behaviour is that the connection succeeds.

### Actual behavior 
When using Connect-PnPOnline, this error occurs:
Connect-PnPOnline: AADSTS50005: User tried to log in to a device from a platform (Unknown) that's currently not supported through Conditional Access policy. Supported device platforms are: iOS, Android, Mac, and Windows flavors.
Trace ID: 5e5c7364-f203-4ecd-8b2f-e4f91c8de302
Correlation ID: cb0bf44f-2993-4359-b610-91885741b0fa
Timestamp: 2021-07-08 12:07:03Z

### Steps to reproduce behavior
Steps to reproduce:
1) Open PowerShell 7
2) Type the command as above
3) Press enter

### What is the version of the Cmdlet module you are running?
Version is 1.6.0
![image](https://user-images.githubusercontent.com/10132417/124919956-19efe380-dff7-11eb-9dcc-049468146009.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by veronicageek** [comment] 2021-07-09 07:51
@gautamdsheth / @erwinvanhunen - Possibly the same as issue #737.

**Comment by Panzerbjrn** [comment] 2021-07-09 09:22
If this is the same, is it being worked on? The other issue is stale, and if this module is not actually working, then it would be great if the other SharePoint Module could be continued for a while.

**Comment by aungminko93750** [comment] 2021-08-23 09:14
________________________________

**Comment by veronicageek** [comment] 2021-08-31 13:13
@Panzerbjrn - A PR has been merged which hopefully resolve the issue (https://github.com/pnp/pnpframework/pull/440). Update to the nightly release (`1.7.36` minimum) and feedback to know if we can close this issue.

**Comment by veronicageek** [comment] 2021-09-03 16:20
Closing as the issue is resolved.

**Closed by veronicageek** 2021-09-03 16:20 UTC
Labels: bug
