### ISSUE TITLE
Get-PnPFile not releasing local file resource when loading file on Mac

### ISSUE THREAD

**Issue by gingemonster** [pnp/powershell#1529] opened 2022-01-14 16:05 UTC
PSVersion 7.2.1
PSEdition Core
OS: macOS Catalina
Pnp.PowerShell 1.9.0

### Issue Summary
Using Get-PnPFile to download a file to the local disk causes file access issues when later used in Add-PnPFileToSiteTemplate throwing error "The process cannot access the file 'filename' because it us being used by another process".

At a guess on MacOS the stream that was used to create the file is not getting closed / recycled.

Working fine on windows, not working on Mac

### Expected behavior 
Should download file and allow adding to site template

### Actual behavior 
Throws file access error on Mac OS

### Steps to reproduce behavior
```
# get temporary files path
$TemplatePath = [System.IO.Path]::GetTempPath()

# connect to sharepoint site
Connect-PnPOnline -Url https://yourdomain/sites/yourexistingsite -Interactive -LaunchBrowser

# download site template
Get-PnPSiteTemplate -Out $TemplatePath + '/mysitetemplate.xml' -IncludeAllClientSidePages -PersistBrandingFiles -PersistPublishingFiles -IncludeNativePublishingFiles -Force

# download a file that exists on you site to the local disk
Get-PnPFile -ServerRelativeUrl '/sites/yourexistingsite/your document library/yourfile.txt' -Path $TemplatePath -FileName yourfile.txt -AsFile

# try and add file to site template
Add-PnPFileToSiteTemplate -Path $TemplatePath + '/mysitetemplate.xml' -Source $TemplatePath + '/yourfile.txt' -Folder '/your document library' -FileLevel Published
```

### What is the version of the Cmdlet module you are running?
Pnp.PowerShell 1.9.0

### Which operating system/environment are you running PnP PowerShell on?
macOS Catalina

**Comment by veronicageek** [comment] 2022-01-22 21:16
@gingemonster - I'm not very familiar with the `[System.IO.Path]::GetTempPath()` but trying on a Mac it's already giving me some issues. Doing a bit of research, I have found this [closed issue](https://github.com/dotnet/runtime/issues/27771) which is what I get on MacOS Monterey.

And looking at the [Microsoft documentation](https://docs.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath?view=net-6.0&tabs=windows), I don't see MacOS. But once again, I'm not familiar with it.

Does it still download the file when you run the script? (without the last line `Add-PnPFileToSiteTemplate`......)

**Comment by brannmar** [comment] 2022-01-26 19:34
Working on a fix right now, will hopefully be in tomorrow.

**Comment by gautamdsheth** [comment] 2022-01-27 12:54
@brannmar - thanks for looking into this. Will await your PR :) 

Just curious, are you able to repro it on Windows as well ? Is it PS 5 or 7 or both ? 

@veronicageek - is it not working on Mac ?

**Comment by brannmar** [comment] 2022-01-27 14:02
I added a PR https://github.com/pnp/powershell/pull/1569 that solves the issue where Add-PnPFileToSiteTemplate throwed The process cannot access the file 'filename' because it us being used by another process

@gautamdsheth Did you close the issue by accident? 
I was able to reproduce it in windows using PS 7.

**Comment by gautamdsheth** [comment] 2022-01-27 14:33
@brannmar  - yeah my bad, sorry.

Looking into your PR , how is it fixing `Get-PnPFile`  which is what was raised here ? Seems like a separate issue compared to this one.

**Comment by gautamdsheth** [comment] 2022-01-27 14:46
@brannmar - re-reading this, looks like I am mistaken again. Sorry 😟

**Comment by gautamdsheth** [comment] 2022-01-27 14:49
Closing this now, the PR related to this has been merged.
It will be available in tomorrow's nightly , please do reopen the issue if it persists :)

Thank you @gingemonster for raising the issue and @brannmar  for fixing it :)

**Closed by gautamdsheth** 2022-01-27 14:49 UTC
Labels: bug
