### ISSUE TITLE
Issue running Invoke-PnpSiteTemplate inside azure automation

### ISSUE THREAD

**Issue by ahmedrafeq** [pnp/powershell#814] opened 2021-06-16 01:12 UTC
Using Invoke-PnPSiteTemplate inside Azure Automation Runbook.
the script runs successfully locally, but when running inside Azure Automation, get the error below when Invoke command is run.

Method not found: 'System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1Boolean Enumerator.MoveNextAsync()'.

The template was generated using get-pnpsitetemplate
The template has few components:

Documents library (folders and files).
Events web part along with sp list.
Quick links web part.
Two text web part.
Countdown timer web part.
Pnp version 1.6

Thanks

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ x] Other : please specify
         Azure automation

**Comment by RoSchoe** [comment] 2021-07-16 09:34
Same in Visual Studio Code -> local you can use ISE

**Comment by tomaszoida** [comment] 2021-09-30 20:13
The same using 1.7 version on Azure Automation while applying template containing ClientSidePages.

**Comment by jackpoz** [comment] 2021-10-01 07:24
could someone post a small PnP template that can be used to reproduce the issue ? and maybe an example Azure Automation script with the calls to apply the template

**Comment by tomaszoida** [comment] 2021-10-02 19:46
@jackpoz here is example of a script that causes the error. Commenting out Connect-AzAccount makes it work fine. It seams that trying to create pages using Add-PnPPage has the same issue like creating pages via provisioning template.

`param
(
    [string]$SiteUrl = 'https://*****.sharepoint.com/sites/*****'  
)

$accesstoken = 'your access code'
$pnp = '<?xml version="1.0"?><pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema">  <pnp:Preferences Generator="PnP.Framework, Version=1.5.0.0, Culture=neutral, PublicKeyToken=null" />  <pnp:Templates ID="CONTAINER-TEMPLATE-A72F4E02FB844BD695ED597595CB8F13">    <pnp:ProvisioningTemplate ID="TEMPLATE-A72F4E02FB844BD695ED597595CB8F13" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">      <pnp:WebSettings RequestAccessEmail="" NoCrawl="false" WelcomePage="SitePages/AllInitiatives.aspx#Start" SiteLogo="" AlternateCSS="" MasterPageUrl="{masterpagecatalog}/seattle.master" CustomMasterPageUrl="{masterpagecatalog}/seattle.master" CommentsOnSitePagesDisabled="true" QuickLaunchEnabled="true" />	   <pnp:ClientSidePages>	    <pnp:ClientSidePage PageName="AllInitiatives.aspx" PromoteAsNewsArticle="false" Overwrite="true" Title="Wszystkie inicjatywy">        </pnp:ClientSidePage>	          </pnp:ClientSidePages>    </pnp:ProvisioningTemplate>  </pnp:Templates></pnp:Provisioning>'
$Id = [Guid]::NewGuid()
$directoryPath = "C:\Temp\$Id"
$filePath = "$directoryPath\Pages.xml"

Write-Verbose 'Preparing deployment folder...'
New-Item -ItemType directory -Path $directoryPath | Out-Null

$ConnectionName = 'AzureRunAsConnection'
$ServicePrincipalConnection = Get-AutomationConnection -Name $ConnectionName

if ($ServicePrincipalConnection) {
    Connect-AzAccount `
        -ServicePrincipal `
        -TenantId $ServicePrincipalConnection.TenantId `
        -ApplicationId $ServicePrincipalConnection.ApplicationId `
        -CertificateThumbprint $ServicePrincipalConnection.CertificateThumbprint   
}


New-Item -ItemType file -Path $filePath
$pnp | Set-Content -Path $filePath 

Connect-PnPOnline -Url $SiteUrl -Accesstoken $accessToken
Invoke-PnPSiteTemplate -Path $filePath | Out-Null

Write-Output "Cleaning folders..."

if (Test-Path -Path $directoryPath) {
    Remove-Item -LiteralPath $directoryPath -Force -Recurse
    Write-Output "Deployment files removed."
}

`

**Comment by tomaszoida** [comment] 2021-10-05 12:35
I've found out that this bug depends on a version of Az.Accounts module. I've checked that this issue occurs with Az.Account 2.5.0 and does not occur with Az.Accounts 1.6.2. I had 2.5.0 installed in my Azure automation and the script failed, while locally worked fine with 1.6.2. After upgrading to 2.5.0 locally, this script fails also locally.

**Comment by gautamdsheth** [comment] 2021-12-15 06:43
Looks like the Az module is interfering with the PnP module,  not sure we can do anything about it unfortunately.

You can try using PS 7 , that does seem to help with the DLL conflicts. 

Will have to close the issue.

**Closed by gautamdsheth** 2021-12-15 06:43 UTC
Labels: bug, azure-automation
