### ISSUE TITLE
[FEATURE] Allow "-PageSize"  in Get-PnPFileInFolder command 

### ISSUE THREAD

**Issue by Ofer-Gal** [pnp/powershell#4330] opened 2024-09-23 07:29 UTC
Get-PnPFileInFolder in a folder having more than 5000 files causes the error:
`The attempted operation is prohibited because it exceeds the list view threshold.`

You have a solution for Get-PnPListItem with -PageSize less than 5000.

If possible, would you please apply same option to commands that get files like Get-PnPFileInFolder 

Thank you.

**Comment by gautamdsheth** [comment] 2024-09-25 18:23
Closing this as duplicate of this feature request : https://github.com/pnp/powershell/issues/4141

**Closed by gautamdsheth** 2024-09-25 18:23 UTC
Labels: enhancement

**Comment by gautamdsheth** [comment] 2024-12-25 14:20
@Ofer-Gal - this has been fixed in the latest nightly builds !

**Comment by Ofer-Gal** [comment] 2024-12-27 07:43
Thank you
