### ISSUE TITLE
[BUG] Sync-PnPAppToTeams Authentication Method is not allowed

### ISSUE THREAD

**Issue by thehorseofcourse** [pnp/powershell#2501] opened 2022-10-27 15:08 UTC
### Reporting an Issue or Missing Feature
I am reporting a bug

### Expected behavior 
Using `Sync-PnPAppToTeams` should deploy an App in the SharePoint App catalog to Teams

### Actual behavior 
I am currently trying to deploy an App that is in my SharePoint App catalog to Teams. I first connect to my app catalog with `Connect-PnPOnline` with an account which has global admin, SharePoint Admin and Teams Admin permissions. 

I then get the following error when running `Sync-PnPAddToTeams`

![image](https://user-images.githubusercontent.com/84247314/198973985-b641796b-dae6-476f-b475-827c669c854d.png)

### Steps to reproduce behavior
Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/apps
Sync-PnPAppToTeams -Identity "AppID"

OR 
Connect-PnPOnline -Url https://contoso.sharepoint.com/sites/apps -ClientId $(SPFxclientId) -CertificatePath $certificatePath -CertificatePassword $SecurePassword  -Tenant $tenantName
Sync-PnPAppToTeams -Identity "AppID"

### What is the version of the Cmdlet module you are running?
![image](https://user-images.githubusercontent.com/84247314/198326831-14351369-c355-4510-bbb2-9fb067c6fbbc.png)

### Which operating system/environment are you running PnP PowerShell on?
- [X ] Windows

**Comment by gautamdsheth** [comment] 2022-10-27 19:37
Hii looks like some issue with your installation, this is not a bug.

Can you maybe try to uninstall and re-install ? or maybe install it on a different machine.

**Comment by thehorseofcourse** [comment] 2022-10-28 07:03
I've uninstalled and tried again. Get the same error. Tried on another machine. Get the same error. Colleague gets the same error.
Do you have any other suggestions please as to how i can rectify this?

**Comment by asadrefai** [comment] 2022-10-28 10:18
Hi Dave (@thehorseofcourse), 
Unfortunately I am also getting the same error. 
CC: @gautamdsheth

**Comment by gautamdsheth** [comment] 2022-10-28 19:26
What is the exact error that you are facing ?

The one in the screenshot is "... is not recognized as a cmdlet , ... etc" . Is a generic error and has nothing to do with PnP PowerShell.

Maybe this link can help:

https://techcommunity.microsoft.com/t5/windows-powershell/the-term-is-not-recognized-as-the-name-of-a-cmdlet/m-p/1414518

**Comment by thehorseofcourse** [comment] 2022-10-31 09:20
@gautamdsheth I have been an idiot and copied the wrong screenshot. Very sorry. I have updated with the actual problem. Sorry for the inconvenience.

**Comment by gautamdsheth** [comment] 2022-10-31 17:18
@thehorseofcourse / @asadrefai - looks like you are using Weblogin method to authenticate. Would suggest that you change the approach and use a different authentication model for SharePoint via OAuth and an Azure AD application.

Weblogin is legacy, insecure and will be removed at some point in future.

**Comment by thehorseofcourse** [comment] 2022-11-01 09:19
Thanks @gautamdsheth will give it a go

**Comment by thehorseofcourse** [comment] 2022-11-09 14:26
@gautamdsheth What permissions would be needed on an app reg. To get this working, I've added a few Application for graph and sharepoint Sites.Fullcontrol, TeamsAppInstallation, AppCatalog still getting the same error. Do I need Delegated permissions instead?

**Comment by gautamdsheth** [comment] 2022-11-15 19:57
Am moving this to discussion, I usually use delegated permissions and works fine.
If it doesn't work with application permissions, then the issue lies with the API itself in which case we can't do anything as Microsoft owns the API.

**Closed as completed** 2022-11-15 19:57 UTC
Labels: more info needed, not a bug
