### ISSUE TITLE
[BUG] Add-PnPTeamsChannel: Failed to execute Skype backend request GetThreadS2SRequest.

### ISSUE THREAD

**Issue by khha** [pnp/powershell#3716] opened 2024-01-29 16:30 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
I expect a new channel without error

### Actual behavior 
I try to create a new channel and get an error

### Steps to reproduce behavior
Connect-PnPOnline https://myCompany.sharepoint.com/sites/teamify46 -Interactive
Add-PnPTeamsChannel -Team $myTeamGuid -DisplayName "myChannelName"

### What is the version of the Cmdlet module you are running?
2.3.0

### Which operating system/environment are you running PnP PowerShell on?
- [ X] Windows

**Comment by gautamdsheth** [comment] 2024-01-29 18:53
Hi @khha , this is a duplicate of https://github.com/pnp/powershell/issues/3703 , has been fixed in nightly builds .  

Please update your PnP PowerShell to the latest nightly builds which contains the fix for this .

**Closed by gautamdsheth** 2024-01-29 18:53 UTC
Labels: bug

**Comment by khha** [comment] 2024-01-30 10:55
Ok, thank you
