### ISSUE TITLE
Register-PnPAzureADApp fails in the nightly builds (including the current latest 1.2.17)

### ISSUE THREAD

**Issue by michael-jensen** [pnp/powershell#237] opened 2021-02-08 22:31 UTC
### Reporting an Issue or Missing Feature
The issues do not exist in the latest stable release (1.2.0) but were introduced in the 1.2.x nightly releases - I saw a different issue last week with 1.2.10-.14 than I am seeing today with 1.2.17.

### Expected behavior 
When I run the script I expect an AAD app to be registered with a self signed certificate, and the defined permissions granted.

### Actual behavior 
With builds 1.2.10-.14 (I didn't try earlier or later other than 1.2.17 today) I receive the following error when the cmdlet attempts to prompt for granting app permission consent

![image](https://user-images.githubusercontent.com/8461914/107289383-cb272900-6a19-11eb-8da9-286c99ab8cc8.png)

When I tried build 1.2.17 the cmdlet fails when it attempts to create the app, crashes and closes my PowerShell 7.1 console so I didn't see what the error is.

### Steps to reproduce behavior
Run the Register-PnPAzureADApp cmdlet, creating a self signed certificate that saves to disk and user store, on builds 1.2.14 for the first issue and 1.2.17 for the second issue.

### What is the version of the Cmdlet module you are running?
1.2.14 and 1.2.17

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by erwinvanhunen** [comment] 2021-02-09 15:14
I am not able to reproduce your issue:

![image](https://user-images.githubusercontent.com/7666381/107383452-4b6c8d80-6af1-11eb-8cac-0f37520cf7b8.png)

A few questions:
What type of authentication do you use with the cmdlet? -Interactive or -DeviceLogin?
Are you running in an elevated powershell session or a normal user session?
Are you specifying your own permissions? If so, what are those?

**Comment by michael-jensen** [comment] 2021-02-09 17:06
Thanks for the quick reply @erwinvanhunen 

I am running the cmdlet with PnP 1.2.17-nightly in an elevated PS session (version 7.1), authenticating with -DeviceLogin, providing my own set of permissions; my call to the cmdlet looks like this

```
$scopes = 'SPO.Sites.FullControl.All', 'SPO.TermStore.ReadWrite.All'
$result = Register-PnPAzureADApp -ApplicationName $appName -Tenant "$tenant.onmicrosoft.com" -OutPath $certPath -Scopes $scopes -CertificatePassword $certPassword -Store CurrentUser -DeviceLogin
```

I managed to capture a screenshot of the error before the PS console crashed:

![image](https://user-images.githubusercontent.com/8461914/107399712-e5aee000-6ab5-11eb-81b6-86c745c4bdd0.png)

Please let me know if you need any additional info.

**Comment by erwinvanhunen** [comment] 2021-02-09 17:37
For now I propose to update to version 1.2.18-nightly, which fixes an issue with creating certificates in elevated mode. I also recommend you to use -Interactive instead of -DeviceLogin as I just found an issue with the cmdlet trying to launch the consent flow when using -DeviceLogin. I'm going to work on that, but I cannot guarantee it will make it the upcoming nightly.

**Comment by erwinvanhunen** [comment] 2021-02-09 18:54
For now I propose to update to version 1.2.18-nightly, which fixes an issue with creating certificates in elevated mode. I also recommend you to uto the -Interactive switch instead of -DeviceLogin as I just found an issue with the cmdlet trying to launch the consent flow when using -DeviceLogin. I'm going to work on that, but I cannot guarantee it will make it the upcoming nightly.

**Comment by michael-jensen** [comment] 2021-02-09 20:00
@erwinvanhunen I tried 1.2.18-nightly in an elevated PS console, using -Interactive (instead of -DeviceLogin) with the defined scopes 'SPO.Sites.FullControl.All', 'SPO.TermStore.ReadWrite.All'.

The app was created, but I received the following error during the consent process (after I selected the logged in admin user):

![image](https://user-images.githubusercontent.com/8461914/107420843-33cfdd80-6ace-11eb-8126-836f37e0b8fa.png)

Please let me know if you need any additional info.

**Comment by erwinvanhunen** [comment] 2021-02-09 20:06
Ah... I just realize what's happening here... in your case you are -only- registering SharePoint permissions. However, in order for us to launch the consent flow with the interactive login we have to acquire an access token. We acquire this token for the Graph... But in your case, exactly what it says, it's not able to acquire that token as you did not register a Graph permission.

I just merged a fix for the other issues, but this one is still outstanding. Working on that one now.

**Comment by erwinvanhunen** [comment] 2021-02-09 20:27
Just merged the fix for the issue you had with Interactive login. It will all be available in 1.2.19-nightly in a few hours from now (we build the nightlies around 4 AM CET time, so in 6.5 hours it will be available).

**Comment by michael-jensen** [comment] 2021-02-09 21:48
Thanks for the really quick turnaround on this @erwinvanhunen 

I just got my fork up to date (so I could create a PR #249 for a small issue where the cached cert file wasn't getting cleaned up on disconnect) and noticed that there are some compilation issues based on this [commit](https://github.com/michael-jensen/powershell/blame/7ec39f77928d3628538ffc2a967b46a937915529/src/Commands/Base/PnPConnectionHelper.cs#L31).

**Comment by erwinvanhunen** [comment] 2021-02-09 21:55
Yes it will not compile yet until the PnP Framework is published too. This will happen tonight before we built the nightly release of PnP PowerShell. We schedule our builds and nightly releases sequentially. PnP Core SDK first, then the PnP Framework, then PnP PowerShell as we have a dependency chain like that.

You can compile it but you need would need a local copy of the those two other repositories. Or wait until tomorrow.

**Comment by michael-jensen** [comment] 2021-02-09 23:06
Ah yes, of course - thanks @erwinvanhunen !

**Closed** 2021-03-01 02:06 UTC
Labels: bug, no-issue-activity
