### ISSUE TITLE
[BUG] New-PnpTerm is changing ASCII ampersand (& - 38) to Unicode ampersand (& - 65286)

### ISSUE THREAD

**Issue by denicomp** [pnp/powershell#2137] opened 2022-07-13 02:07 UTC
### Reporting an Issue or Missing Feature
New-PnpTerm is changing an ampersand (&) to a Unicode character.

[NOTE: Unsure whether New-PnpTerm is doing this or SharePoint...]

### Expected behavior 
The term I create should have exactly the same characters and encoding as I have given it

### Actual behavior 
When the term I create has an ampersand in it, it is being converted to a Unicode "full width ampersand" &#65286

### Steps to reproduce behavior

Assume there is a TermGroup named "Test Group" and a TermSet named "Test Set"
```
# Set a variable to the string with a plain ASCII ampersand
$newTerm = "First & Second"

# Convert the 6th character (the ampersand) to display its int value
[char[]]$newTerm.substring(6,1) | %{ "$_ -> " + [int]$_ }

& -> 38

# Create the term
$term = New-PnpTerm -TermSet "Test Set" -TermGroup "Test Group" -Name $newTerm

# Display the original term and the returned term - ampersand is a "full width" Unicode ampersand - note the slight difference in the second one
$newTerm, $term.Name

First & Second
First ＆ Second

# Convert the 6th character of the term returned from New-PnpTerm to display its int value
[char[]]$term.Name.substring(6,1) | %{ "$_ -> " + [int]$_ }

＆ -> 65286

# The value for the 6th character has changed from 38 (ASCII &) to 65286 (Unicode full width ampersand)
```

### What is the version of the Cmdlet module you are running?
1.11.11

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by Studermarc** [comment] 2022-09-03 23:48
Hi @denicomp,
This issue is not related to PnP PowerShell, but to the term store itself.
Sharepoint termstore automatically converts the & character with the wide character version of the character (\uFF06), it also replaces consecutive spaces into one automatically.
Don't ask me why Microsoft does this, but it is by design and documented here for example:
https://docs.microsoft.com/en-us/previous-versions/office/sharepoint-server/ee576778(v=office.15)?redirectedfrom=MSDN

**Comment by denicomp** [comment] 2022-09-04 01:08
Wow, and it's even documented! Thanks for pointing that out, that's what I suspected. I suppose it's their way of allowing an ampersand without it being interpreted as such.

**Comment by gautamdsheth** [comment] 2022-09-11 20:02
Closing it as it is by design.

**Closed by gautamdsheth** 2022-09-11 20:02 UTC
Labels: bug
