### ISSUE TITLE
[BUG] Not able to use connect Connect-PnPOnline via Azure Automation

### ISSUE THREAD

**Issue by SergiyKostenko** [pnp/powershell#3116] opened 2023-05-16 12:50 UTC
### Reporting an Issue or Missing Feature
I am trying to run my powershell pnp script in Azure Automation runbook.
Version is 7.2.
Same script is working well If I host is as 5.1

### Expected behavior 
Runbook is able to authenticate. 

### Actual behavior 
Getting error:
```
Connect-PnPOnline: 
Line |
  13 |  Connect-PnPOnline -Url $siteUrl -ClientId $clientId -Tenant $tenantId …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Object was not found.
```
### Steps to reproduce behavior
Create runbook (powershell 7.2)
Run script:
`Connect-PnPOnline -Url $siteUrl -ClientId $clientId -Tenant $tenantId -CertificateBase64Encoded $clientCertificate`

### What is the version of the Cmdlet module you are running?
`2.1.1, 2.1.48`

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [x] Other : Azure Automation runbook

**Comment by BlazeOfFeathers** [comment] 2023-05-25 11:03
Probably same issue as here: [https://github.com/pnp/powershell/issues/3092](https://github.com/pnp/powershell/issues/3092)

**Comment by gautamdsheth** [comment] 2023-05-27 19:19
Closing as duplicate of https://github.com/pnp/powershell/issues/3092

**Closed by gautamdsheth** 2023-05-27 19:19 UTC
Labels: bug, azure-automation
