### ISSUE TITLE
[BUG] New-PnPTeamsTeam: Failed to find users with user principal name

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#1640] opened 2022-02-16 19:16 UTC
### Reporting an Issue or Missing Feature
This is a bug 

### Expected behavior 
`New-PnPTeamsTeam` with `-Members` -and/or `-Owner` should not throw errors

### Actual behavior 
`New-PnPTeamsTeam` throws an error below when calling `-Owners`

> New-PnPTeamsTeam: Failed to find users with user principal name

However, the team get created no problem:
![image](https://user-images.githubusercontent.com/5260172/154339813-d976aa59-9f90-4134-b977-89a9b03037dd.png)

### Steps to reproduce behavior
```
'TeamName' | %{ New-PnPTeamsTeam -DisplayName $_ -MailNickName $_ -Owners @veeam.com }
```
![image](https://user-images.githubusercontent.com/5260172/154338747-15839d45-cb31-4b62-8b85-ee6452ec7b80.png)

### What is the version of the Cmdlet module you are running?
```
Name    : PnP.PowerShell
Version : 1.9.47
```

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

### Reference
#1585

**Comment by veronicageek** [comment] 2022-02-16 21:14
@YuriySamorodov - Not sure if this was at a point in time, but I'm not able to reproduce with `1.9.47`, even adding owners & members

<img width="1354" alt="image" src="https://user-images.githubusercontent.com/25181757/154357978-a7520c6b-14b2-4702-9720-4314a51e2581.png">

Can you please try again?

**Comment by mdressel** [comment] 2022-02-24 19:23
@KoenZomers I am getting a similar error, but I am using the current released version 1.9.0.

`Resource 'USERNAME@DOMAIN.COM' does not exist or one of its queried reference-property objects are not present.`

We just upgraded from the previous PnP PowerShell library (not cross platform). So, I tried this same call in that version and it worked.

**Comment by gautamdsheth** [comment] 2022-03-04 09:19
@mdressel - can you try this with the latest nightly in your local machine or a VM and test it ? 

@YuriySamorodov  - any update on this ? Not able to reproduce this at our end :(

**Comment by KoenZomers** [comment] 2022-03-04 13:23
If one of you being able to reproduce wants to privately share a Fiddler trace when this happens, that would be very useful in allowing us to try to figure out why it happens. On our side nobody can reproduce this. Please do not share Fiddler traces here, but share them privately.

**Comment by gautamdsheth** [comment] 2022-03-05 15:40
@YuriySamorodov  or @mdressel - any chance you guys can reproduce this with latest nightly ?? We are approaching closer to a major release and would really like to fix this asap before that :) 
This is a heavily used command, so don't want to ship it buggy 😊

**Comment by mdressel** [comment] 2022-03-07 13:05
Also, we have not had the issue again. But I think the issue may be related to the fact that the users that caused the issue were in a separate AD domain and no one has created a request for a new team since for that AD domain.  Just FYI.

**Comment by thunderstorm654** [comment] 2022-03-11 09:43
Have just encountered a similar error when sending emails using PnP. In our scenario the user principal name in AD was different to the email address. Not sure if this helps investigation!

**Comment by KoenZomers** [comment] 2022-03-11 12:21
> Have just encountered a similar error `Resource 'USERNAME@DOMAIN.COM' does not exist or one of its queried reference-property objects are not present." `when sending emails using PnP. In our scenario the user principal name in AD was different to the email address. Not sure if this helps investigation!

It sure does, because I've been fiddling with that. Can you tell me more? Did you have to provide the UPN or the e-mail address of the user to make it work?

**Comment by thunderstorm654** [comment] 2022-03-11 16:24
> > Have just encountered a similar error `Resource 'USERNAME@DOMAIN.COM' does not exist or one of its queried reference-property objects are not present." `when sending emails using PnP. In our scenario the user principal name in AD was different to the email address. Not sure if this helps investigation!
> 
> It sure does, because I've been fiddling with that. Can you tell me more? Did you have to provide the UPN or the e-mail address of the user to make it work?

Yes, I discovered it wasn't actually emails but group owner/membership changes throwing the error. It appears that using UPN rather than email addresses will work in this scenario when a user's UPN doesn't match their email in AD. Specifically this was with the 'Add-PnPMicrosoft365GroupOwner' cmdlet but I would guess it'll be the same with anything touching Team/Group owners and members! It's generally not recommended as far as I understand it to have different UPN vs email, so I hadn't seen this before!

**Comment by mdressel** [comment] 2022-03-22 17:35
@KoenZomers and @thunderstorm654 I can confirm that in my case the users I have issues with have a different UPN then their email address. Do we think that is something that can/would be fixed in PnP or do I need to come up with a workaround?

**Comment by thunderstorm654** [comment] 2022-03-22 18:06
> @KoenZomers and @thunderstorm654 I can confirm that in my case the users I have issues with have a different UPN then their email address. Do we think that is something that can/would be fixed in PnP or do I need to come up with a workaround?

Hi there's a relatively simple workaround for now. Assuming you've already got an email, you can do this to get their UPN:

```
$pnpUser = Get-PnPUser | Where-Object Email -eq $teamOwnerEmail
$teamOwnerUPN = Get-PnPProperty -ClientObject $pnpUser -Property UserPrincipalName
```

Then just pass that in as the owners of the group/Team, and still works with a collection e.g. of multiple UPNs for multiple owners. There may be some shortcut to getting more properties in the first line but the above works :)

**Comment by mdressel** [comment] 2022-03-22 19:09
@thunderstorm654 I think the logic you gave only works if the user is in the web you are currently connected to? I am going to implement the following which I think works regardless of what connection you have.
`$user = Get-PnpAzureADUser -Filter "mail eq '$email'"`

That object has a `UserPrincipalName` property directly on it.

**Comment by thunderstorm654** [comment] 2022-03-22 20:36
> @thunderstorm654 I think the logic you gave only works if the user is in the web you are currently connected to? I am going to implement the following which I think works regardless of what connection you have. `$user = Get-PnpAzureADUser -Filter "mail eq '$email'"`
> 
> That object has a `UserPrincipalName` property directly on it.

Even better! The PnPUser one will ensure the user in the web, so they don't need direct access (and don't get it), but then by doing that they will end up in the user info list. In my scenario the users are all in that web creating items, so didn't think about it. I like your solution better though as covers all bases, nice :)

**Comment by gautamdsheth** [comment] 2022-03-25 13:04
Hello, thanks for the wonderful discussion here in the issue.

To use the Owners and Members parameters, you will need to provide the UPN.
The underlying Graph API that we use also has the same requirement. 

Both the approaches mentioned above by @mdressel  and @thunderstorm654 will work and fetch UPN values which you can then pass to this cmdlet.

So, if your email is different from your UPN, then this will not work, so please use the UPN values.
We have also updated the New-PnPTeamsTeam docs to better clarify the same.
Will close the issue for now, feel free to let us know if issue still exists  :) 

Happy weekend, stay awesome 🙏😊

**Closed by gautamdsheth** 2022-03-25 13:04 UTC
Labels: bug

**Comment by LastGunslinger** [comment] 2022-05-11 16:19
I wanted to add that this isn't just an issue when a user's UPN and email don't match. I am using release 1.10.0, and am unable to use the -Owners param in teams creation because for some inexplicable reason the search against the UPN is case-sensitive. For example, if I have a user whose UPN in AzureAD is listed as Firstname.Lastname@domain.com, this will work:

```javascript
New-PnPTeamsTeam -DisplayName 'Test Team' -Owners @('Firstname.Lastname@domain.com')
```

But this will not:

```javascript
New-PnPTeamsTeam -DisplayName 'Test Team' -Owners @('firstname.lastname@domain.com')
```

This behavior is consistent, even when the users' UPN and email are identical. This is an annoying problem for us, since the script that we are using is pulling the users from SharePoint, where the casing may not be consistent with what AzureAD has.
