### ISSUE TITLE
[BUG] Add-PnPHubSiteAssociation do not work in a multi geo environment

### ISSUE THREAD

**Issue by komirishetty246** [pnp/powershell#2594] opened 2022-12-01 01:58 UTC
### Reporting an Issue or Missing Feature
When Add-PnPHubSiteAssociation is used as per the help article, the command executes perfectly with in the default Geo, but when tried in non default geo, it errors out as below

Add-PnPHubSiteAssociation: proxy request for hubsite GetByID failed with following error: The remote server returned an error: (401) unauthorized.

### Expected behavior 
Target site associates with the hubsite.

### Actual behavior 
Errors out on non default geo.
Add-PnPHubSiteAssociation: proxy request for hubsite GetByID failed with following error: The remote server returned an error: (401) unauthorized.

### What is the version of the Cmdlet module you are running?
PnP.PowerShell 1.10

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows 2019/10

**Comment by gautamdsheth** [comment] 2022-12-02 10:59
Closing it as a duplicate of #1911

**Closed by gautamdsheth** 2022-12-02 10:59 UTC
Labels: bug

**Comment by praveenbattula** [comment] 2023-02-16 19:46
@gautamdsheth I see it is circular reference through 2 issues back and forth. you closed it by duplicate but in other thread you just closed it. I also face same issue and what is the solution? Or why it is closed with no explanation. Please suggest.

**Comment by veronicageek** [comment] 2023-02-17 09:08
@praveenbattula - Issue #1911 is not closed
