### ISSUE TITLE
Clear-PnPDefaultColumnValues does nothing?

### ISSUE THREAD

**Issue by jeroenbrussich** [pnp/powershell#2043] opened 2022-06-28 07:52 UTC
### Discussed in https://github.com/pnp/powershell/discussions/2034

<div type='discussions-op-text'>

<sup>Originally posted by **jeroenbrussich** June 25, 2022</sup>
I have a Documentlibrary on which I want to remove some default Column Values.
Idealiter, I only would want to remove some default Values on some folders, but right now I'm desperate enough to nuke all default Values on all Folders and just start over :)

Chances are I don't quite understand how the command is run, so any help would be welcome.

```
$sharepointSite = "mySharepoint.online/sites/SITE"
Connect-PnPOnline -Url $sharePointSite -ClientId $clientID -Tenant $tenant -Thumbprint $thumbPrint -ErrorAction Stop

# $folder is a folder in `documents`  (List ID= 'C45604CF-73A7-451E-98A0-F0791D8FC3C7)

#  FOLDER = "100008"

Clear-PnPDefaultColumnValues -List 'documents' -Field werkterrein -Folder '100008' 
Clear-PnPDefaultColumnValues -List 'C45604CF-73A7-451E-98A0-F0791D8FC3C7' -Field werkterrein -Folder '100008' 

#   FOLDER = 100008

Clear-PnPDefaultColumnValues -List 'documents' -Field werkterrein -Folder 100008 
Clear-PnPDefaultColumnValues -List 'C45604CF-73A7-451E-98A0-F0791D8FC3C7' -Field werkterrein -Folder 100008 

#   NO FOLDER - RESET FIELD ON TOPFOLDER

Clear-PnPDefaultColumnValues -List 'documents'
Clear-PnPDefaultColumnValues -List 'C45604CF-73A7-451E-98A0-F0791D8FC3C7' 

```

My parameters seem to be correct, When I change $sharepointSite to only "mySharepoint.online", I get an error.
However, when I fiddle with -List, or -Field, things are becoming interesting.

The command runs for an equal amount of time, whether I include -Field or not.
What's more, when I -List a non-existent List (Let's say: 'C45604CF-73A7-451E-98A0', or DOCS'), the command keeps running the same amount of time. I get no errors. So it looks like It's timing out?

Using the parameter -verbose does nothing.

So I'm stuck, don't quite know what's going on/wrong and can't debug.

HELP :)
</div>

**Comment by CallumCrowley** [comment] 2022-08-08 15:07
@jeroenbrussich is the type of column a managed metadata column? (the column you're trying to clear default values for)

**Comment by klaaslauwers** [comment] 2022-11-03 13:25
Same issue here
@CallumCrowley Indeed, for MMD columns

**Comment by jackpoz** [comment] 2024-07-10 22:18
> UPDATE - It does work when I add a path in the Folder parameter:

I can confirm that passing a path to the `-Folder` parameter without the "/" prefix does nothing, which seems to be most of the cases reported in this issue. I opened a PR at https://github.com/pnp/powershell/pull/4088 that adds the "/" prefix as needed.

**Comment by gautamdsheth** [comment] 2024-07-17 09:12
Closing this as it has been fixed. 
Will be available from tomorrow's nightly builds as well as the next major version

**Closed by gautamdsheth** 2024-07-17 09:12 UTC
Labels: bug, reproduced, pending team discussion
