### ISSUE TITLE
[BUG] - Set-PnPDefaultPageLayout cmdlet throws an error that "Cannot find Page Layout with name xxxx"

### ISSUE THREAD

**Issue by hemantkabra** [pnp/powershell#3772] opened 2024-02-21 07:20 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
While using `Set-PnPDefaultPageLayout` cmdlet, it should set a specific page to be the default page layout/template for a SharePoint Site.

### Actual behavior 
While running the `Set-PnPDefaultPageLayout` cmdlet, getting below error and it is not setting up an already created page template as the default. Here is the Error message:

**`Set-PnPDefaultPageLayout: Cannot find Page Layout with name 'Templates/HomePageTemplate.aspx'.`**

### Steps to reproduce behavior
1. Create/Setup a Page Template in a communication site. For example, HomePageTemplate.aspx
2. If Page Template is already available, skip the first step.
3. Once page template is available, use the below command to setup that page template as default page template:
`Set-PnPDefaultPageLayout -Title "Templates/HomePageTemplate.aspx"`
**Note:** In my case, page template is named "HomePageTemplate.aspx" and available under the "Templates" folder.
4. After running the error, you should expect the below error:
**`Set-PnPDefaultPageLayout: Cannot find Page Layout with name 'Templates/HomePageTemplate.aspx'.`**

**Important Note:** The page is already available in the Site Pages Library. When we try to fetch the page using below command it works fine and gives the expected response,

`Get-PnPPage -Identity "Templates/HomePageTemplate.aspx"`

### What is the version of the Cmdlet module you are running?
PnP.PowerShell - 2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by a1mery** [comment] 2024-02-21 13:34
Hi,

I have the same behavior on my side.
However, I'm not sure that this is a bug. The doc says it **works for publishing sites** (classic site template). So it won't work for modern communication sites.
[Set-PnPDefaultPageLayout](https://pnp.github.io/powershell/cmdlets/Set-PnPDefaultPageLayout.html)

**Comment by hemantkabra** [comment] 2024-02-22 06:32
@a1mery I had tried this command earlier on the communication sites and it was working fine, but recently it stopped working.. We tried on multiple tenants from multiple machines, but received the same error.. so let see if some one from the community can help us with this.

**Comment by gautamdsheth** [comment] 2024-02-25 16:24
hi @hemantkabra , as @a1mery mentioned this is by design. The docs state that it would work in publishing sites, so shouldn't be used in a modern site collections.

Closing this.

**Closed by gautamdsheth** 2024-02-25 16:24 UTC
Labels: bug
