### ISSUE TITLE
[BUG] - Get-PnPTenantSite - CommentsOnSitePagesDisabled always returns FALSE

### ISSUE THREAD

**Issue by robertcaretta** [pnp/powershell#3755] opened 2024-02-14 17:12 UTC
### Reporting an Issue or Missing Feature
When fetching all sites via Get-PnPTenantSite, the field CommentsOnSitePagesDisabled always returns FALSE. That is incorrect.

### Expected behavior 
When pulling all sites via Get-PnPTenantSite the field CommentsOnSitePagesDisabled field returns the proper value of TRUE or FALSE.

### Actual behavior 
When fetching all sites via Get-PnPTenantSite, the field CommentsOnSitePagesDisabled always returns FALSE. That is incorrect.

### Steps to reproduce behavior
When fetching all sites via this command, and exporting the data to a CSV the field CommentsOnSitePagesDisabled always returns FALSE. **That is incorrect.**

$allSites = Get-PnPTenantSite
$allSites | Export-CSV -Path "\csv\allSites.csv" -Force

When fetching individual sites via this command and exporting to CSV, the field CommentsOnSitePagesDisabled returns the proper value TRUE or FALSE. **That is correct.**

$allSites = Get-PnPTenantSite
$allSites | ForEach-Object {
    Get-PnPTenantSite -Identity $_.Url | Export-CSV -Path '\csv\DataValidation.csv' -Append
}

### What is the version of the Cmdlet module you are running?
2.2.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by a1mery** [comment] 2024-02-14 20:52
Hi,

Have you tried the `-Detailed` parameter? Without this, some attributes will show default values that may not be correct.
[Get-PnPTenantSite](https://pnp.github.io/powershell/cmdlets/Get-PnPTenantSite.html#-detailed)

**Comment by robertcaretta** [comment] 2024-02-14 21:37
Yes. In both cases the column was included, and all values returned FALSE.

**Comment by wilecoyotegenius** [comment] 2024-02-14 22:10
Can you please try a newer version of the module?
I am on 2.3.36 and everything works fine for my tenant:

```
PS >$ts = get-pnptenantsite  https://contoso.sharepoint.com/sites/t2
PS >$ts.CommentsOnSitePagesDisabled
False
PS >$tss = get-pnptenantsite
PS >$t = $tss.Where({$_.Url -eq "https://contoso.sharepoint.com/sites/T2"})
PS >$t.CommentsOnSitePagesDisabled
False
PS >set-pnptenantsite  https://contoso.sharepoint.com/sites/t2 -CommentsOnSitePagesDisabled
PS >$ts = get-pnptenantsite  https://contoso.sharepoint.com/sites/t2
PS >$ts.CommentsOnSitePagesDisabled
True
PS >$tss = get-pnptenantsite
PS >$t = $tss.Where({$_.Url -eq "https://contoso.sharepoint.com/sites/T2"})
PS >$t.CommentsOnSitePagesDisabled
True

```

**Comment by robertcaretta** [comment] 2024-02-14 22:45
I got different results. I tried it with 2.3.0 and the same issue is
present.  Also tried with 2.3.56 nightly build and the same issue is there
as well.
I did force the proper minimum version on PnP when using the Import-Module
command.

Try piping the results to a CSV export just as I have described.

**Comment by wilecoyotegenius** [comment] 2024-02-15 00:15
I was able to reproduce the issue.
It looks like the problem is in CSOM, not PnP.PowerShell module.
Method GetSitePropertiesFromSharePointByFilters from class Microsoft.Online.SharePoint.TenantAdministration.Tenant is always returns CommentsOnSitePagesDisabled='false', whereas GetSitePropertiesByUrl method from that same class returns proper values.  
I think it would be best if CSOM would fix this, as any methods to fix the value on the fly in the cmdlet may result in poor performance (especially for tenants with a large number of sites).

**Comment by gautamdsheth** [comment] 2024-02-15 11:08
hi @robertcaretta , as @wilecoyotegenius  mentioned this is a server side issue.
We display whatever value is returned by the API.

Wont be able to fix this in PnP PowerShell, you would need to raise one MSFT support ticket for this. Only MSFT can fix this.

As mentioned in above comment, specifying the Identity parameter does help in getting accurate values. If not specified, it uses a different method which returns inaccurate data in some cases.

Closing this as by we can't do anything.

**Closed by gautamdsheth** 2024-02-15 11:08 UTC
Labels: bug

**Comment by robertcaretta** [comment] 2024-02-15 14:19
For anyone that finds this, I posted a thread to the SharePoint feedback forum. I didn't feel this merited a support ticket.
https://feedbackportal.microsoft.com/feedback/idea/2062c8f6-0ccc-ee11-92bd-000d3a7a5824
