### ISSUE TITLE
[BUG]Set-PnPMicrosoft365GroupSettings  is returning type conversion error

### ISSUE THREAD

**Issue by pe-ds** [pnp/powershell#4410] opened 2024-10-10 12:09 UTC
### Reporting an Issue or Missing Feature
When calling im Powershell 7:
Set-PnPMicrosoft365GroupSettings -Identity $groupSettingID -Values @{"AllowExternalSenders"="true"} -Group [$groupID]
I get the below error:
Set-PnPMicrosoft365GroupSettings: Cannot implicitly convert type 'void' to 'object'

### Expected behavior 
Please describe what output you expect to see from the PnP PowerShell Cmdlets

### Actual behavior 
Set-PnPMicrosoft365GroupSettings: Cannot implicitly convert type 'void' to 'object'

### Steps to reproduce behavior
Run cmdlet

### What is the version of the Cmdlet module you are running?
2.12.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by jackpoz** [comment] 2024-10-10 12:51
This is a duplicate of https://github.com/pnp/powershell/issues/4263 and it has been fixed already in the nightly builds.

**Comment by gautamdsheth** [comment] 2024-10-10 18:42
Hi @pe-ds , as mentioned above. This has been fixed in nightly builds , closing this.

**Closed by gautamdsheth** 2024-10-10 18:42 UTC
Labels: bug
