### ISSUE TITLE
[BUG] Outdated Microsoft.Graph.Core.dll in PnP.PowerShell

### ISSUE THREAD

**Issue by YuriySamorodov** [pnp/powershell#3735] opened 2024-02-07 17:10 UTC
### Reporting an Issue or Missing Feature
I am reporting a bug.

### Expected behavior 
This is a follow up on #3395 

When PnP.PowerShell and Microsoft.Graph modules are used ion the same script, it causes ```Get-PnPGroup -All``` to fail with the following error:
```
Get-MgGroup_List: Could not load type 'Microsoft.Graph.Authentication.AzureIdentityAccessTokenProvider' from assembly 'Microsoft.Graph.Core, Version=1.25.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
```

According to the blog post https://mortenknudsen.net/?p=2631, the old Microsoft.Graph.Core version 1.25.1.0 from 2021 seems to originate from the module dependencies of PnP.PowerShell.
![image](https://github.com/pnp/powershell/assets/5260172/cb8b2c0d-2f83-47c0-b3cc-e7c7a2c57ecf)

![image](https://github.com/pnp/powershell/assets/5260172/5124cfb9-06a5-4d32-ae2f-ee3c17c7e648)

In 2024 Microsoft.Graph.Core.dll has version ```3.0.9.0```
![image](https://github.com/pnp/powershell/assets/5260172/2a957f4f-a60b-418e-b640-f344b91c4ea5)

Any chance you can equip PnP.PowerShell with the newer version of Microsoft.Graph.Core.dll?

**Comment by gautamdsheth** [comment] 2024-02-08 16:13
Closing as duplicate of 
https://github.com/pnp/powershell/issues/3637

**Closed by gautamdsheth** 2024-02-08 16:13 UTC
Labels: bug

**Comment by nicole-ge** [comment] 2024-04-28 17:32
Hi @gautamdsheth 

Can we reopen this issue? It is a problem of pnp module loading the wrong msgraph core dll
