### ISSUE TITLE
[BUG] Creating list from template not keeping status of content types

### ISSUE THREAD

**Issue by paylord** [pnp/powershell#2627] opened 2022-12-12 03:14 UTC
### Reporting an Issue or Missing Feature
When saving a list as a template and then creating new lists from that template, content types are visible when they were hidden in the source list.

### Expected behavior 
I would expect the status of content types to be consistent when created from a template

### Actual behavior 
The template has 4 content types, but only 3 of them are "Visible on New Button".
The list created from the template has all 4 content types "Visible on New Button".

### Steps to reproduce behavior
#Get the List
$List = Get-PnpList -Identity $ListName 
#Save List as template
$List.SaveAsTemplate($TemplateFileName, $TemplateName, $TemplateDescription, $IncludeData)
$Context.ExecuteQuery()
#Get the Custom List Template
$Ctx = Get-PnPContext
$Web = Get-PnPWeb
$RootWeb = $Ctx.Site.RootWeb
$ListTemplates = $Ctx.Site.GetCustomListTemplates($RootWeb)
$Ctx.Load($RootWeb)
$Ctx.Load($ListTemplates)
Invoke-PnPQuery
$ListTemplate = $ListTemplates | where {$_.Name -eq $ListTemplateName}
#sharepoint online powershell create list from template
$ListCreation = New-Object Microsoft.SharePoint.Client.ListCreationInformation
$ListCreation.Title = $ListName
$ListCreation.ListTemplate = $ListTemplate
$Web.Lists.Add($ListCreation)
Invoke-PnPQuery

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by gautamdsheth** [comment] 2022-12-27 20:20
hi @paylord , your script/code-snippet uses the CSOM methods itself.
Seems like the issue is with the CSOM SDK itself or maybe a server-side issue. 
Would suggest that you raise a ticket with Microsoft detailing these repro steps.
Unfortunately we can't help here. Will close the issue.

**Closed by gautamdsheth** 2022-12-27 20:20 UTC
Labels: bug
