### ISSUE TITLE
[BUG]Periods are excluded from URLs when creating a site with 'New-PnPSite'.

### ISSUE THREAD

**Issue by ShuheiIwama** [pnp/powershell#1076] opened 2021-09-07 13:24 UTC
### Reporting an Issue or Missing Feature
'New-PnPSite' in the SharePointPowerShellOnline module was able to create a SharePoint site with a URL containing a period.
When I create a SharePoint site with 'New-PnPSite' in the PnP.PowerShell module, the URL is generated with the period part removed, even though I specified a string with a period as Alias.
Is this a specification?

### Expected behavior 
I want to generate a SharePoint site URL with a period and a Microsoft 365 Group email address.

### Actual behavior 
[PnP.PowerShell]
As shown below, even if you put a period in Alias, a URL without a period will be generated.
![image](https://user-images.githubusercontent.com/77622455/132349631-2df7437b-939b-43dc-a8ce-426e8db414e3.png)

[SharePointPnPPowerShellOnline]
URL with a period will be generated.
![image](https://user-images.githubusercontent.com/77622455/132351228-bc2f75dc-6227-427d-9443-062f7b73a812.png)

### What is the version of the Cmdlet module you are running?
Version : 1.7.0

### Which operating system/environment are you running PnP PowerShell on?
- [x] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by YuriySamorodov** [comment] 2021-09-08 22:48
Hi @ShuheiIwama 

Same for me:
![image](https://user-images.githubusercontent.com/5260172/132595473-b8d62b82-9246-423e-be4b-39cec12118a6.png)

Looks like this is a platform "feature" as most likely you get pretty much the same experience when creating a site SharePoint Online Admin Center.

As a workaround you may want to specify ```SiteAlias``` parameter. With this parameter in place I was able to create a site with dots in the URL:
![image](https://user-images.githubusercontent.com/5260172/132595524-e58d599b-aa9d-4f42-804d-8a6a0e230db0.png)

May I also suggest you updating your PnP.PowerShell module? We are on 1.7.44 as of September 8th 2021.

**Comment by KoenZomers** [comment] 2021-10-11 00:39
Special characters are being blocked in PnP Framework:
https://github.com/pnp/pnpframework/blob/29e8d01aff7899f0aa1f355f14113b2d30b90dfa/src/lib/PnP.Framework/Utilities/UrlUtility.cs#L224

The SharePoint WebUI also doesn't allow dots in URLs:

![image](https://user-images.githubusercontent.com/5940670/136718756-bfe00607-f080-4e18-a5a8-3dd28e3e167d.png)

Will discuss it in our team, but feels like this is by design.

**Comment by YuriySamorodov** [comment] 2021-10-11 12:58
Appreciate that @KoenZomers.
I might be wrong, however to my understand there should no issue to determine site title as URL can be easily split with something like ```(^.?\/)(.?\/)(.?$)``` In human language it does not really matter how many dots can be located in URL as the portion after the last forward slash will show site title.
But again, I might (and more than likely am) wrong.

**Comment by gautamdsheth** [comment] 2021-12-23 14:25
Hi going to close this as designed, not a bug but a platform feature.
Its not supported via the UI as well, so will also update the SiteAlias to block periods to match the same experience as the Alias parameter.

**Closed by gautamdsheth** 2021-12-23 14:25 UTC
Labels: documentation

**Comment by YuriySamorodov** [comment] 2022-01-26 09:01
Hi @gautamdsheth , looks like Microsoft have changed their mind (again!):
![image](https://user-images.githubusercontent.com/5260172/151133368-9d025e5b-80f6-41c0-a4db-c9ea25a915d1.png)
Now SharePoint Online supports:

- Underscores
- dash
- single quotes (sic!)
- **period**
