### ISSUE TITLE
[BUG] Add-PnPFile not setting Modified & Created dates on list item for uploaded file

### ISSUE THREAD

**Issue by olatodimeji** [pnp/powershell#2524] opened 2022-11-03 16:03 UTC
### Reporting an Issue or Missing Feature
Issue when uploading a file with Add-PnPFile, values for Modified & Created are ignored.

The issue appears to be identical to https://github.com/pnp/PnP-PowerShell/issues/1550 and https://github.com/pnp/powershell/issues/627

### Expected behavior 
Modified and created dates to be set to the values passed in the -Values parameter hashtable

### Actual behavior 
Modified and created dates are set to current time

### Steps to reproduce behavior
PS > Add-PnPFile -Path $path -Folder $folder -Values @{Modified="1/1/2018"; Created="1/1/2017"}

### What is the version of the Cmdlet module you are running?
Can reproduce the issue in both 1.11.0 and 1.5.0

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by JazBInKC** [comment] 2022-12-12 16:41
Experiencing the same issue under version 1.12.32 of PnP.PowerShell.

**Comment by gautamdsheth** [comment] 2023-02-10 14:28
hi @olatodimeji / @JazBInKC - unfortunately couldn't repro it. Can you please try it with the latest nightly builds and let us know ? Do note that the latest nightly builds require PS 7.2.x or later to be installed on your machine.

**Comment by veronicageek** [comment] 2023-02-16 18:31
Also not able to reproduce with `1.12.80`. Closing.

![image](https://user-images.githubusercontent.com/25181757/219455754-00bf3ac8-1aca-4729-9526-8eb4eb084aca.png)

**Closed by veronicageek** 2023-02-16 18:31 UTC
Labels: bug
