### ISSUE TITLE
[BUG] New-PnPTeamsTeam: Adding owners fails if cases do not match

### ISSUE THREAD

**Issue by LastGunslinger** [pnp/powershell#1855] opened 2022-05-11 16:32 UTC
### Reporting an Issue or Missing Feature
Bug

### Expected behavior 
When creating a new team with the New-PnPTeamsTeam command and the -Owners parameter, a new team should be created with specified owners.

### Actual behavior 
A new team is created, but owners are not added, and the below error is displayed:
**New-PnPTeamsTeam: Failed to find users with user principal name <username>**

### Steps to reproduce behavior
If I have a user whose UPN in AzureAD is listed as Firstname.Lastname@domain.com, this will work:

```javascript
New-PnPTeamsTeam -DisplayName 'Test Team' -Owners @('Firstname.Lastname@domain.com')
```

But this will not, and will show the error **New-PnPTeamsTeam: Failed to find users with user principal name <username>**:

```javascript
New-PnPTeamsTeam -DisplayName 'Test Team' -Owners @('firstname.lastname@domain.com')
```
Please note that although this seems very similar to #1640, it is not identical, because in all cases where I have observed this error the UPN and the email of the affected users are the same, so this is not an issue with UPN and email not matching. It seems instead that when the -Owners parameter searches for applicable users, it does so in a case-sensitive manner.

### What is the version of the Cmdlet module you are running?
1.10.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [x ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by veronicageek** [comment] 2022-05-11 20:46
FYI - @gautamdsheth 

I was (strangely) able to reproduce. I can create the teams capitalising my first initial if my UPN format is just the first name (or simply no "dot" in between). For example, my UPN in O365 is `vero@contoso.com`, I can have a lowercase or uppercase `v` or `V` and it works.

But not in the format with a dot. For example if my UPN in O365 is `terry.smith@contoso.com`, then it will indeed **not** work with `Terry.Smith@contoso.com`

![image](https://user-images.githubusercontent.com/25181757/167944621-263c2514-f588-4092-aab8-71e3eddd1edd.png)

**Comment by milanholemans** [comment] 2022-05-13 21:30
Issue happens in this part of the code.

https://github.com/pnp/powershell/blob/f2c41de2fbc6defce6e6cc304b184c3c2a776b8c/src/Commands/Utilities/TeamsUtility.cs#L198-L223

Appears that the bulk add users is case sensitive while the single add user isn't.
When creating a new group, it is possible to define the group owners and members for the new group. Instead of adding them afterwards, we could use this way of adding owners and members directly when creating the group.
I've tested this way of adding members and owners and can say this works case insensitively.
I can make a PR tomorrow with a fix.

**Comment by gautamdsheth** [comment] 2022-05-14 04:40
@milanholemans - if the problem lies with Graph API then I think we can just document it.

we want to use this because it’s faster and we can add 200 users in a single request. Changing to a different endpoint would mean that addition of users to a group would be slower and need more http requests and we would run into more throttling issues.

**Comment by milanholemans** [comment] 2022-05-14 12:06
@gautamdsheth 

Understandable. But the request I was referring to was the create group request. When creating a group, it is possible to provide owners and members directly. The request would look something like this:

`POST https://graph.microsoft.com/v1.0/groups`
```json
{
  "description": "Group with designated owner and members",
  "displayName": "Operations group",
  "groupTypes": [
  ],
  "mailEnabled": false,
  "mailNickname": "operations2019",
  "securityEnabled": true,
  "owners@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/user1@contoso.com"
  ],
  "members@odata.bind": [
    "https://graph.microsoft.com/v1.0/users/user2@contoso.com",
    "https://graph.microsoft.com/v1.0/users/user3@contoso.com"
  ]
}
```

Currently the owners and members are added afterwards while they can be added immediately. Because of this, we make one request less. The only thing I don't know about is whether or not there are limits on how many people you can specify in this call.

**Comment by gautamdsheth** [comment] 2022-05-16 12:09
@milanholemans - yeah we discarded this approach because it is limited to 20 users only. So , you can add a combination of 20 users , ie 10 owners and 10 members , 1 owner and 19 members, 5 owners and 15 members like that.

While they were immediately added to Group, sometimes it wouldn't be reflected in Teams. Also, we had to add Owners as members as well and that kind of twisted logic. So, we decided to add these users using the new bulk API.

**Comment by milanholemans** [comment] 2022-05-16 12:23
> @milanholemans - yeah we discarded this approach because it is limited to 20 users only. So , you can add a combination of 20 users , ie 10 owners and 10 members , 1 owner and 19 members, 5 owners and 15 members like that.
> 
> While they were immediately added to Group, sometimes it wouldn't be reflected in Teams. Also, we had to add Owners as members as well and that kind of twisted logic. So, we decided to add these users using the new bulk API.

I see. It makes sense now. Then I don't know how to fix this issue at this moment. Seems like an inconsistency with the Graph API since a single request is case insensitive while the bulk API is case sensitive.

**Comment by LastGunslinger** [comment] 2022-05-16 14:39
@milanholemans Thank you for looking into this so thoroughly. I assume that this is unintended behavior on the Graph API side as well, is there anywhere that this issue can be raised on their side?

**Comment by gautamdsheth** [comment] 2022-05-16 18:19
Hi @LastGunslinger , you can open an issue on graph docs repo here:

https://github.com/microsoftgraph/microsoft-graph-docs/issues/new?title=&body=%0A%0A%5BEnter%20feedback%20here%5D%0A%0A%0A---%0A%23%23%23%23%20Document%20Details%0A%0A⚠%20*Do%20not%20edit%20this%20section.%20It%20is%20required%20for%20docs.microsoft.com%20➟%20GitHub%20issue%20linking.*%0A%0A*%20ID%3A%207279fc44-89a2-5b5e-1064-a5701880a564%0A*%20Version%20Independent%20ID%3A%20095d95ca-2198-9cfe-ef6a-3a69ed5bcfe9%0A*%20Content%3A%20%5BAdd%20member%20to%20team%20-%20Microsoft%20Graph%20v1.0%5D(https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fgraph%2Fapi%2Fteam-post-members%3Fview%3Dgraph-rest-1.0%26tabs%3Dhttp)%0A*%20Content%20Source%3A%20%5Bapi-reference%2Fv1.0%2Fapi%2Fteam-post-members.md%5D(https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fblob%2Fmain%2Fapi-reference%2Fv1.0%2Fapi%2Fteam-post-members.md)%0A*%20Product%3A%20**microsoft-teams**%0A*%20Technology%3A%20**microsoft-graph**%0A*%20GitHub%20Login%3A%20%40nkramer%0A*%20Microsoft%20Alias%3A%20**MSGraphDocsVteam**

**Comment by gautamdsheth** [comment] 2022-05-21 19:59
Hi @LastGunslinger , will have to close the issue here at our end because we wont be able to fix it. 
Once the Graph team fixes that at the API level,  this should automatically start working with case insensitivity.

**Closed by gautamdsheth** 2022-05-21 19:59 UTC
Labels: bug, reproduced
