### ISSUE TITLE
[BUG] Rename-PNPTenantSite Exception message

### ISSUE THREAD

**Issue by glasserre** [pnp/powershell#2772] opened 2023-02-01 10:12 UTC
### Reporting an Issue or Missing Feature
`
Try{
Rename-PnPTenantSite -Identity $OldURL -NewSiteUrl $NewURL -Wait -ErrorAction Stop
}Catch{
    $PNPException = Get-PNPException
    $PSCmdlet.ThrowTerminatingError($PSitem)
}
`

Please confirm what it is that your reporting

### Expected behavior 
Got something like :

`{
	"odata.error":
		{
			"code":"-109",
			"message":{
				"lang":"en-US",
				"value":"This site address can't be changed.This site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy."}
		}
}`

### Actual behavior 
Get-PNPException return the following :

`{
    "body": {
        "runbook": {
            "name": "PROD-ChangeDMSURL"
        },
        "startedBy": "{scrubbed}",
        "creationTime": "2023-02-01T09:52:41.9834344+00:00",
        "endTime": "2023-02-01T09:52:51.784488+00:00",
        "exception": "{\"odata.error\":{\"code\":\"-109\",\"message\":{\"lang\":\"en-US\",\"value\":\"This site address can't be changed.\\r\\nThis site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy.\\r\\n\"},\"MultiGeoService.ExceptionType\":\"MultiGeoServiceException\",\"MultiGeoService.ExceptionContext\":\"{\\\"Errors\\\":[{\\\"ErrorCode\\\":-109,\\\"ErrorMessage\\\":\\\"This site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy.\\\"}],\\\"Warnings\\\":[]}\"}} ({\"odata.error\":{\"code\":\"-109\",\"message\":{\"lang\":\"en-US\",\"value\":\"This site address can't be changed.\\r\\nThis site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy.\\r\\n\"},\"MultiGeoService.ExceptionType\":\"MultiGeoServiceException\",\"MultiGeoService.ExceptionContext\":\"{\\\"Errors\\\":[{\\\"ErrorCode\\\":-109,\\\"ErrorMessage\\\":\\\"This site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy.\\\"}],\\\"Warnings\\\":[]}\"}})",
        "lastModifiedTime": "2023-02-01T09:52:51.784488+00:00",
        "lastStatusModifiedTime": "2023-02-01T09:52:51.784488+00:00",
        "jobId": "fd6ee4dd-e57a-45ce-a861-dda999796fbb",
        "startTime": "2023-02-01T09:52:51.784488+00:00",
        "status": "Failed",
        "statusDetails": "None",
...
`

Exception property contains many '\' that complexify json parsing.

### What is the version of the Cmdlet module you are running?
1.11.0

### Which operating system/environment are you running PnP PowerShell on?
- [ ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ X] Azure Functions
- [ ] Azure Logic App

**Comment by Studermarc** [comment] 2023-02-01 10:25
Hi, 

I Think the error message says it all: "This site address can't be changed.This site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy."

Which means the operation is blocked, because a records or retention policy is assigned to that site.
You must first remove it, if you want to change the url.

Kind regards

**Comment by glasserre** [comment] 2023-02-01 11:37
Hello @Studermarc 
My Issue is not on the fact that the site is on retention policy but on the formating exception message that contains many '\':
`{\\\"Errors\\\":[{\\\"ErrorCode\\\":-109,\\\"ErrorMessage\\\":\\\"This site's URL can't be changed because the site or a subsite within it is included in an eDiscovery hold or retention policy.\\\"}],\\`
This cause issue when i try to Parse JSON string in Logic App workflow.

**Comment by Studermarc** [comment] 2023-02-01 12:20
Hi @glasserre,

This is most likely because you are converting a json string into a json string again. When parsing a json string to json, all the json characters are escaped with a backslash.
-> the " are converted to \"
-> the \ are converted to \\

So if you parse the following simple json string:
{"key":"value"}

to json, you get
{\"key\":\"value\*}

If you then parse it again to json you get
{\\\"key\\\":\\\"value"\\\"}

Which is what can be observed in your error message. 

Check your code, I'm pretty sure you're parsing the error message to json 2 times, when the error message is already a json string.

**Comment by glasserre** [comment] 2023-02-01 12:34
I parsed nothing in fact, this is the raw exception return by Rename-PNPTenantSite :

![image](https://user-images.githubusercontent.com/2472365/216043575-30d3fc93-486a-4f31-a171-47266b4b4f39.png)

Maybe, what you describe is done somewhere by the commandlet or a 3rd party used by the commandlet ?

**Comment by KoenZomers** [comment] 2023-02-16 08:51
Not sure what we can do here @glasserre. PnP PowerShell just forwards the information received from the backend:

<img width="1812" alt="image" src="https://user-images.githubusercontent.com/5940670/219314953-851c0519-2639-46c1-abad-e33b0a49c091.png">

It looks as simple as it can be without building any dependencies on the returned message format.

**Comment by glasserre** [comment] 2023-02-16 09:03
Hello @KoenZomers 
High probability the bug in on MS side, but if i post an issue to MS, they will said 'We don't support PNP.Powershell, please contact the project team" :)
This bug is just anoying if we want automate rename of site url , cause we can't properly format the output message from the JSON.
Thanks for your job in any case, if not on PNP.Powershell side, maybe you can escalate to MS.

**Comment by KoenZomers** [comment] 2023-02-16 09:09
Sorry but I still don't see the issue. The site I'm testing this against has a retention policy on it, so the outcome is valid and we're passing it directly back to the cmdlet. I guess you might mean you want to go through series of sites to rename them, could hit some that are under retention and would get blocked by this and would like to handle them accordingly. I don't see why you could not do that as such though. What if you just do a string contains on the returned message with a fragment of the error message? There would be no need to parse the entire JSON structure, right? Would make your solution too dependent on the exact JSON structure getting returned, too, which is risky I'd say.

**Comment by KoenZomers** [comment] 2023-02-22 14:00
@glasserre Please share if you still think this is a bug and we can try to see if we can resolve or work around it somehow. As I see it, this works as designed.

**Comment by glasserre** [comment] 2023-02-22 14:15
@KoenZomers As you want as i don't know if the issue come from PNP or from MS.
How i can help you to test ?

**Comment by gautamdsheth** [comment] 2023-03-10 12:37
Closing this issue. We are simply throwing the raw exception message sent by the server. You will have to format it at your end by escaping the slashes.

**Closed by gautamdsheth** 2023-03-10 12:37 UTC
Labels: in review
