### ISSUE TITLE
[BUG] Set-PnPPageTextPart : CSOM service exception

### ISSUE THREAD

**Issue by 280237** [pnp/powershell#631] opened 2021-04-29 06:03 UTC
### Reporting an Issue or Missing Feature
Set-PnPPageTextPart  command is throwing error when I try to set client side text webpart through PowerShell.

### Expected behavior 
The webpart text should be set with the text passed to the command.

### Actual behavior 

Getting this error: _Set-PnPPageTextPart : CSOM service exception_

**A more detailed exception is thrown using Azure Function:** 

ERROR: CSOM service exception Exception : Type : PnP.Core.CsomServiceException Error : HttpResponseCode: 200 Message: Column 'OData__AuthorByline' does not exist. It may have been deleted by another user. /sites/mytestsite/SitePages ClientRequestId: 6fb4c29f-a0e5-2000-c487-16bb23dcb45e ErrorTypeName: "System.ArgumentException" TargetSite : Name : ProcessCsomBatchResponse DeclaringType : PnP.Core.Services.BatchClient, PnP.Core, Version=1.1.27.0, Culture=neutral, PublicKeyToken=null MemberType : Method Module : PnP.Core.dll StackTrace : at PnP.Core.Services.BatchClient.ProcessCsomBatchResponse(CsomBatch csomBatch, String batchResponse, HttpStatusCode statusCode) at PnP.Core.Services.BatchClient.ExecuteCsomBatchAsync(Batch batch) at PnP.Core.Services.BatchClient.ExecuteBatch(Batch batch) at PnP.Core.Model.BaseDataModel`1.RequestAsync(ApiCall apiCall, HttpMethod method, String operationName) at PnP.Core.Model.BaseDataModel`1.RawRequestAsync(ApiCall apiCall, HttpMethod method, String operationName) at PnP.Core.Model.SharePoint.ListItem.SystemUpdateAsync() at PnP.Core.Model.SharePoint.Page.SaveAsync(String pageName) at PnP.Core.Model.SharePoint.Page.Save(String pageName) at PnP.PowerShell.Commands.Pages.SetClientSideText.ExecuteCmdlet() in D:\a\powershell\powershell\src\Commands\Pages\SetPageTextPart.cs:line 36 at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord() in D:\a\powershell\powershell\src\Commands\Base\PnPSharePointCmdlet.cs:line 60 Message : CSOM service exception Data : System.Collections.ListDictionaryInternal Source : PnP.Core HResult : -2146233088 CategoryInfo : WriteError: (:) [Set-PnPPageTextPart], CsomServiceException FullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.Pages.SetClientSideText ErrorDetails : CSOM service exception InvocationInfo : MyCommand : Set-PnPPageTextPart ScriptLineNumber : 82 OffsetInLine : 9 HistoryId : 1 ScriptName : C:\home\site\wwwroot\TestFunc\run.ps1 Line : Set-PnPPageTextPart -Page $newPage -InstanceId $textControl.InstanceId -Text $translatedControlText PositionMessage : At C:\home\site\wwwroot\TestFunc\run.ps1:82 char:9 + Set-PnPPageTextPart -Page $newPage -InstanceId $textControl.I … + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ PSScriptRoot : C:\home\site\wwwroot\TestFunc PSCommandPath : C:\home\site\wwwroot\TestFunc\run.ps1 InvocationName : Set-PnPPageTextPart CommandOrigin : Internal ScriptStackTrace : at <ScriptBlock>, C:\home\site\wwwroot\TestFunc\run.ps1: line 82 PipelineIterationInfo :

### Steps to reproduce behavior

$newPage = Get-PnPClientSidePage "testpage.aspx"
$textControls = $newPage.Controls | Where-Object {$_.Type.Name -eq "PageText"}
$text = "Hello, this is a sample text"   
foreach ($textControl in $textControls){
        Set-PnPPageTextPart -Page $newPage -InstanceId $textControl.InstanceId -Text $text
}

### What is the version of the Cmdlet module you are running?
(you can retrieve this by executing ```Get-Module -Name "PnP.PowerShell" -ListAvailable```)

1.5.27     PnP.PowerShell

### Which operating system/environment are you running PnP PowerShell on?
- [x ] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by prawnz** [comment] 2021-04-30 06:33
I am having the same CSOM Exception when trying to us Invoke-PnPBatch as well. I wonder if they are related

**Comment by jansenbe** [comment] 2021-04-30 09:58
@280237 / @prawnz : I've been able to reproduce and fix this in PnP Core SDK. Issue was due to the fact that we did not correctly handle the odata field name prefixing: when a field starts with an _ that underscore is replaced by OData__ when doing certain SPO rest queries. CSOM however needs the normal field name, so that's why this went wrong.

@prawnz : if you can run get-pnpexception after you see the error that can possibly also clarify if this is also related to an _ field. If not maybe best to create a dedicated issue with more details.

**Comment by 280237** [comment] 2021-04-30 12:19
Thanks @jansenbe for identifying and fixing this. I am using PnP.PowerShell nightly build, so how do I ensure that this fix is available to me?

**Comment by jansenbe** [comment] 2021-04-30 13:04
Wait for the nightly build of the coming night, so you should be able to test this tomorrow

**Comment by gautamdsheth** [comment] 2021-05-16 06:31
Closing it as the fix is available in the nightly build.

**Closed by gautamdsheth** 2021-05-16 06:31 UTC
Labels: bug, no-issue-activity
