### ISSUE TITLE
[BUG] Add-PnPContentTypesFromContentTypeHub throws error - "The type of data at position 248 is different than the one expected"

### ISSUE THREAD

**Issue by himani-chi** [pnp/powershell#1080] opened 2021-09-08 03:58 UTC
### Reporting an Issue or Missing Feature
Issue

### Expected behavior 
Content Type should sync to the site collection

### Actual behavior 
Command throws error.

Add-PnPContentTypesFromContentTypeHub : The type of data at position 248 is different than the one expected.
At line:1 char:1
 Add-PnPContentTypesFromContentTypeHub -ContentTypes $list
CategoryInfo          : WriteError: (:) [Add-PnPContentTypesFromContentTypeHub], InvalidOperationException
 ullyQualifiedErrorId : EXCEPTION,PnP.PowerShell.Commands.ContentTypes.AddContentTypesFromContentTypeHub

### Steps to reproduce behavior
`Connect-PnPOnline -Url $siteUrl -Credentials $userCredential`
`$list = New-Object Collections.Generic.List[string]`
`$list.Add($customCTypeID)`
`Add-PnPContentTypesFromContentTypeHub -ContentTypes $list`

### What is the version of the Cmdlet module you are running?
1.7.44-nightly

### Which operating system/environment are you running PnP PowerShell on?
- [X] Windows
- [ ] Linux
- [ ] MacOS
- [ ] Azure Cloud Shell
- [ ] Azure Functions
- [ ] Other : please specify

**Comment by CallumCrowley** [comment] 2021-09-08 11:02
I'm also experiencing this bug. My logs suggest this was working up until at least Thursday last week (02/09/2021) but running the cmdlet this morning is resulting the in the exact same error reported here.

Steps to reproduce:
`$testConnection = Connect-PnPOnline -Url $siteUrl -Credentials $userCredential -ReturnConnection`
`$list = New-Object Collections.Generic.List[string]`
`$list.Add($contentTypeId)`
`Add-PnPContentTypesFromContentTypeHub -ContentTypes $list -Connection $testConnection`

Cmdlet version: 1.7.0
Operating system/environment: Windows

**Comment by himani-chi** [comment] 2021-09-08 14:55
If you directly run the code used by this commandlet, the error reproduces - 
[https://github.com/pnp/powershell/blob/d27994688ba051092feb4c47f5c95693bfdcf8e8/src/Commands/ContentTypes/AddContentTypesFromContentTypeHub.cs](url).

`Stacktrace       :    at Microsoft.SharePoint.Client.JsonReader.ReadArrayStart()
                      at Microsoft.SharePoint.Client.JsonReader.ReadList[T]()
                      at 
                   Microsoft.SharePoint.Client.Taxonomy.ContentTypeSync.ContentTypeSyndicationResult.InitOnePropertyFromJson(String 
                   peekedName, JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientValueObject.FromJson(JsonReader reader)
                      at Microsoft.SharePoint.Client.JsonReader.ReadJsonObject(Type fallbackType)
                      at Microsoft.SharePoint.Client.JsonReader.Read[T]()
                      at Microsoft.SharePoint.Client.ClientResult` `1.Microsoft.SharePoint.Client.IFromJson.FromJson(JsonReader reader)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
                      at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__53.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__39.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__65.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__28.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__6.MoveNext()
                   --- End of stack trace from previous location where exception was thrown ---
                      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                      at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
                      at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, 
                   Int32 retryCount, String userAgent)
                      at PnP.PowerShell.Commands.ContentTypes.AddContentTypesFromContentTypeHub.ExecuteCmdlet()
                      at PnP.PowerShell.Commands.PnPSharePointCmdlet.ProcessRecord()`


**It looks like data type accepted by SyncContentTypesFromHubSite2 have changed.**

**Comment by CallumCrowley** [comment] 2021-09-08 15:14
Yes, this makes sense. It seems as though Microsoft may have pushed an update meaning the underlying CSOM no longer works? I'm using 1.7.0 rather than nightly and it was definitely working last week, as I've been using it as part of a site provisioning process.

**Comment by kilasuit** [comment] 2021-09-08 15:40
@CallumCrowley did this work when using 1.6.0 of the module or has it always worked with 1.7.0?

**Comment by kilasuit** [comment] 2021-09-08 16:36
Interestingly enough I have just run this with a couple of content types on a brand new site and they have come through even though this error is thrown (using 1.7.0)

**Comment by CallumCrowley** [comment] 2021-09-08 17:13
@kilasuit I've only used this cmdlet with 1.7.0. I did wonder if it would work regardless of the error but it definitely appears to be a bug. As mentioned, it wasn't throwing any errors in my logs from last Thursday so presumably this has been caused by an update to SharePoint itself?

**Comment by himani-chi** [comment] 2021-09-08 20:09
> Interestingly enough I have just run this with a couple of content types on a brand new site and they have come through even though this error is thrown (using 1.7.0) so I think this error is a weird red herring - though it definitely should not throw this message out at all.

That may be true as the error comes while processing the result. 
`public void ReadArrayStart()`
        `{`
            `JsonReader.Token token = this.ReadToken();`
            `if (token.Type != JsonTokenType.ArrayStart)`
            `{`
                `throw new InvalidOperationException(Resources.GetString("JsonDataTypeNotMatch", new Object[] { token.Position }));`
           ` }`
        `}`

I will check if my content types are pulled in, irrespective of the error.

**Comment by CallumCrowley** [comment] 2021-09-09 09:29
> **UPDATE**: My content type is getting pulled in despite the error processing the result.

@himani-chi that's good to know, thanks for confirming

**Comment by himani-chi** [comment] 2021-09-09 14:08
I also tested the method SyncContentTypesFromHubSite2 with the latest three versions of 'Microsoft.SharePointOnline.CSOM' but the error consistently reproduced. 

16.1.21610.12000
16.1.21411.12000
16.1.21312.12000

**Comment by adambu** [comment] 2021-09-14 17:54
Same exact experience here.  In my case even using the underlying method "SyncContentTypesFromHubSite2" produced the same exact results.  Error thrown, and CT pulled.

The PS cmdlet is specifically mentioned in the guidance as the way to work around the issue.  A lot of people are programmatically provisioning site and document libraries so there needs to be a programmatic way to pull the CT.  The error is confusing and makes it difficult to retrofit existing code.  Even though you can work around it, it would have to be redone after the issue if fixed.

**Comment by adambu** [comment] 2021-09-28 04:54
@JosephT93 check the versions shown by @himani-chi.  It is there but undocumented.  The exception will likely go away soon, and it seems to be incidental to the API itself.  You can either handle the exception or wait a little while to see if it is fixed.

**Comment by kilasuit** [comment] 2021-09-29 12:29
>
> Where are people accessing "SyncContentTypesFromHubSite2"? It does not seem available from the Microsoft.SharePointOnline.CSOM package and googling this only returns this page. 

The underlying dll where this method is available is `Microsoft.SharePoint.Client.Taxonomy` 
![image](https://user-images.githubusercontent.com/6355225/135267898-9721c0b4-13f1-4e2f-b512-4fa0fe00e11d.png)
which Fuget.org shows is included in the Microsoft.SharePoint.CSOM package - https://www.fuget.org/packages/Microsoft.SharePointOnline.CSOM/16.1.21714.12000/lib/netstandard2.0/Microsoft.SharePoint.Client.Taxonomy.dll

**Comment by gautamdsheth** [comment] 2021-10-07 20:14
Will have to close this issue because it is an issue from Microsoft's end in CSOM.
Would suggest that you open a ticket with MS support and mention that `SyncContentTypesFromHubSite2` method in CSOM is behaving erroneously.

We wont be able to do anything from our end because we are simply consuming it, so the actual issue lies in a server side fix which only MS can provide. Once they have done that fix, it will be available in the nightly builds as we always use the latest CSOM SDK.

**Closed by gautamdsheth** 2021-10-07 20:14 UTC
Labels: bug

**Comment by h00g** [comment] 2021-11-12 10:24
The new way of adding content types in SharePoint online has arrived.
... but the PnP.Online powershell module still throws an error when using **Add-PnPContentTypesFromContentTypeHub**

> Add-PnPContentTypesFromContentTypeHub: The type of data at position 280 is different than the one expected.

@gautamdsheth 
This topic has been closed but where is the applicable solution?

If it is something in the Microsoft backend that is broken then that may be a root cause, but in reality, as far as I can see, **Add-PnPContentTypesFromContentTypeHub** is still broken.

**Comment by h00g** [comment] 2021-11-12 10:41
Interestingly the only references to **SyncContentTypesFromHubSite2** that can be found online is in this thread!
